### ISSUE TITLE
Oracle VM VirtualBox: ReaR Rescue ISO media stuk/freeze at "Probing EDD (edd=off to disable) ... ok"

### ISSUE THREAD

**Issue by iamgupta24** [rear/rear#2933] opened 2023-02-15 02:57 UTC
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): 
~]# /usr/sbin/rear -V
Relax-and-Recover 2.4 / Git

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
```
~]# cat /etc/redhat-release ; uname -r
CentOS Linux release 7.9.2009 (Core)
3.10.0-1160.49.1.el7.x86_64
```

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
 ~]# cat /etc/rear/local.conf
OUTPUT=ISO
OUTPUT_URL=nfs://192.168.225.254/backups
BACKUP_URL=nfs://192.168.225.254/backups
BACKUP=NETFS
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}"'/media''/var/tmp/''var/crash''/mnt')
#NETFS_KEEP_OLD_BACKUP_COPY=
BACKUP_TYPE=incremental
FULLBACKUPDAY="Sat"
BACKUP_PROG=tar
```

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR): 
Oracle VM VirtualBox 6.1.40

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86_64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
UEFI | GRUB

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
Local SSD

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"):
```
~]# lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT
NAME                        KNAME     PKNAME    TRAN   TYPE FSTYPE      LABEL          SIZE MOUNTPOINT
/dev/sda                    /dev/sda            sata   disk                              8G
|-/dev/sda1                 /dev/sda1 /dev/sda         part xfs                        200M /boot
`-/dev/sda2                 /dev/sda2 /dev/sda         part LVM2_member                7.8G
  |-/dev/mapper/centos-root /dev/dm-0 /dev/sda2        lvm  xfs                        6.8G /
  `-/dev/mapper/centos-swap /dev/dm-1 /dev/sda2        lvm  swap                         1G [SWAP]
/dev/sr0                    /dev/sr0            ata    rom  iso9660     RELAXRECOVER 269.2M
```

* Description of the issue (ideally so that others can reproduce it):
ReaR Rescue media stuck after booting with "Relax-and-Recover "
Loading Kernel ...
Loading initrd.cgz
Probing EDD (edd=off to disable) ... ok

* Workaround, if any:
![Relax-and-RecoverV2 4](https://user-images.githubusercontent.com/24269816/218915721-aa667cef-ce29-47ef-8cc6-b5edc5a5388e.PNG)
![Relax-and-RecoverV2 4_EDD=off](https://user-images.githubusercontent.com/24269816/218915731-1751b1ff-9c93-4812-ba21-a5bd346fa7b1.PNG)

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):

To paste verbatim text like command output or file content,
include it between a leading and a closing line of three backticks like
````
```
verbatim content
```
````

**Comment by schlomo** [comment] 2023-02-15 10:39
Please try again with our latest version 2.7

**Comment by iamgupta24** [comment] 2023-02-16 04:50
Hi @schlomo, 
Thank you so much for your quick response..!!!

I've upgraded the rear version from 2.4 to 2.7 but the problem is still persist. 
![Relax-and-RecoverV2 7](https://user-images.githubusercontent.com/24269816/219271482-c919e82e-d509-4ba3-80f8-36a08b2193dc.PNG)
![Relax-and-RecoverV2 7_EDD=off](https://user-images.githubusercontent.com/24269816/219271487-7c1e34d1-d428-468c-8b3f-01e9065fc118.PNG)

**Comment by jsmeix** [comment] 2023-02-16 08:12
This one seems to be a duplicate of
https://github.com/rear/rear/issues/2843

What is unexpected is that this issue
also happens with ReaR version 2.4 because
I thought my "Overhauled serial console support code"
cf. https://github.com/rear/rear/pull/2699
in ReaR 2.7 caused some regression in some cases.

In
https://github.com/rear/rear/issues/2843
see in particular
https://github.com/rear/rear/issues/2843#issuecomment-1196337765
for the reason (as far as I understand it) and
https://github.com/rear/rear/issues/2843#issuecomment-1196588256
https://github.com/rear/rear/issues/2843#issuecomment-1196592017
for possible solutions.
For the latter solution ReaR version 2.7 is needed.

**Comment by schlomo** [comment] 2023-02-17 10:11
@iamgupta24 can you verify the serial console thought by removing all the `console` kernel command line parameters or maybe setting `console=tty0` or something like this?

Another thought I had is that maybe your VirtualBox VM configuration is the problem. You can try the following to check out that thought:

1. try to boot a distro ISO instead of the ReaR ISO
2. make sure that the recovery VM configuration matches the original VM configuration, especially with regard to machine type, feature flags and set at least 2 or 4 GB for memory (I recently had SLE15.4 crash with only 1GB memory)

BTW, you can simplify your configuration like this:
```
BACKUP_PROG_EXCLUDE+=( /media /var/tmp/ /var/crash /mnt )
```

**Comment by iamgupta24** [comment] 2023-04-21 08:44
@gdha please find the requested output. 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ~]# cat /etc/default/grub
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="crashkernel=auto spectre_v2=retpoline rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet"
GRUB_DISABLE_RECOVERY="true"
~]#

**Comment by gdha** [comment] 2023-04-21 10:13
@iamgupta24 Have a look at https://bugzilla.redhat.com/show_bug.cgi?id=1767612 - I guess grub2 argument "spectre_v2=retpoline" has to be removed.

**Comment by iamgupta24** [comment] 2023-04-22 01:09
@gdha I've removed the reported kernel argument from the grub. However the problem is still persist. 
![ReaRError](https://user-images.githubusercontent.com/24269816/233753832-d8522214-8115-4632-b5fb-ca7102865624.PNG)


~]# cat /proc/cmdline
BOOT_IMAGE=/vmlinuz-3.10.0-1160.83.1.el7.x86_64 root=/dev/mapper/centos-root ro crashkernel=auto rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet LANG=en_US.UTF-8
 ~]# cat /etc/default/grub
GRUB_TIMEOUT=5
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL_OUTPUT="console"
GRUB_CMDLINE_LINUX="crashkernel=auto rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet"
GRUB_DISABLE_RECOVERY="true"
 ~]#

**Comment by gdha** [comment] 2023-04-24 07:49
@iamgupta24 noticed that you upgraded/patched your system in the meantime without any improvement, right?

**Closed** 2023-07-01 02:55 UTC
Labels: waiting for info, support / question, no-issue-activity
