### ISSUE TITLE
Excluded directory being backed up and in wrong place

### ISSUE THREAD

**Issue by Xaimin** [rear/rear#1056] opened 2016-10-30 14:54 UTC
# Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue:
- rear version (/usr/sbin/rear -V):
  Relax-and-Recover 1.19-git201610281605 / 2016-10-28
- OS version (cat /etc/rear/os.conf or lsb_release  -a):
  OS_VENDOR=RedHatEnterpriseServer
  OS_VERSION=7
- rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
````
  OUTPUT=ISO
  OUTPUT_URL=file:///mounts/ts569/backups/gbrix

BACKUP=NETFS
BACKUP_PROG=rsync
BACKUP_URL=file:///mounts/ts569/backups/gbrix/backup
BACKUP_PROG_EXCLUDE=( '/tmp/_'                        \
                      '/dev/shm/_'                    \
                      '/mnt/_'                        \
                      '/mounts/_'                     \
                      '/media/_'                      \
                      '$VAR_DIR/output/\_'            \
                      '/tsminst1/containers/usb_/_'   \
                      '/home/ian/Documents/_'         \
                      '/home/ian/Downloads/_'         \
                      '/home/ian/Music/_'             \
                      '/home/ian/Pictures/_'          \
                      '/home/ian/Videos/_'            \
                      '/home/ian/deluge/_'            \
                      '/home/ian/.cache/_'            \
                      '/home/ian/.cxoffice/_'         \
                      '/home/ian/tmp/_'               \
                      '/mounts/ts-569pro/_'           \
                      '/mounts/ts569/_'               \
                      '/home/tsminst1/tsmlog/_'       \
                      '/tsminst1/tsmdb0_/_'           \
                      '/tsminst1/tsmarchlog/*'        \
                      '/mounts/ds413j' )
````
- Brief description of the issue
  `/tsminst1/containers/usb2` is being backed up as `/usb2`

See output:
````
Relax-and-Recover 1.19-git201610281605 / 2016-10-28
Using log file: /var/log/rear/rear-gbrix-01.log
Using UEFI Boot Loader for Linux (USING_UEFI_BOOTLOADER=1)
Creating disk layout
Excluding component fs:/mounts/ts569
Encrypting disabled
Creating rsync archive '/mounts/ts569/backups/gbrix/backup/gbrix-01/backup'
Preparing archive operationsending incremental file list
etc/rear/
etc/rear/local.conf
home/ian/.config/deluge/state/
Archived 5 MiB [avg 2884 KiB/sec]home/ian/.config/deluge/state/torrents.fastresume
home/ian/.config/deluge/state/torrents.fastresume.bak
home/ian/.config/deluge/state/torrents.state
home/ian/.config/deluge/state/torrents.state.bak
Archived 3 MiB [avg 988 KiB/sec]home/tsminst1/sqllib/db2dump/events/db2optstats.7161.log
home/tsminst1/sqllib/db2dump/stmmlog/stmm.97.log
Archived 46 MiB [avg 3197 KiB/sec]opt/tivoli/tsm/ui/Liberty/usr/servers/guiServer/logs/tsm_opscntr.log
Archived 52 MiB [avg 3156 KiB/sec]tmp/
usb2/04/
usb2/04/0000000000000458.dcf

List of root directory:
# ls -al /

total 304
dr-xr-xr-x.  20 root     root       4096 Oct  6 13:28 .
dr-xr-xr-x.  20 root     root       4096 Oct  6 13:28 ..
-rw-r--r--    1 root     root          0 May 13 21:38 .autorelabel
lrwxrwxrwx.   1 root     root          7 May 12 12:26 bin -> usr/bin
dr-xr-xr-x.   5 root     root       4096 Oct  9 12:01 boot
drwxr-xr-x   20 root     root       3260 Oct 29 20:44 dev
drwxr-xr-x. 156 root     root       8192 Oct 29 10:48 etc
drwxr-xr-x.   4 root     root         31 May 16 10:34 home
lrwxrwxrwx.   1 root     root          7 May 12 12:26 lib -> usr/lib
lrwxrwxrwx.   1 root     root          9 May 12 12:26 lib64 -> usr/lib64
drwxr-xr-x.   2 root     root          6 Aug 12  2015 media
drwxr-xr-x.   3 root     root         18 May 12 16:49 mnt
drwxr-xr-x.   6 root     root         57 Jul 29 09:37 mounts
drwxr-xr-x.   7 root     root         67 Oct  9 11:44 opt
dr-xr-xr-x  287 root     root          0 May 26 14:45 proc
-rw-r--r--    1 root     root     265524 May 26 14:46 .readahead
dr-xr-x---.   8 root     root       4096 May 25 15:43 root
drwxr-xr-x   41 root     root       1320 Oct 29 20:43 run
lrwxrwxrwx.   1 root     root          8 May 12 12:26 sbin -> usr/sbin
drwxr-xr-x.   2 root     root          6 Aug 12  2015 srv
dr-xr-xr-x   13 root     root          0 May 26 14:45 sys
drwxr-xr-x    2 root     root          6 Oct  6 13:28 tftpboot
drwxrwxrwt.  26 root     root       4096 Oct 30 14:49 tmp
drwxr-xr-x    9 tsminst1 tsmsrvrs   4096 Oct 30 06:34 tsminst1
drwxr-xr-x.  13 root     root       4096 May 12 12:26 usr
drwxr-xr-x.  26 root     root       4096 Aug 16 10:19 var
````
- Work-around, if any
  None, have tried explicitly putting `/tsminst1/containers/usb2` in include

**Comment by gdha** [comment] 2016-11-04 14:17
@Xaimin This issue has already been reported before for the `BACKUP=RSYNC` method (issue #871), and a similar issue #993 like yours.
The fix is applying the RSYNC workflow addition to the NETFS workflow. I will test this and release it when I'm satisfied with the fix

**Comment by gdha** [comment] 2016-11-11 13:21
@Xaimin With the above pull request it should be better. Please try it out and let me know what the result was...

**Comment by Xaimin** [comment] 2016-11-11 16:27
@gdha Worked perfectly, thanks.

**Comment by jsmeix** [comment] 2016-11-24 17:54
The issue is marked as "fixed"
so that I asssume it can be closed.

**Closed by jsmeix** 2016-11-24 17:54 UTC
Labels: bug, fixed
