### ISSUE TITLE
Creating EFI USB boot fails on rhel 7

### ISSUE THREAD

**Issue by Rosco-github** [rear/rear#849] opened 2016-05-26 07:46 UTC
* rear version (/usr/sbin/rear -V):
Relax-and-Recover 1.18 / Git

* OS version (cat /etc/rear/os.conf or lsb_release  -a):
OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=7

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
OUTPUT=USB
BACKUP=NETFS
USB_DEVICE=/dev/disk/by-label/REAR-000
BACKUP_URL=usb:///dev/disk/by-label/REAR-000

* Brief description of the issue
issue: Trying to create an EFI enabled USB bootable stick fails. This is caused by this line in 10_create_efiboot.sh

else
    # Hope this assumption is not wrong ...
    if has_binary grub-install; then
        # What version of grub are we using

The assumption is that grub-install is available, while in rhel7 the command is called grub2-install. Also the same file tries to use grub-mkimage while the command available is grub2-mkimage.

Also The package grub2-efi-modules need to be installed or the image creation will fail with: "grub-mkimage: error: cannot open ‘/usr/lib/grub/x86_64-efi/moddep.lst’: No such file or directory."

* Work-around, if any

Create a symlink grub-install -> grub2-install and grub-mkimage -> grub2-mkimage in /usr/local/bin. Also "yum install grub2-efi-modules"

**Comment by gozora** [comment] 2016-05-26 10:19
This one is probably for me :-) ...
EFI USB support is quite new feature, so I was pretty sure that some of the conditions don't need to match all OSes.
I'll certainly take a look how things are on RHEL/Centos 7 (I'm missing these two in my VM collection) and will report back with updates ...

@Rosco-github thanks for reporting this issue ...

**Comment by gozora** [comment] 2016-05-26 17:39
@Rosco-github I've created fix for this issue, hope it will work fine now ...

**Comment by BCITMike** [comment] 2016-06-21 03:48
I don't think I'm having a blocking problem creating the USB key in Centos7, but I am having problems running mkrescue to the EFI formatting USB key.  I have a 4GB Kingston USB stick installed in the server to be backed up.

Firstly, I think this is possibly an error:
$ sudo usr/sbin/rear format --efi /dev/sde
**rear: unrecognized option '--efi'**
USB device /dev/sde must be formatted with ext2/3/4 or btrfs file system
Please type Yes to format /dev/sde in ext3 format:

I bail out of that, and add the --- (this doesn't seem expected/right? Previous issues I read referred to just 'format --efi <usb_device>'), and it completes without error.

$ sudo usr/sbin/rear format -- --efi /dev/sde
USB device /dev/sde must be formatted with ext2/3/4 or btrfs file system
Please type Yes to format /dev/sde in ext3 format: Yes


I've tried using REAR-000 and REAR-EFI (and EFI for output and 000 for USB_DEVICE) in the local.conf, but in all cases, I'm always running out of space on the USB key.  Which label should I be using in local.conf? Test below is using REAR-000 after I saw the OP in this issues thread:

OUTPUT_URL=usb:///dev/disk/by-label/REAR-000
USB_DEVICE=/dev/disk/by-label/REAR-000


$ sudo usr/sbin/rear -v mkrescue

Relax-and-Recover 1.18 / Git
Using log file: /opt/rear/var/log/rear/rear-server.log
Using UEFI Boot Loader for Linux (USING_UEFI_BOOTLOADER=1)
Creating disk layout
Creating root filesystem layout
TIP: To login as root via ssh you need to set up /root/.ssh/authorized_keys or SSH_ROOT_PASSWORD in your configuration file
Copying files and directories
Copying binaries and libraries
Copying kernel modules
Removing all encryption Keys from initrd
Creating initramfs
'/boot/efi/EFI/centos/grubx64.efi' -> '/tmp/rear-efi.Mueke//EFI/BOOT/BOOTX64.efi'
ERROR: Could not copy /tmp/rear.C8bw1NNp1vlJfej/tmp/initrd.cgz to /tmp/rear-efi.Mueke//EFI/BOOT/initrd.cgz
Aborting due to an error, check /opt/rear/var/log/rear/rear-server.log for details


I check the log, and its always running out of space on the USB:

....
2016-06-20 20:19:45 Configuring device for EFI boot
'/boot/vmlinuz-3.10.0-229.1.2.el7.x86_64' -> '/tmp/rear-efi.Mueke//EFI/BOOT/kernel'
'/tmp/rear.C8bw1NNp1vlJfej/tmp/initrd.cgz' -> '/tmp/rear-efi.Mueke//EFI/BOOT/initrd.cgz'
cp: error writing '/tmp/rear-efi.Mueke//EFI/BOOT/initrd.cgz': No space left on device
cp: failed to extend '/tmp/rear-efi.Mueke//EFI/BOOT/initrd.cgz': No space left on device
2016-06-20 20:19:45 ERROR: Could not copy /tmp/rear.C8bw1NNp1vlJfej/tmp/initrd.cgz to /tmp/rear-efi.Mueke//EFI/BOOT/initrd.cgz
=== Stack trace ===
Trace 0: usr/sbin/rear:410 main
Trace 1: /opt/rear/usr/share/rear/lib/mkrescue-workflow.sh:35 WORKFLOW_mkrescue
Trace 2: /opt/rear/usr/share/rear/lib/framework-functions.sh:85 SourceStage
Trace 3: /opt/rear/usr/share/rear/lib/framework-functions.sh:45 Source
Trace 4: /opt/rear/usr/share/rear/output/USB/Linux-i386/10_create_efiboot.sh:40 source
Trace 5: /opt/rear/usr/share/rear/lib/_input-output-functions.sh:150 StopIfError
Message: Could not copy /tmp/rear.C8bw1NNp1vlJfej/tmp/initrd.cgz to /tmp/rear-efi.Mueke//EFI/BOOT/initrd.cgz
===================
2016-06-20 20:19:45 Running exit tasks.
2016-06-20 20:19:45 Finished in 20 seconds
2016-06-20 20:19:45 Removing build area /tmp/rear.C8bw1NNp1vlJfej
removed directory: '/tmp/rear.C8bw1NNp1vlJfej'
2016-06-20 20:19:46 End of program reached


USB key is /dev/sde:

$ df -H
<snip>
192.168.0.2:/volume1/server_backup/rear   12T  805G   12T   7% /mnt
/dev/sde1                                105M  105M     0 100% /tmp/rear-efi.Mueke

$ mount
<snip>
/dev/sde1 on /tmp/rear-efi.Mueke type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=ascii,shortname=mixed,errors=remount-ro)


$ sudo fdisk -l /dev/sde
WARNING: fdisk GPT support is currently new, and therefore in an experimental phase. Use at your own discretion.

Disk /dev/sde: 4005 MB, 4005527552 bytes, 7823296 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: gpt


#         Start          End    Size  Type            Name
 1           34       204799    100M  EFI System      primary
 2       204800      7821311    3.6G  Microsoft basic primary


$ ls -la /dev/disk/by-label
total 0
drwxr-xr-x 2 root root 100 Jun 20 20:19 .
drwxr-xr-x 8 root root 160 Feb  6 20:12 ..
lrwxrwxrwx 1 root root  10 Jun 20 20:19 REAR-000 -> ../../sde2
lrwxrwxrwx 1 root root  10 Jun 20 20:19 REAR-EFI -> ../../sde1


Is it expected to create a primary partition of 100MB and the rest is unused?  Or should the whole 4GB be available for the rescue disk?

Thanks in advance.

Please note, I am a beginner with this and this is my first time trying to get REAR running.  I would like to get this running so that the OS can be restored (and not just files, like duplicity or something), so I'm available to help debug/troubleshoot this.

**Comment by gozora** [comment] 2016-06-21 06:33
Hi,
I was wondering whether 100MB will be enough for EFI, however I was not able to reproduce needs for bigger EFI partition.

Could you please try edit following code in **/usr/share/rear/format/USB/default/30_format_usb_disk.sh** to more appropriate size that could better fit your needs.

e.g.
```
if [[ "$EFI" == "y" ]]; then
        LogPrint "The --efi toggle was used with format - make an EFI bootable USB disk"
        echo "Yes" | parted -s $RAW_USB_DEVICE -- mklabel gpt mkpart primary 0 200Mib mkpart primary 200Mib 100% >&2
...
```

then format your USB stick again and try to run `rear mkrescue/mkbackup` again?

@gdha as you seems to be author of the code, do you think it would be possible to prompt user user for size of EFI partition prior format takes place?

**Comment by BCITMike** [comment] 2016-06-21 07:32
@gozora 

Thanks! That got past the out of space issue, but now fails shortly after:

`2016-06-21 00:18:22 Configuring device for EFI boot
'/boot/vmlinuz-3.10.0-229.1.2.el7.x86_64' -> '/tmp/rear-efi.WCaOs//EFI/BOOT/kernel'
'/tmp/rear.ZyAG1s6PpUzYRpy/tmp/initrd.cgz' -> '/tmp/rear-efi.WCaOs//EFI/BOOT/initrd.cgz'
2016-06-21 00:18:22 Copied kernel and initrd.cgz to /tmp/rear-efi.WCaOs//EFI/BOOT
2016-06-21 00:18:22 Configuring grub 2.0 for EFI boot
grub2-mkimage: error: cannot open `/usr/lib/grub/x86_64-efi/moddep.lst': No such file or directory.
2016-06-21 00:18:22 ERROR: Failed to create BOOTX64.efi
=== Stack trace ===
Trace 0: usr/sbin/rear:410 main
Trace 1: /opt/rear/usr/share/rear/lib/mkrescue-workflow.sh:35 WORKFLOW_mkrescue
Trace 2: /opt/rear/usr/share/rear/lib/framework-functions.sh:85 SourceStage
Trace 3: /opt/rear/usr/share/rear/lib/framework-functions.sh:45 Source
Trace 4: /opt/rear/usr/share/rear/output/USB/Linux-i386/10_create_efiboot.sh:99 source
Trace 5: /opt/rear/usr/share/rear/lib/_input-output-functions.sh:150 StopIfError
Message: Failed to create BOOTX64.efi
===================
2016-06-21 00:18:22 Running exit tasks.
2016-06-21 00:18:22 Finished in 20 seconds
2016-06-21 00:18:22 Removing build area /tmp/rear.ZyAG1s6PpUzYRpy
removed directory: '/tmp/rear.ZyAG1s6PpUzYRpy'
2016-06-21 00:18:22 End of program reached
`

In this Centos 7 install, /usr/lib/grub/x86_64-efi/moddep.lst doesn't exist.  

Now I'm wondering if I really need EFI? I started out today with 1.17.2 and couldn't figure out the issue. I then cloned git to 1.18.1 and saw the error about running out of space, and something that indicated I NEEDED to format the USB for EFI.  /boot has an efi dir...

dmesg | grep "EFI v"
[    0.000000] efi: EFI v2.31 by American Megatrends

Am I now running into the bug that this issue was created for and what you created a possible fix for? If so, I'll take a look at your changes and see if that fixes it.

**Comment by gozora** [comment] 2016-06-21 07:50
I guess we've stopped here:

`${GRUB_MKIMAGE} -o ${EFI_DST}/BOOTX64.efi -p ${EFI_DIR} -O x86_64-efi linux part_gpt ext2 normal gfxterm gfxterm_background gfxterm_menu test all_video loadenv fat`

Just to confirm my doubt, could you run following comand:
`grub2-mkimage -o /tmp/test.efi -O x86_64-efi linux part_gpt ext2 normal gfxterm gfxterm_background gfxterm_menu test all_video loadenv fat`

> Now I'm wondering if I really need EFI?

This is something you must decide ;-), If you want to save trouble switch to legacy boot, if you want to experiment, got for EFI.

**Comment by gozora** [comment] 2016-06-21 07:58
@BCITMike sorry to just put you command without further explanation (I'm a bit deformed :-))
grub2-mkimage will create EFI bootloader in /tmp/test.efi (which you can delete afterwards) it will not mess with your current configuration.

**Comment by BCITMike** [comment] 2016-06-21 08:35
@gozora 

Didn't like that syntax:

$ sudo grub2-mkimage -o /tmp/test.efi -O x86_64-efi linux part_gpt ext2 normal gfxterm gfxterm_background gfxterm_menu test all_video loadenv fat
Prefix not specified (use the -p option).
Usage: grub2-mkimage [OPTION...] [OPTION]... [MODULES]
Try ‘grub2-mkimage --help’ or ‘grub2-mkimage --usage’ for more information.


I even tried backspacing over the "-" in case it was copy/paste issue with keyboard/language, but same.

Help says:

` -p, --prefix=DIR           set prefix directory`

**Comment by gozora** [comment] 2016-06-21 08:38
argh, my bad!

Try `-p /EFI/BOOT`

**Comment by BCITMike** [comment] 2016-06-21 08:39
```
$ sudo grub2-mkimage -o /tmp/test.efi -O x86_64-efi linux part_gpt ext2 normal gfxterm gfxterm_background gfxterm_menu test all_video loadenv fat -p /EFI/BOOT
grub2-mkimage: error: cannot open ‘/usr/lib/grub/x86_64-efi/moddep.lst’: No such file or directory.
```

**Comment by gozora** [comment] 2016-06-21 08:46
:-) ok, confirmed.

After a bit of googling, missing file(s) should be part of package called **grub2-efi-modules** [(rpmfind_link)](https://www.rpmfind.net/linux/RPM/centos/updates/7.2.1511/x86_64/Packages/grub2-efi-modules-2.02-0.34.el7.centos.x86_64.html).

Can you look for such package (or equivalent) on your distro?

**Comment by BCITMike** [comment] 2016-06-21 08:49
Haha, found it right when you did.  I sure as hell hope this doesn't bork anything just by installing it.

```
$ sudo grub2-mkimage -o /tmp/test.efi -O x86_64-efi linux part_gpt ext2 normal gfxterm gfxterm_background gfxterm_menu test all_video loadenv fat -p /EFI/BOOT
$ ls /tmp/test.efi
/tmp/test.efi

```

Sounds like this dependency needs to be added to the epel repo for rear, right?

**Comment by gozora** [comment] 2016-06-21 08:56
> Haha, found it right when you did.

Yeah, but I was first that that counts :-). 

> I sure as hell hope this doesn't bork anything just by installing it.

No, it is safe to install.

> Sounds like this dependency needs to be added to the epel repo for rear, right?

Not sure if dependency directly, because this is EFI specific, but it could be certainly helpful to mentioned it in documentation.

I'll try to find some suitable spot for this.

@jsmeix @gdha any ideas where we could put this info?

**Comment by BCITMike** [comment] 2016-06-21 09:00
I'm thinking that this is no longer an EFI issue, and a generic rear issue I need to open a new issue for? Though, the mkrescue isn't completely successfully, so not sure if EFI issue or not.

```
$ sudo usr/sbin/rear -v mkrescue
Relax-and-Recover 1.18 / Git
Using log file: /opt/rear/var/log/rear/rear-server.log
Using UEFI Boot Loader for Linux (USING_UEFI_BOOTLOADER=1)
Creating disk layout
Creating root filesystem layout
TIP: To login as root via ssh you need to set up /root/.ssh/authorized_keys or SSH_ROOT_PASSWORD in your configuration file
Copying files and directories
Copying binaries and libraries
Copying kernel modules
Removing all encryption Keys from initrd
Creating initramfs
'/boot/efi/EFI/centos/grubx64.efi' -> '/tmp/rear-efi.EtFYw//EFI/BOOT/BOOTX64.efi'
Writing MBR to /dev/sde
Copying resulting files to usb location
ERROR: No files to send (RESULT_FILES is empty)
Aborting due to an error, check /opt/rear/var/log/rear/rear-server.log for details

```

end of the log:

```
2016-06-21 01:50:48 Configuring grub 2.0 for EFI boot
2016-06-21 01:50:48 Doing cleanup of /tmp/rear-efi.EtFYw
2016-06-21 01:50:48 Created EFI configuration for USB
2016-06-21 01:50:48 Including output/default/10_mount_output_path.sh
mkdir: created directory '/tmp/rear.3c3u8RaRHTDspT5/outputfs'
2016-06-21 01:50:48 Mounting with 'mount -v -o rw,noatime /dev/disk/by-label/REAR-000 /tmp/rear.3c3u8RaRHTDspT5/outputfs'
mount: /dev/sde2 mounted on /tmp/rear.3c3u8RaRHTDspT5/outputfs.
2016-06-21 01:50:49 Including output/default/15_save_copy_of_prefix_dir.sh
2016-06-21 01:50:49 Including output/default/20_make_boot_dir.sh
mkdir: created directory '/tmp/rear.3c3u8RaRHTDspT5/tmp/boot'
2016-06-21 01:50:49 Including output/default/20_make_prefix_dir.sh
mkdir: created directory '/tmp/rear.3c3u8RaRHTDspT5/outputfs/server'
2016-06-21 01:50:49 Including output/default/25_create_lock.sh
2016-06-21 01:50:49 Including output/USB/Linux-i386/30_create_extlinux.sh
2016-06-21 01:50:49 USB syslinux version:
2016-06-21 01:50:49 System syslinux version: 4.05
2016-06-21 01:50:49 Features based on syslinux version: 4.05
2016-06-21 01:50:49 Using syslinux prefix: boot/syslinux
2016-06-21 01:50:49 Creating rear/server/20160621.0150/syslinux.cfg
2016-06-21 01:50:49 Creating /rear/syslinux.cfg
2016-06-21 01:50:49 Processing rear/server/20160621.0150/syslinux.cfg
2016-06-21 01:50:49 Creating boot/syslinux/extlinux.conf
'/usr/share/syslinux/cat.c32' -> '/tmp/rear.3c3u8RaRHTDspT5/outputfs/boot/syslinux/cat.c32'
'/usr/share/syslinux/config.c32' -> '/tmp/rear.3c3u8RaRHTDspT5/outputfs/boot/syslinux/config.c32'
'/usr/share/syslinux/cmd.c32' -> '/tmp/rear.3c3u8RaRHTDspT5/outputfs/boot/syslinux/cmd.c32'
'/usr/share/syslinux/cpuid.c32' -> '/tmp/rear.3c3u8RaRHTDspT5/outputfs/boot/syslinux/cpuid.c32'
'/usr/share/syslinux/disk.c32' -> '/tmp/rear.3c3u8RaRHTDspT5/outputfs/boot/syslinux/disk.c32'
'/usr/share/syslinux/host.c32' -> '/tmp/rear.3c3u8RaRHTDspT5/outputfs/boot/syslinux/host.c32'
'/usr/share/syslinux/kbdmap.c32' -> '/tmp/rear.3c3u8RaRHTDspT5/outputfs/boot/syslinux/kbdmap.c32'
'/usr/share/syslinux/ls.c32' -> '/tmp/rear.3c3u8RaRHTDspT5/outputfs/boot/syslinux/ls.c32'
'/usr/share/syslinux/lua.c32' -> '/tmp/rear.3c3u8RaRHTDspT5/outputfs/boot/syslinux/lua.c32'
'/usr/share/syslinux/rosh.c32' -> '/tmp/rear.3c3u8RaRHTDspT5/outputfs/boot/syslinux/rosh.c32'
'/usr/share/syslinux/sysdump.c32' -> '/tmp/rear.3c3u8RaRHTDspT5/outputfs/boot/syslinux/sysdump.c32'
'/usr/share/syslinux/vesamenu.c32' -> '/tmp/rear.3c3u8RaRHTDspT5/outputfs/boot/syslinux/vesamenu.c32'
'/usr/share/syslinux/menu.c32' -> '/tmp/rear.3c3u8RaRHTDspT5/outputfs/boot/syslinux/menu.c32'
'/usr/share/syslinux/chain.c32' -> '/tmp/rear.3c3u8RaRHTDspT5/outputfs/boot/syslinux/chain.c32'
'/usr/share/syslinux/hdt.c32' -> '/tmp/rear.3c3u8RaRHTDspT5/outputfs/boot/syslinux/hdt.c32'
'/usr/share/syslinux/reboot.c32' -> '/tmp/rear.3c3u8RaRHTDspT5/outputfs/boot/syslinux/reboot.c32'
'/usr/share/syslinux/poweroff.com' -> '/tmp/rear.3c3u8RaRHTDspT5/outputfs/boot/syslinux/poweroff.com'
2016-06-21 01:50:49 Created extlinux configuration 'boot/syslinux/extlinux.conf'
2016-06-21 01:50:49 Including output/USB/Linux-i386/83_copy_kernel_initrd.sh
'/boot/vmlinuz-3.10.0-229.1.2.el7.x86_64' -> '/tmp/rear.3c3u8RaRHTDspT5/outputfs/rear/server/20160621.0150/kernel'
'/tmp/rear.3c3u8RaRHTDspT5/tmp/initrd.cgz' -> '/tmp/rear.3c3u8RaRHTDspT5/outputfs/rear/server/20160621.0150/initrd.cgz'
2016-06-21 01:50:49 Copied kernel and initrd.cgz to rear/server/20160621.0150
2016-06-21 01:50:49 Saved /opt/rear/var/log/rear/rear-server.log as rear/server/20160621.0150/rear.log
2016-06-21 01:50:49 Including output/USB/Linux-i386/85_make_USB_bootable.sh
/tmp/rear.3c3u8RaRHTDspT5/outputfs/boot/syslinux is device /dev/sde2
2016-06-21 01:51:21 Writing MBR to /dev/sde
1+0 records in
1+0 records out
440 bytes (440 B) copied, 0.0102611 s, 42.9 kB/s
2016-06-21 01:51:21 Including output/default/94_grub2_rescue.sh
2016-06-21 01:51:21 Including output/default/94_grub_rescue.sh
2016-06-21 01:51:21 Including output/default/95_copy_result_files.sh
2016-06-21 01:51:21 Copying resulting files to usb location
'/opt/rear/usr/share/rear/conf/templates/RESULT_usage_USB.txt' -> '/tmp/rear.3c3u8RaRHTDspT5/outputfs/server/README'
2016-06-21 01:51:21 Saved /opt/rear/var/log/rear/rear-server.log as rear.log
2016-06-21 01:51:21 Including output/default/95_email_result_files.sh
2016-06-21 01:51:21 **ERROR: No files to send (RESULT_FILES is empty)**
=== Stack trace ===
Trace 0: usr/sbin/rear:410 main
Trace 1: /opt/rear/usr/share/rear/lib/mkrescue-workflow.sh:35 WORKFLOW_mkrescue
Trace 2: /opt/rear/usr/share/rear/lib/framework-functions.sh:85 SourceStage
Trace 3: /opt/rear/usr/share/rear/lib/framework-functions.sh:45 Source
Trace 4: /opt/rear/usr/share/rear/output/default/95_email_result_files.sh:8 source
Trace 5: /opt/rear/usr/share/rear/lib/_input-output-functions.sh:150 StopIfError
Message: No files to send (RESULT_FILES is empty)
===================
2016-06-21 01:51:21 Running exit tasks.
umount: /tmp/rear.3c3u8RaRHTDspT5/outputfs (/dev/sde2) unmounted
removed directory: '/tmp/rear.3c3u8RaRHTDspT5/outputfs'
2016-06-21 01:51:23 Finished in 79 seconds
2016-06-21 01:51:23 Removing build area /tmp/rear.3c3u8RaRHTDspT5
removed directory: '/tmp/rear.3c3u8RaRHTDspT5'
2016-06-21 01:51:23 End of program reached

```

**Comment by gozora** [comment] 2016-06-21 09:05
@BCITMike I'd agree here. 
You might have better attention from guys who have much deeper knowledge of rear than I do, (I basically try to mess with EFI booting  ... ) when you open new issue with more fitting description ...

**Comment by jsmeix** [comment] 2016-06-21 09:12
@BCITMike 
on a very first glance it seems your issue in https://github.com/rear/rear/issues/849#issuecomment-227381627
is separated from your initial issue here.

If yes, please submit separated GitHub issues
for separated issues - otherwise different things
get mixed up here until all ends in chaos.

**Comment by jsmeix** [comment] 2016-06-21 09:15
@gozora regarding your https://github.com/rear/rear/issues/849#issuecomment-227380538

I am not a sufficient (U)EFI expert to fully understand
what went on here.

Could you post here a proposal text of what to mention
in the rear documentation.

Then I think it is easy to find an appropriate place in the
rear documentation whereto add that text.

**Comment by gdha** [comment] 2016-06-21 09:21
@Rosco-github @gozora I think it would be good idea to foresee a new variable in default.conf file to be able to overwrite the default size of the FAT partition.

And, the **grub2-efi-modules** - is this specific needed for USB/UEFI? I never needed this requirement before? If yes, then we should add a little prep script for EFI and USB output?

**Comment by jsmeix** [comment] 2016-06-21 09:23
FYI:

On my openSUSE Leap 42.1 system I have
<pre>
/usr/lib/grub2/i386-pc/moddep.lst
/usr/lib/grub2/x86_64-efi/moddep.lst
</pre>
installed by default.
Note for me it is "grub2" not "grub".

Those files belong to the RPMs
<pre>
grub2-i386-pc-2.02~beta2-76.1.x86_64
grub2-x86_64-efi-2.02~beta2-76.1.x86_64
</pre>
respectively.

**Comment by gozora** [comment] 2016-06-21 14:34
@gdha @jsmeix 
> I think it would be good idea to foresee a new variable in default.conf file to be able to overwrite the default size of the FAT partition.

Fine with that, I'll can prepare pull request for it if you want.

> is this specific needed for USB/UEFI? I never needed this requirement before? If yes, then we should add a little prep script for EFI and USB output?

This package (modules) are required by grub(2)-mkimage to create bootloader.efi which is used to EFI  boot from USB. So it is required only if you want to do EFI boot from USB. As this don't seems to be mainstream setup, I think we just could put note to **README.adoc** _REQUIREMENTS_ section.
Something like:
-     mingetty or agetty
-     sfdisk or parted
-     grub2-efi-modules or similar package that provides Grub2 modules (/usr/lib/grub(2)/) if USB recovery on EFI is used

**Comment by gdha** [comment] 2016-07-07 16:54
@gozora sorry for the delay - sure you make prepare a pull request for the summary of above

**Comment by gozora** [comment] 2016-07-08 08:27
@gdha, Yeah quite a lag :-)

**Comment by jsmeix** [comment] 2016-07-12 11:32
With https://github.com/rear/rear/pull/906 merged
one issue should now be fixed.

What is left in https://github.com/rear/rear/issues/849#issuecomment-227459162
is documentation what packages (modules) are required
by grub(2)-mkimage to create bootloader.efi
which is used to EFI boot from USB.

**Comment by gozora** [comment] 2016-07-12 11:50
Actually I didn't get any feedback whether **README.adoc** is right place for this information, so I just put it "on hold".

**Comment by gdha** [comment] 2016-07-12 19:42
@gozora sorry for the delay (holidays). As I have currently no better proposition I agree with **README.adoc**

**Comment by gozora** [comment] 2016-07-12 19:48
@gdha No stress! ;-) I will put that in **README.adoc** then, hopefully tomorrow.
Enjoy your free time!

**Comment by jsmeix** [comment] 2016-07-13 12:57
With https://github.com/rear/rear/pull/911
I consider this issue to be fixed.

If not one can reopen it or - perhaps even better -
create a separated new issue.

@gozora 
many thanks for your continuous valuable contribution to rear!

**Closed by jsmeix** 2016-07-13 12:57 UTC
Labels: enhancement, fixed
