### ISSUE TITLE
ReaR releases should not mention Git in version / Dev builds should mention the Git commit hash

### ISSUE THREAD

**Issue by schlomo** [rear/rear#1362] opened 2017-05-11 12:40 UTC
ATM the version string of a release (e.g. from EPEL) is `Relax-and-Recovery 2.00 / Git` which is confusing to customers who think that this is a development build from some git commit and not a real release.

ATM the version string of a dev build contains a date/time string and the date but not the commit hash.

I suggest to improve that so that we are more clear about the release/dev status of a package.

**Comment by jsmeix** [comment] 2017-05-11 13:15
I also noitced that but found no time
to investigate what the root cause is.

**Comment by gdha** [comment] 2017-05-22 15:50
@schlomo @jsmeix This will show the effective RELEASE_DATE of an official release date. I suppose this enough for v2.1?

**Comment by gdha** [comment] 2017-05-29 16:25
Moved the milestone to v2.2 - for v2.1 we did what we needed to do and we have no time for further corrections/modifications.

**Comment by gdha** [comment] 2017-07-11 06:03
I think we can close this issue

**Closed by gdha** 2017-07-11 06:03 UTC
Labels: enhancement, minor bug
