### ISSUE TITLE
error: ../../grub-core/loader/i386/efi/linux.c:158:can't allocate initrd

### ISSUE THREAD

**Issue by sathyane007** [rear/rear#3186] opened 2024-03-27 15:08 UTC
Hello ;
i have an issue when i try to use rear.iso file to recever linux REH8.7 on a dell idrac BMR.
On a topic , someone suggest to exclude from rear iso firmware in order to reduce intrd but i need also firmware updatation on image file .
is there any updation of this kind of issue please ?
Thanks for your help

**Comment by pcahyna** [comment] 2024-03-27 15:18
Hi, this was reported as #2681 . I know two solutions (besides reducing the size of the initrd):
- downgrading grub to a version between 2.02-121.el8 and grub2-1:2.02-141.el8 : https://github.com/rear/rear/issues/2681#issuecomment-1697073572
- firmware update (helped on HP hardware, don't know if it will help on Dell hardware though)

**Comment by sathyane007** [comment] 2024-03-28 12:18
Hi pcahyna , thanks for your reply 
we are in version  grub2-2.02-142.el8_7.1.x86_64
Unfortunatly , we can not downgrade to  version  2.02-121.el8 . i ask to upgrade the firmware of dell hardware in case ..
but is there an other solution please to charge rear-iso file ?
thanks

**Comment by pcahyna** [comment] 2024-03-28 12:25
What Dell hardware is it, exactly?

**Comment by sathyane007** [comment] 2024-03-29 08:53
Dell PowerEdge R750 
Bios Version 1.9.2
Integrated Dell Remote Access Controller 9........................................................................... Version 6.10.30.00(Build 29)

**Comment by sathyane007** [comment] 2024-04-03 07:31
Hello
i have tested on a cisco platform , and i have this version: grub2-efi-x64-2.02-150.el8.x86_64
And i had no problem with rear iso file to load it .

Someone has any idea  why it is not working on Dell Platform , ?

**Comment by pcahyna** [comment] 2024-04-05 10:35
@sathyane007 this GRUB problem is apparently firmware (both manufacturer and version) dependent, that's why. Have you tried updating it?

**Comment by sathyane007** [comment] 2024-04-24 07:22
HI pcahyna thanks for your reply
iDRAC Firmware Version | 6.10.30.00 which is not an old version 
do you think i need to upgrade for the latest one ?

**Comment by sathyane007** [comment] 2024-04-26 09:39
I have tested on an other platform in firmware version 7.00.30.00 , same issue ... 
i 'll try to upgrade firmware version on 7.10.30.00 which is the latest ...

**Comment by pcahyna** [comment] 2024-04-26 09:47
not sure if UEFI firmware version is the same as the iDRAC firmware version btw...

For example on my notebook, I get this in the `dmidecode` output:

```
Handle 0x0031, DMI type 0, 24 bytes
BIOS Information
        Vendor: ...
        Version: ...
        Release Date: ...
        Characteristics:
                (...)
                UEFI is supported
        BIOS Revision: 1.12
        Firmware Revision: 1.0
```

**Comment by sathyane007** [comment] 2024-04-26 13:15
i confirm it still not working in idrac firmware 7.10.30 . 
@pcahyna : here is my dmidecode on my powerEdge R750:

Handle 0x0000, DMI type 0, 26 bytes
BIOS Information
        Vendor: Dell Inc.
        Version: 1.11.2
        Release Date: 08/10/2023
        Address: 0xF0000
        Runtime Size: 64 kB
        ROM Size: 32 MB
                   UEFI is supported
        BIOS Revision: 1.11
Handle 0x0100, DMI type 1, 27 bytes
System Information
        Manufacturer: Dell Inc.
        Product Name: PowerEdge R750

I cannot see the UEFI version  or firmware revision version ?? (under Bios Revision).

**Comment by sathyane007** [comment] 2024-04-26 14:41
so it works only if i remove firmware information on that iso file (reducing it) but we have different hardware 
idreac dell firmware updated .. grub2 in version 1.50... any other think to upgrade ?

**Comment by pcahyna** [comment] 2024-05-23 17:42
@sathyane007 another idea... can you perhaps try if setting `REAR_INITRD_COMPRESSION="lzma"` produces a small enough initrd? Inspired by #3233

**Comment by sathyane007** [comment] 2024-05-27 09:29
yes indeed this option (REAR_INITRD_COMPRESSION="lzma") reduced a little the iso file (instead of 750MB , it reduce to 550M) but still have the pb :(loader/i386/efi/linux.c:158:can't allocate initrd)

**Comment by pcahyna** [comment] 2024-09-02 20:58
Hi @sathyane007 sorry for the late reply. This needs to be fixed in GRUB provided in RHEL, so if you have a RHEL support contract, please open a customer case and refer to https://issues.redhat.com/browse/RHEL-4389 . Also in the customer case mention the hardware (Dell PowerEdge R750) and BIOS version. and the initrd size that did not work (550M).

**Comment by jsmeix** [comment] 2024-11-08 15:55
Because "no news is good news" I assume this is meanwhile
somehow solved (e.g. handled via Red Hat RHEL support)
and its root cause is not in ReaR anyway.

**Closed by jsmeix** 2024-11-08 15:55 UTC
Labels: support / question, external tool, not ReaR / invalid, special hardware or VM
