### ISSUE TITLE
HP ProLiant BL460c Gen9 hangs after boot from ISO

### ISSUE THREAD

**Issue by KingDanTR** [rear/rear#848] opened 2016-05-25 07:22 UTC
* rear version 1.18
* OS version: SUSE Linux Enterprise Server 12 (x86_64) SP1
* rear configuration file:
```
BACKUP=NSR
OUTPUT=ISO
NSRSERVER=xxx
NSR_DEFAULT_POOL_NAME=xxx
NSR_RETENTION_TIME="Month"
USE_CFG2HTML=y
```

Brief description:
After booting from created ISO image I cannot login to the server, no input is possible with ILO console and the server is not reachable over the network (ping, ssh, ...)

Is the hardware type supported? 
With a HP Proliant DL 380p Gen8 the backup and recover was successful with the same ReaR configuration.

When I'm booting the HP Proliant DL 380p Gen8 server from the ISO image created with the HP ProLiant BL460c Gen9 server it hangs when I have to choose the network interface to use.

**Comment by gdha** [comment] 2016-05-30 07:28
@KingDanTR IMHO you are missing a kernel module which differs between Gen8 and Gen9. However, I cannot help you with this due to no HW to test on.

**Comment by jsmeix** [comment] 2016-09-21 13:40
I think the issue is sufficientliy answered (as far as possible
withou having that hardware available) => closing it.
If needed it can be reopened.

**Closed by jsmeix** 2016-09-21 13:40 UTC
Labels: support
