### ISSUE TITLE
Disklayout have collecting problem

### ISSUE THREAD

**Issue by Kolesar** [rear/rear#1491] opened 2017-09-13 13:54 UTC
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): **Relax-and-Recover 2.2 / 2017-07-20**
* OS version (cat /etc/rear/os.conf or lsb_release -a): **CentOS Linux release 7.3.1611 (Core)**
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf): **empty**
* Are you using legacy BIOS or UEFI boot? **UEFI**
* Brief description of the issue:
On each run `rear -v mkrescue` or `rear -v savelayout` `/var/lib/rear/layout/disklayout.conf` have different number of partitions. I have found where is problem in code, but I cannot understand why it happened.
Command `declare -a sysfs_paths=(/sys/block/$sysfs_name/$sysfs_name*)` every time return different output, so this is really strange
* Work-around, if any:
Unfortunately at this moment I do not have work-around. If you have any idea I can try on my hardware and hopefully fix this issue.

**Comment by jsmeix** [comment] 2017-09-19 14:44
@Kolesar 
I am not at all an expert in this area but in general I assume
when running a particular command on comandline
produces varying/unstable/unreliable outout
the root cause is likely not inside ReaR but in that command
or even more likely somewhere in the environment
(in this case kernel/udev/whatever...).

Does it perhaps help to add an artificial 'sleep' e.g. like
<pre>
sleep 30
</pre>
in the script before that command is run in the hope
that then what there is in /sys/block/... got stabilized
so that the command output is also stable and reliable?

**Comment by jsmeix** [comment] 2017-09-21 08:16
@Kolesar 
you wrote "any idea I can try on my hardware"
but nobody can have such an idea because
nobody can know what your hardware is
because you did not tell that.

Is this issue here perhaps somehow related to you
https://github.com/rear/rear/issues/1460
which is about "Raid Level: container"
where you told "I have RAID 1 on my environment"
but not what your environment actually is.

**Comment by gdha** [comment] 2017-10-27 15:33
@Kolesar Can you share an example of the differences please? What kind of disk devices do you have?

**Comment by gdha** [comment] 2017-11-17 13:58
@Kolesar As no evidence was delivered there is nothing we can do I'm afraid - will close it - you may re-open it when sufficient useful information is provided

**Closed by gdha** 2017-11-17 13:58 UTC
Labels: not ReaR / invalid, support/question, waiting for info
