### ISSUE TITLE
PPC64be - Cannot find required programs: efibootmgr

### ISSUE THREAD

**Issue by viper1986** [rear/rear#1239] opened 2017-03-14 13:18 UTC
#### Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue (quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): Relax-and-Recover 2.00 / Git
* OS version (cat /etc/rear/os.conf or lsb_release -a):
````
LSB Version:    core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-ppc64:core-3.2-ppc64:core-4.0-ppc64:desktop-4.0-noarch:desktop-4.0-ppc32:desktop-4.0-ppc64:graphics-2.0-noarch:graphics-2.0-ppc32:graphics-2.0-ppc64:graphics-3.2-noarch:graphics-3.2-ppc32:graphics-3.2-ppc64:graphics-4.0-noarch:graphics-4.0-ppc32:graphics-4.0-ppc64
Distributor ID: SUSE LINUX
Description:    SUSE Linux Enterprise Server 11 (ppc64)
Release:        11
Codename:       n/a
````

cat /etc/*-release
````
LSB_VERSION="core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-ppc64:core-3.2-ppc64:core-4.0-ppc64"
NAME="SLES"
VERSION="11.4"
VERSION_ID="11.4"
PRETTY_NAME="SUSE Linux Enterprise Server 11 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:11:4"
SUSE Linux Enterprise Server 11 (ppc64)
VERSION = 11
PATCHLEVEL = 4
````
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
````
BACKUP=NSR
OUTPUT=ISO
OUTPUT_URL=nfs://t301-dd10.itebck.local/data/col1/rear
NSRSERVER=c301bcksrv
POOLNAME=ddos
RETENTION_TIME=Month
USE_CFG2HTML=y
````
* Are you using legacy BIOS or UEFI boot?
* Brief description of the issue:
I want to configure REAR on my ppc64 system, but I have a problem with creating iso and properly configuration.

Logs:
````
rear -v mkbackup
2017-03-14 14:05:38 Relax-and-Recover 2.00 / Git
2017-03-14 14:05:38 Command line options: /usr/sbin/rear -v mkbackup
2017-03-14 14:05:38 Using log file: /var/log/rear/rear-iterelax01.log
2017-03-14 14:05:38 Including conf/Linux-ppc64.conf
2017-03-14 14:05:38 Including conf/GNU/Linux.conf
2017-03-14 14:05:38 Including conf/SUSE_LINUX.conf
2017-03-14 14:05:38 Including /etc/rear/site.conf
2017-03-14 14:05:38 Including /etc/rear/local.conf
2017-03-14 14:05:38 Running 'init' stage
2017-03-14 14:05:38 Including init/default/010_set_drlm_env.sh
2017-03-14 14:05:38 Including init/default/030_update_recovery_system.sh
2017-03-14 14:05:39 Including init/default/050_check_rear_recover_mode.sh
2017-03-14 14:05:39 Finished running 'init' stage in 0 seconds
2017-03-14 14:05:39 Using build area '/tmp/rear.bftpfMPLH2xXZDK'
mkdir: created directory `/tmp/rear.bftpfMPLH2xXZDK/rootfs'
mkdir: created directory `/tmp/rear.bftpfMPLH2xXZDK/tmp'
2017-03-14 14:05:39 Running mkbackup workflow
2017-03-14 14:05:39 Running 'prep' stage
2017-03-14 14:05:39 Including prep/default/005_remove_workflow_conf.sh
mkdir: created directory `/tmp/rear.bftpfMPLH2xXZDK/rootfs/etc'
mkdir: created directory `/tmp/rear.bftpfMPLH2xXZDK/rootfs/etc/rear'
2017-03-14 14:05:39 Including prep/default/020_translate_url.sh
2017-03-14 14:05:39 Including prep/default/030_translate_tape.sh
2017-03-14 14:05:39 Including prep/default/040_check_output_scheme.sh
2017-03-14 14:05:39 Including prep/default/050_check_keep_old_output_copy_var.sh
2017-03-14 14:05:39 Including prep/default/100_init_workflow_conf.sh
2017-03-14 14:05:39 Including prep/GNU/Linux/200_include_getty.sh
2017-03-14 14:05:39 Including prep/GNU/Linux/200_include_serial_console.sh
2017-03-14 14:05:39 Including prep/GNU/Linux/210_include_dhclient.sh
2017-03-14 14:05:39 Including prep/GNU/Linux/220_include_lvm_tools.sh
2017-03-14 14:05:39 Device mapper found enabled. Including LVM tools.
2017-03-14 14:05:39 Including prep/GNU/Linux/230_include_md_tools.sh
2017-03-14 14:05:39 Including prep/GNU/Linux/240_include_multipath_tools.sh
2017-03-14 14:05:39 Including prep/GNU/Linux/280_include_systemd.sh
2017-03-14 14:05:39 Including prep/GNU/Linux/280_include_vmware_tools.sh
2017-03-14 14:05:39 Including prep/GNU/Linux/290_include_drbd.sh
2017-03-14 14:05:39 Including prep/GNU/Linux/300_check_backup_and_output_url.sh
2017-03-14 14:05:39 Including prep/ISO/default/300_check_iso_dir.sh
2017-03-14 14:05:39 Including prep/GNU/Linux/300_include_grub_tools.sh
2017-03-14 14:05:39 Including prep/GNU/Linux/310_include_cap_utils.sh
2017-03-14 14:05:39 Including prep/default/310_include_uefi_tools.sh
2017-03-14 14:05:39 Including prep/ISO/default/320_check_cdrom_size.sh
2017-03-14 14:05:39 ISO Directory '/var/lib/rear/output' [/dev/mapper/OS-var] has 3388 MB free space
2017-03-14 14:05:39 Including prep/default/320_include_uefi_env.sh
2017-03-14 14:05:39 Including prep/ISO/GNU/Linux/320_verify_mkisofs.sh
2017-03-14 14:05:39 Using '/usr/bin/mkisofs' to create ISO images
2017-03-14 14:05:39 Including prep/ISO/GNU/Linux/340_add_isofs_module.sh
2017-03-14 14:05:39 Including prep/NSR/default/400_prep_nsr.sh
2017-03-14 14:05:39 Including prep/default/400_save_mountpoint_details.sh
2017-03-14 14:05:39 Including prep/NSR/default/450_check_nsr_client.sh
2017-03-14 14:05:39 Backup method is NetWorker (NSR): check nsrexecd
2017-03-14 14:05:39 Including prep/default/500_guess_bootloader.sh
2017-03-14 14:05:39 Including prep/default/950_check_missing_programs.sh
2017-03-14 14:05:39 ERROR: Cannot find required programs: efibootmgr
==== Stack trace ====
Trace 0: /usr/sbin/rear:504 main
Trace 1: /usr/share/rear/lib/mkbackup-workflow.sh:9 WORKFLOW_mkbackup
Trace 2: /usr/share/rear/lib/framework-functions.sh:85 SourceStage
Trace 3: /usr/share/rear/lib/framework-functions.sh:45 Source
Trace 4: /usr/share/rear/prep/default/950_check_missing_programs.sh:15 source
Message: Cannot find required programs: efibootmgr
== End stack trace ==
2017-03-14 14:05:39 Running exit tasks.
2017-03-14 14:05:39 Finished in 1 seconds
2017-03-14 14:05:39 Removing build area /tmp/rear.bftpfMPLH2xXZDK
removed directory: `/tmp/rear.bftpfMPLH2xXZDK'
2017-03-14 14:05:39 End of program reached
````
I use **yaboot** and **lilo** bootloader.
````
hostname:/usr/share/rear # ls -l /boot
total 39172
-rw-r--r-- 1 root root     1236 Jan 15  2016 boot.readme
-rw-r--r-- 1 root root   112426 Jul 18  2016 config-3.0.101-80-ppc64
lrwxrwxrwx 1 root root       23 Aug 22  2016 initrd -> initrd-3.0.101-80-ppc64
-rw-r--r-- 1 root root  6874584 Aug 22  2016 initrd-3.0.101-80-ppc64
-rw------- 1 root root  8960284 Aug 22  2016 initrd-3.0.101-80-ppc64-kdump
-rw-r--r-- 1 root root   198238 Jul 18  2016 symvers-3.0.101-80-ppc64.gz
-rw-r--r-- 1 root root  3004002 Jul 18  2016 System.map-3.0.101-80-ppc64
lrwxrwxrwx 1 root root       24 Aug 22  2016 vmlinux -> vmlinux-3.0.101-80-ppc64
-rw-r--r-- 1 root root 20880080 Jul 18  2016 vmlinux-3.0.101-80-ppc64
````

**Comment by gdha** [comment] 2017-03-14 17:52
````
ERROR: Cannot find required programs: dosfsck efibootmgr
````
Found  the root cause in issue #1225

**Comment by gdha** [comment] 2017-03-14 18:21
@viper1986 Try tomorrow again with the latest snapshot of rear (with above fix included)

**Comment by viper1986** [comment] 2017-03-15 08:34
Hello,
Thank you for quick response. I try today and it works! 

But I have little problem with NFS. I want to change some NFS option of mount. Now I got 
mount  -t nfs -o rw,noatime 169.254.252.10:/data/col1/rear /tmp/rear.VZ0sSt5OmzzRCw2/outputfs
and I want to change -o rw,noatime to:
-o hard,intr,nolock,nfsvers=3,tcp,timeo=1200,rsize=1048600,wsize=1048600,bg

In which file I can find configuration for this? Or maybe this is system default?

**Comment by jsmeix** [comment] 2017-03-15 09:14
The initial issue here is fixed with
https://github.com/rear/rear/commit/6c477d4e99edeb21a1a8c7649c24b2a56de535a7

@viper1986 
I did not check the details of this issue here
but in general for NFS mount options see
the usr/share/rear/conf/examples/SLE1*
example config files - therein note the
BACKUP_OPTIONS variable

In general regarding third party backup tools (like BACKUP=NSR)
see the section "Relax-and-Recover versus backup and restore" in
https://en.opensuse.org/SDB:Disaster_Recovery

In general there is nothing at all what I could do in case of issues
with third-party backup tools or any other third-party software
because I do not have such software on my test systems
so that I can neither test nor reproduce anything, cf.
https://github.com/rear/rear/issues/823

**Closed by jsmeix** 2017-03-15 09:14 UTC
Labels: bug, fixed/solved/done
