### ISSUE TITLE
Netbackup agents not automatically started

### ISSUE THREAD

**Issue by pdanek** [rear/rear#1523] opened 2017-10-03 17:44 UTC
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): 2.00
* OS version (cat /etc/rear/os.conf or lsb_release -a): RHEL 7.3
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
OUTPUT=ISO
BACKUP=NBU
KERNEL_CMDLINE="$KERNEL_CMDLINE net.ifnames=0"
ONLY_INCLUDE_VG=( "rootvg" )
SSH_ROOT_PASSWORD='<confidential>'

* Are you using legacy BIOS or UEFI boot? BIOS
* Brief description of the issue: Netbackup standalone agents vnetd and bpcd are not automatically started by rear recover command.
I have noticed there is prep script 450_prepare_netbackup.sh, but it's not automatically run by rear recover.
Is it by design? Or could you please advise how to make it start automatically?

* Work-around, if any: Start agents manually with /etc/scripts/system-setup.d/90-netbackup.sh before running rear recover
[rear-is-rear1t.log](https://github.com/rear/rear/files/1353308/rear-is-rear1t.log)

**Comment by gdha** [comment] 2017-10-04 15:12
@pdanek Have look at `conf/default.conf` file entry:
````
grep COPY_AS_IS_NBU conf/default.conf 
COPY_AS_IS_NBU=( /usr/openv/bin/vnetd /usr/openv/bin/vopied /usr/openv/lib /usr/openv/netbackup /usr/openv/var/auth/[mn]*.txt )
````
Is here something missing from the point of view of NBU?
Also the script you should inspect is `rescue/NBU/default/450_prepare_xinetd.sh` which starts the NBU processes. Perhaps, it needs to be updated for RHEL 7.3 - systemd scripts maybe??

**Comment by pdanek** [comment] 2017-10-24 09:49
COPY_AS_IS_NBU files:
```
RESCUE is-rear1t:~ # ls -ld /usr/openv/bin/vnetd
ls: cannot access /usr/openv/bin/vnetd: No such file or directory
RESCUE is-rear1t:~ # ls -ld /usr/openv/bin/vopied
ls: cannot access /usr/openv/bin/vopied: No such file or directory
RESCUE is-rear1t:~ # ls -ld /usr/openv/lib
drwxr-xr-x 7 root 1 0 Oct 14 12:14 /usr/openv/lib
RESCUE is-rear1t:~ # ls -ld /usr/openv/netbackup
drwxr-xr-x 11 root 1 0 Oct 14 12:15 /usr/openv/netbackup
RESCUE is-rear1t:~ # ls -ld /usr/openv/var/auth/[mn]*.txt
ls: cannot access /usr/openv/var/auth/[mn]*.txt: No such file or directory
```

Inspection of script:
```
if [ ! -f /etc/xinetd.d/vnetd ]; then
        /usr/openv/netbackup/bin/vnetd -standalone
fi
if [ ! -f /etc/xinetd.d/bpcd ]; then
        /usr/openv/netbackup/bin/bpcd -standalone
fi
```

Executing the part of script manually:
```
RESCUE is-rear1t:~ # ls -ld /etc/xinetd.d/vnetd
ls: cannot access /etc/xinetd.d/vnetd: No such file or directory
RESCUE is-rear1t:~ # ls -ld /etc/xinetd.d/bpcd
ls: cannot access /etc/xinetd.d/bpcd: No such file or directory
RESCUE is-rear1t:~ # /usr/openv/netbackup/bin/vnetd -standalone
RESCUE is-rear1t:~ # /usr/openv/netbackup/bin/bpcd -standalone
RESCUE is-rear1t:~ # ps -ef|grep -i netb
root       453     1  0 09:47 ?        00:00:00 /usr/openv/netbackup/bin/vnetd -standalone
root       457     1  0 09:47 ?        00:00:00 /usr/openv/netbackup/bin/bpcd -standalone
```

So why doesn't it start automatically? :-/

**Comment by gdha** [comment] 2017-10-24 10:14
@pdanek because RHEL 7.3 uses systemd scripts to launch these daemons and not xinetd.d scripts anymore. It should be updated from the ReaR side.
However, NBU is an external backup program for which we do **not write for free** updates within ReaR. It can be done as it is not complicated to do so.

**Comment by gdha** [comment] 2017-10-26 14:56
@pdanek  @rmetrich The pull request has been merged. Please provide feedback if it works fine or not?
Thanks for the effort already.

**Comment by gdha** [comment] 2017-11-28 14:50
We will close this issue as no responsive is _good news_, right?

**Comment by rmetrich** [comment] 2017-11-28 15:42
No, no, please reopen, I'm finishing the work (there is some issue to deal with, unrelated to NetBackup but showing up because of it). I'm currently waiting for feedback from @pdanek

**Comment by rmetrich** [comment] 2017-11-28 15:43
@jsmeix @gdha see above

**Comment by gdha** [comment] 2017-11-28 15:52
As requested by @rmetrich we re-open the issue, but is the new issue related to the PR you made? Or, is it something new due to the PR you introduced?

**Comment by rmetrich** [comment] 2017-11-28 15:54
The issue is within systemd service spawning the scripts (including netbackup).
With actual netbackup code, it still doesn't work because of that.
So maybe opening a new issue is OK instead

**Comment by gdha** [comment] 2017-11-28 15:57
@rmetrich Indeed it seems a new issue related to this one. Create a separate issue please.
I assume the new netbackup script you made works from the command line? If that is the case, then it is related to systemd only and a new systemd script should be written (and placed in the skel directory structure perhaps).

**Comment by rmetrich** [comment] 2017-11-28 15:58
won't be needed.
Please close again, then. I hope to submit a PR soon (waiting for @pdanek feedback).

**Closed** 2017-11-28 16:03 UTC
Labels: external tool, fixed/solved/done, support/question

**Comment by pcahyna** [comment] 2018-06-26 15:46
@rmetrich was it #1609 & #1610 or something else?
