### ISSUE TITLE
Issues with "rear recover" - network interfaces

### ISSUE THREAD

**Issue by perlvan** [rear/rear#1890] opened 2018-08-05 07:43 UTC
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):

Relax-and Recover 2.4 / 2018-06-21
Relax-and Recover 2.3 / 2017-12-20
Relax-and Recover 2.2 / 2017-07-20
Relax-and Recover 2.1 / 2017-06-07

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
Oracle Linux Server 6.9
* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

KERNEL_FILE="/boot/vmlinuz-4.1.12-94.7.8.el6uek.x86_64"
BACKUP=NETFS
OUTPUT=PXE

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
BareMetal

* System architecture (x86 compatible or PPC64/PPC64LE or what excat ARM device):

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
GRUB

* Description of the issue (ideally so that others can reproduce it):
None of network interface/s are not coming up in Rear Rescue prompt except loopback (lo)interface.
Rear Recovery stuck while loading modules... 
60-network-devices.sh script output will be as below..
Cannot find device "eth0"
Cannot find device "eth1"
:
/bin/modprobe: line 17: /sbin/modprobe.ksplice-orig: No such file or directory
/bin/modprobe: line 17: exec: /sbin/modprobe.ksplice-orig: cannot execute: No such file or directory
Cannot find device "bondeth0"
Master 'bondeth0': Error: handshake with driver failed. Aborting

* Work-around, if any: 
Still no solution/fix found

**Comment by jsmeix** [comment] 2018-08-06 10:10
I don't use Oracle Linux Server so that I cannot reproduce anything here
but it seems the `/sbin/modprobe.ksplice-orig: No such file or directory`
error is exactly the same as in
https://github.com/rear/rear/issues/605
which should have been fixed since a long time via
https://github.com/rear/rear/commit/f17948ff3760df36bea53a828274e2726e514c8b
and we still have /sbin/modprobe.ksplice-orig in COPY_AS_IS
and oinstall in CLONE_GROUPS in our ReaR GitHub master code in
https://github.com/rear/rear/blob/master/usr/share/rear/conf/GNU/Linux.conf

**Comment by gdha** [comment] 2018-08-06 16:42
@perlvan check the `dmesg` output after booting up with the rescue image for information about LAN interfaces, and also try `ip a` command to see what you really have.
Or, try to add the following line to the `local.conf` file:
````
KERNEL_CMDLINE="$KERNEL_CMDLINE net.ifnames=0"
````

**Comment by perlvan** [comment] 2018-08-07 01:42
I tried adding modprobe.ksplice-orig to COPY_AS_IS.. Now i can see the interfaces came up and able to ping the tftp server. But when i try to run the "rear recover" it is failing  with below errors...

RESCUE :/# rear recover
Relax-and-Recover 2.3 / 2017-12-20
Using log file: /vra/log/rear/rear-<>.log
Running workflow recover within the Rear rescue/recovery system
Starting required daemons for NFS: RPC portmapper (portmap or rpcbind) and rpc.statd if available.
ERROR: Starting RPC portmapper 'rpcbind' failed.
Aborting due to an error, check /var/log/rear/rear-<>.log for details
You should also rm -Rf .tmp/rear.WOOXInWLu1V9gQ
Terminated
RESCUE :/#

Error log and Stack trace output:
====================
/usr/share/rear/lib/_input-output-functions.sh: line 208: type: portmap: not found
2018-08-07 01:29:58.119421836 ERROR: Starting RPC portmapper 'rpcbind' failed.

/usr/share/rear/verify/NETFS/default/050_start_required_nfs_daemons.sh: 
45 source
Message: Starting RPC portmapper 'rpcbind' failed.

**Comment by jsmeix** [comment] 2018-08-07 09:08
In current ReaR GitHub master code line 208 of lib/_input-output-functions.sh is
<pre>
# the original STDIN STDOUT and STDERR file descriptors are saved as fd6 fd7 and fd8
</pre>
so line numbers of older versions of scripts don't help us much.

@perlvan 
could you try out using our current ReaR GitHub master code
so that you and we use at least the same code
which makes debugging easier for us.

To use our current ReaR upstream GitHub master code do the following:

Basically "git clone" it into a separated directory and then
configure and run ReaR from within that directory like:
<pre>
# git clone https://github.com/rear/rear.git

# mv rear rear.github.master

# cd rear.github.master

# vi etc/rear/local.conf

# usr/sbin/rear -D mkbackup
</pre>
Note the relative paths "etc/rear/" and "usr/sbin/".

I recommend to use our current ReaR upstream GitHub master code
because that is the only place where we fix bugs - i.e. bugs in older
ReaR versions are not fixed by us (i.e. by ReaR upstream).

**Comment by perlvan** [comment] 2018-08-09 05:14
Apologies my host which i'm testing is behind firewall and can't download or upload the packages from Git.. Between I'm able to copy System files and backup files ( backup.tar.gz)  file directly to /mnt/local with the network interafaces up.. 
It's just that "rear recover" doesn't work, which complains about "rpcbind" and portmap..

So, here are the steps i followed..
I have mounted nfs manually and copied the backup and system files to /mnt/local..
Now how to make the system bootup with the restored files in /mnt/local..?

**Comment by gdha** [comment] 2018-08-17 13:09
@perlvan the `rpcbind` is missing because you used `OUTPUT=PXE`
You might consider to add the following lines to `/etc/rear/local.conf`:
````
PROGS=( "${PROGS[@]}" showmount mount.nfs umount.nfs )
MODULES=( "${MODULES[@]}" nfs )
PRE_RECOVERY_SCRIPT="systemctl start rpcbind.target || rpcbind &"
````

**Comment by gdha** [comment] 2018-09-24 15:12
@perlvan is your question sufficient answered?

**Comment by perlvan** [comment] 2018-09-25 23:20
Yes, it addressed my issue. Thank you.

**Closed** 2018-09-26 09:12 UTC
Labels: fixed/solved/done, support/question
