### ISSUE TITLE
Rear Disk Layout script failing On Centos7

### ISSUE THREAD

**Issue by cksmith3** [rear/rear#1775] opened 2018-04-13 12:07 UTC
* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.3 / 2017-12-20

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
Red Hat Enterprise Linux Server release 7.3 (Maipo)
OS_VENDOR=Fedora
OS_VERSION=28

* ReaR configuration files ("cat /etc/rear/site.conf" or "cat /etc/rear/local.conf"):

OUTPUT=ISO
(the only line change/ added to the conf file)

* System architecture (x86 compatible or POWER and/or what kind of virtual machine):
x86
Dl380 hp server 

* Are you using BIOS or UEFI or another way to boot?
UEFI 

* Brief description of the issue:
The disk set up script is failing. The error after reading the log is Error: Expecting a file system type. The drive is one logical drive made by combining 3 physical drives on a server.  I have attached the log file from the error. 
[df.txt](https://github.com/rear/rear/files/1907213/df.txt)
[rear-localhost.log](https://github.com/rear/rear/files/1907214/rear-localhost.log)

* Work-around, if any:
None found yet

**Comment by gozora** [comment] 2018-04-13 12:27
Check my https://github.com/rear/rear/issues/1770#issuecomment-379541958, for solution, tt is same problem as yours.

V.

**Comment by jsmeix** [comment] 2018-04-13 12:29
In your rear-localhost.log there is
<pre>
2018-04-13 00:34:42.141982548 Start system layout restoration.
...
+++ parted -s /dev/sda mkpart 'EFI System Partition' 786432B 209977343B
parted: invalid token: System
Error: Expecting a file system type.
</pre>
which makes this issue a duplicate of
https://github.com/rear/rear/issues/1770
therein see in particular
https://github.com/rear/rear/issues/1770#issuecomment-379541958

Regarding "downloading latest ReaR upstream code".

To use our current ReaR upstream GitHub master code
do the following:

Basically "git clone" it into a separated directory and then
configure and run ReaR from within that directory like:
<pre>
# git clone https://github.com/rear/rear.git

# mv rear rear.github.master

# cd rear.github.master

# vi etc/rear/local.conf

# usr/sbin/rear -D mkbackup
</pre>
Note the relative paths "etc/rear/" and "usr/sbin/".

I recommend to use our current ReaR upstream GitHub master code
because that is the only place where we fix bugs - i.e. bugs in older
ReaR versions are not fixed by us (i.e. by ReaR upstream).
Bugs in older ReaR versions that got fixed in current ReaR upstream
GitHub master code might be fixed (if the fix can be backported)
by the Linux distributor wherefrom you got your older ReaR version.

**Closed by jsmeix** 2018-04-13 12:29 UTC
Labels: fixed/solved/done, support/question

**Comment by jsmeix** [comment] 2018-04-13 12:31
@gozora 
o.k. o.k. you won but it's not a fair race
when you write so little text ;-)
Have a nice weekend!

**Comment by jsmeix** [comment] 2018-04-13 12:32
And even with a typo!

**Comment by cksmith3** [comment] 2018-04-13 12:33
thank you for the quick and thorough answers. 
and LOL the race to answer

**Comment by gozora** [comment] 2018-04-13 12:43
@jsmeix 
:-) what typo ?

> when you write so little text ;-)

As mister Da Vinci said "Simplicity is the ultimate sophistication" ;-)

@cksmith3 
> thank you for the quick and thorough answers.
> and LOL the race to answer

You are welcome, we try to do our best ;-).

V.

**Comment by jsmeix** [comment] 2018-04-13 12:53
or https://tools.ietf.org/html/rfc1925 item (12)
<pre>
... perfection has been reached
not when there is nothing left to add,
but when there is nothing left to take away
</pre>
so that ultimate perfection has been reached
when the empty set is reached ;-)
https://en.wikipedia.org/wiki/Empty_set

**Comment by jsmeix** [comment] 2018-04-14 19:04
True! ;-)

"si tacuisses, philosophus mansisses"
https://en.wikipedia.org/wiki/List_of_Latin_phrases_(S)
