### ISSUE TITLE
Default ISO_VOLID="RELAXRECOVER" too long for a FAT32 volume label

### ISSUE THREAD

**Issue by MarcoS80** [rear/rear#1565] opened 2017-11-06 09:29 UTC
Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

rear version (/usr/sbin/rear -V): Relax-and-Recover 2.2-git.0.b7927e5.unknown.changed / 2017-10-31

OS version (cat /etc/rear/os.conf or lsb_release -a): Ubuntu/17.04/i386

rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL=iso:///backup
ISO_VOLID="REARISO"
OUTPUT_URL=file:///tmp
MODULES=( 'all_modules' )

Are you using legacy BIOS or UEFI boot? UEFI

* Brief description of the issue:
If the output of choice is an iso image, and the iso image is used to create a FAT32 bootable usb memory stick (I used UltraIso in Windows), the Volume ID is truncated, preventing the device from being mounted correctly  
* Work-around, if any:
ISO_VOLID can be used as a work-around, although a shorter default VOLID would be more convenient.

**Comment by gozora** [comment] 2017-11-06 16:23
@MarcoS80 I'm not sure what is the reported issue here ...
Would you like us to change configuration directive _ISO_VOLID_ to _VOLID_ ?
If so, I'd disagree as _VOLID_ is currently correctly bonded to ISO and avoiding _ISO_ prefix could cause possible namespace conflicts in the future, so I'd prefer letting it be as it is ...

V.

**Comment by MarcoS80** [comment] 2017-11-06 16:55
Apologies! 
What I mean is that at line 301 in default.conf the assignment: 
ISO_VOLID="RELAXRECOVER"
could be replaced by an assignment such as:
ISO_VOLID="REARRECOV"
or something like that.
It is not really a "bug" but it may force the user to explicitly assign the ISO_VOLID variable, if the ISO image is to be used to create a bootable memory stick. 

Simply put, it seems that RELAXRECOVER is a bit too long to fit a FAT32 volume label. 
AFAIK, many (MS-Windows) applications, that are used to create EFI bootable memory sticks, do not bother to create different partitions. The just create a single FAT32 partition and put everything in it.
In my case (at least),  the resulting FAT32 volume has been truncated as RELAXRECOVE, with the last R left out, thus during the restoration process, the script was unable to mount the memory stick.

**Comment by gozora** [comment] 2017-11-06 17:12
In general I don't care what Windows programs do, as putting it very politely,  M$ Windows is IMHO quite an egoistic platform ;-).
On the other hand if we are dealing here with FAT, iso9660 or maybe other not so robust filesystems it might give a sense to keep labels 8 characters long, so something like REAR_ISO (REARISO) could be more appropriate as the default.

@schlomo, @gdha, @jsmeix, @schabrolles any ideas here?

V.

**Comment by jsmeix** [comment] 2017-11-07 11:04
In practice we cannot change such default settings
because probably zillions of ReaR users use the default
for their existing ISOs and if we changed the default
their existing ISOs (that are labelled "RELAXRECOVER")
would no longer match what there is expected/used in ReaR
so that regressions happen for "probably zillions of ReaR users".

But what I can do is to add an explanatory comment
to default.conf that describes when that default value
must be adapted by the user according to his particular
environment restrictions.

**Comment by jsmeix** [comment] 2017-11-08 12:16
With https://github.com/rear/rear/pull/1568 merged
I consider this issue to be fixed as good as possible in practice.

**Closed by jsmeix** 2017-11-08 12:16 UTC
Labels: discuss/RFC, documentation, enhancement

**Comment by jsmeix** [comment] 2020-07-15 13:07
Regarding "we cannot change such default settings"
https://github.com/rear/rear/issues/1565#issuecomment-342449263

Perhaps actually we can change this specific default setting, see
https://github.com/rear/rear/pull/2457#issuecomment-658752233

I would appreciate feedback what you think about
https://github.com/rear/rear/pull/2457

**Comment by jsmeix** [comment] 2020-07-20 14:33
With https://github.com/rear/rear/pull/2457 merged
this issue should now be actually fixed.
