### ISSUE TITLE
NBU libs in /usr/openv/netbackup/sec/at/lib not included

### ISSUE THREAD

**Issue by ofalk** [rear/rear#2105] opened 2019-04-02 09:28 UTC
* ReaR version ("/usr/sbin/rear -V"): 2.4

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"): RHEL7.6

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):

```
/etc/rear/os.conf:
OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=7

/etc/rear/local.conf:
OUTPUT=ISO
OUTPUT_URL=file:///var/lib/rear/output/
BACKUP=NBU
COPY_AS_IS_EXCLUDE_NBU=( "/usr/openv/netbackup/logs/*" "/usr/openv/netbackup/bin/bpjava*" /usr/openv/netbackup/bin/xbp /usr/openv/netbackup/bin/private /usr/openv/lib/java /usr/openv/lib/shared/vddk /usr/openv/netbackup/baremetal )
export TMPDIR=/var/tmp
```

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR): n/a

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device): x86_64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): n/a

* Storage (lokal disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe): n/a (I guess you want this template to read 'local disk', not 'lokal disk' :-))

* Description of the issue (ideally so that others can reproduce it):
While running `rear mkrescue -v`, it reports the following
```
<snip>
There are binaries or libraries in the ReaR recovery system that need additional libraries
/usr/openv/lib/plugins/libauthpam_t.so requires additional libraries
        libvrtsat_t.so => not found
ReaR recovery system in '/var/tmp/rear.NMVYmoi2gx7hvX0/rootfs' needs additional libraries, check /var/log/rear/rear-hostname.log for details
</snip>
```

* Workaround, if any:

Currently we're checking if setting `NBU_LD_LIBRARY_PATH` to the following will solve the issue:
```
NBU_LD_LIBRARY_PATH="/usr/openv/lib:/usr/openv/netbackup/sec/at/lib/"
```

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files): n/a

**Comment by jsmeix** [comment] 2019-04-02 13:59
I do not use NBU (Symantec/Veritas NetBackup)
because I do not have any kind of proprietary software
like third-party backup tools.

Perhaps
https://github.com/rear/rear/issues/1907#issuecomment-422281884
could help here as a workaround?

Perhaps this issue here has the same root cause as
https://github.com/rear/rear/issues/1974
that is fixed via
https://github.com/rear/rear/pull/1980

How to try out our current ReaR GitHub master code
where https://github.com/rear/rear/pull/1980 is merged:

Basically "git clone" our current ReaR upstream GitHub master code
into a separated directory and then configure and run ReaR
from within that directory like:
```
# git clone https://github.com/rear/rear.git

# mv rear rear.github.master

# cd rear.github.master

# vi etc/rear/local.conf

# usr/sbin/rear -D mkbackup
```
Note the relative paths "etc/rear/" and "usr/sbin/".

**Comment by ofalk** [comment] 2019-04-15 08:52
Hi!
Sorry for not getting back to you earlier.
My customer reported that adding the following to the configuration fixed the situation.

    NBU_LD_LIBRARY_PATH="/usr/openv/lib:/usr/openv/netbackup/sec/at/lib/"

Maybe you can integrate this?! Or shall I provide the merge request?

**Comment by jsmeix** [comment] 2019-04-15 09:52
@rmetrich 
I dared to assign this issue to you because
you had worked on https://github.com/rear/rear/issues/1974

https://github.com/rear/rear/issues/2105#issuecomment-483165617
is about to change default.conf
from
```
NBU_LD_LIBRARY_PATH="/usr/openv/lib"
```
to
```
NBU_LD_LIBRARY_PATH="/usr/openv/lib:/usr/openv/netbackup/sec/at/lib/"
```

The question (that I cannot answer) is whether or not
adding `/usr/openv/netbackup/sec/at/lib/` to NBU_LD_LIBRARY_PATH
by default could have unwanted side-effects (a.k.a. regressions) elsewhere.

**Comment by ofalk** [comment] 2019-04-15 10:02
@jsmeix Thanks for pulling in the right person.

**Comment by rmetrich** [comment] 2019-04-15 18:01
I do not see any issue with this change.

Renaud.

Out of the office / Sent from my phone.

Le lun. 15 avr. 2019 11:52, Johannes Meixner <notifications@github.com> a
écrit :

**Comment by ofalk** [comment] 2019-04-17 08:58
Created PR for this. Let me know if you need anything additionally changed/done, etc.

**Comment by jsmeix** [comment] 2019-04-17 10:46
With https://github.com/rear/rear/pull/2122 merged
I consider this issue to be fixed.

@ofalk 
thank you for your pull request with the fix!

**Closed by jsmeix** 2019-04-17 10:46 UTC
Labels: enhancement, external tool, fixed / solved / done, minor bug, support / question

**Comment by jsmeix** [comment] 2019-04-17 10:51
Via
https://github.com/rear/rear/commit/2377d694d7a8f2fc4232dbfa539006a499ea9cbb
I added a comment to default.conf that tells why /usr/openv/netbackup/sec/at/lib/
is needed in NBU_LD_LIBRARY_PATH

**Comment by ofalk** [comment] 2019-04-17 11:58
Awesome - thanks for the prompt replies and merge!
@jsmeix No problem - that was low hanging fruit!

**Comment by pcahyna** [comment] 2022-07-15 15:11
@ofalk do you know if there was there any reason to add the trailing slash? (Other entries do not have it, so I would prefer to be consistent.)

**Comment by pcahyna** [comment] 2022-07-25 09:47
@ofalk thanks, I have another customer who tested it with the slash removed, so I will submit a PR to remove it for consistency.

**Comment by ofalk** [comment] 2022-07-25 09:54
@pcahyna Sure!!
