### ISSUE TITLE
ReaR within SLES still lower than v2.0

### ISSUE THREAD

**Issue by gdha** [rear/rear#1506] opened 2017-09-20 09:55 UTC
According https://en.opensuse.org/SDB:Disaster_Recovery#rear_.2F_rear116_.2F_rear1172a_.2F_rear118a SLES 11/12 is still using rear-1.18 with features of rear-19 included (at least some new features).
Is it not time that rear-2.2 gets integrated into SLES? I thinking about the renumbering of the scripts for example.
It would be nice that all major Linux vendors are at least on version 2. RedHat released rear-2.0 with RHEL 7.4.

**Comment by jsmeix** [comment] 2017-09-20 10:28
In general in SLES we do not do version upgrades
unless that is really required.

Because we like to provide better support for POWER architecture
a ReaR version upgrade to the upcoming 2.3 is planned for SLES12
so that in particular our SLES12 customers on POWER architecture
could enjoy all those fixes and enhancements from @schabrolles !

**Comment by schlomo** [comment] 2017-09-20 10:31
Good rationalisation, Let's hope that we will get another important architecture to drive the inclusion of a new ReaR version in the future. Maybe S390 would be a good candidate :smile: Or maybe till then ARM will be sufficiently established in the data centers.

**Comment by jsmeix** [comment] 2017-09-20 10:39
I got already questions about ReaR on 'IBM z Systems' [sic!]
( cf. https://en.wikipedia.org/wiki/IBM_System_z  ;-)
and also about ReaR on ARM architecture
but in both cases I assume it will take some time.
See also
https://github.com/rear/rear/issues/1261
https://github.com/rear/rear/issues/1357
https://github.com/rear/rear/issues/1358

**Comment by jsmeix** [comment] 2017-09-20 10:50
FYI
what sources we have in SLE12-SP2 see
https://build.opensuse.org/package/show/SUSE:SLE-12-SP2:GA/rear118a
therein in particular the RPM changelos could be of interest
https://build.opensuse.org/package/view_file/SUSE:SLE-12-SP2:GA/rear118a/rear118a.changes?expand=1

**Comment by schabrolles** [comment] 2017-09-20 10:50
As jsmeix said, 
IBM ask to Suse to update the ReaR version to 2.3 to better support SAP Hana on POWER (rear-1.18 was not POWER friendly enough). 
It seems to be recently accepted by Suse to update ReaR version in "SLES-HA" for Suse 11 / 12 and the Next Suse release..... (please @jsmeix, correct me if I'm wrong)

That's why, we need to have a very clean and polished version of ReaR 2.3 ;-)

**Comment by schlomo** [comment] 2017-09-20 10:51
@schabrolles the best way to get reliably quality in ReaR is to invest into automated tests.

**Comment by schabrolles** [comment] 2017-09-20 10:56
@schlomo, I've started to automate test on POWER with Ansible.
It is currently only testing Backup/Restore on the same system
 - ISO generation
 - Backup with (NETFS or TSM ) + PXE
 - Reboot, then Recover
 - Reboot on recovered OS 
=> OS tested (Suse11, Suse12, ubuntu16.04, RHEL7)

Migration test on PowerVM is still made manually...

**Comment by schlomo** [comment] 2017-09-20 10:59
Nice. Do you see any way how you can port that to a VM that I can run on non-PPC hardware? Maybe based on QEMU? That way all of us could test if a change has an impact on PPC.

**Comment by jsmeix** [comment] 2017-09-20 11:00
@schabrolles 
it is currently planned that ReaR 2.3 should be provided
for SLEHA12 and even for SLEHA11 but I am not a
decision maker for such things.

**Comment by schabrolles** [comment] 2017-09-20 11:07
@schlomo Ansible scripts can be run on every arch/system... the problem is to adapt it to Pure KVM (but could be done... ) and having access to a PowerVM hypervisor (not really possible).

My current plan is to continue the automation on my system to add migration and PowerVM
Then, I would like to generate automatically a test when a merge is done on the git master branch and send a result by email to the team....

**Comment by gdha** [comment] 2017-09-21 09:28
@jsmeix Q: rear118a does that support `ebiso`  especially for SLES SP4 SAP HANA based systems?

**Comment by jsmeix** [comment] 2017-09-21 12:03
@gdha 
in general rear118a does support ebiso, cf
https://en.opensuse.org/SDB:Disaster_Recovery#rear_.2F_rear116_.2F_rear1172a_.2F_rear118a
but I never used that on a SLE11 system.
I asssume the crucial point is whether or not ebiso works
as intended also on a SLE11 system with UEFI.

**Comment by gozora** [comment] 2017-09-21 12:21
@jsmeix ebiso was developed on/for SLES11, so yes it does works there ;-)

**Comment by jsmeix** [comment] 2017-09-21 12:40
@gdha 
why do you ask about rear118a on SLE11?
As far as I know SUSE provides officially only rear116 for SLEHA11
so that using rear118a on SLE11 is not officially supported by
the official SUSE support - as far as I know.
Accordingly I think that for a SLE11 system with UEFI
one could as well use the latest ReaR release 2.2
or even the latest GitHub ReaR master code.
Because ReaR 2.3 is planned to be provided also for SLEHA11
I think it is even "the right way" to use now on SLE11
already the latest GitHub ReaR master code
to be closer to what is planned to be also officially
supported by SUSE for SLEHA11.
Note that right now there is no guarantee from me
what will be officially supported by SUSE for SLE11
because I am not a decision maker in this area.

**Comment by gdha** [comment] 2017-09-27 09:49
@rear/contributors I suppose this question was answered sufficient. Shall we close it?

**Comment by jsmeix** [comment] 2017-09-27 11:19
It is o.k. for me to close it because it is sufficiently answered
but it ia also o.k. for me to keep it open until ReaR in SLE11/12
was really upgraded - I will report that here when it happened.

**Comment by schabrolles** [comment] 2017-09-27 17:14
Just for information... as the version 2.0 (in rhel) is not usable on POWER, a request was send from IBM to update ReaR to >=2.3 for next rhel7.5 and rhel8.... Let's see what RedHat will answer.

**Comment by jsmeix** [comment] 2017-10-20 09:47
Because this is not an issue to be fixed for "ReaR v2.3"
I set the more generic milestone "ReaR future".

**Comment by jsmeix** [comment] 2018-07-31 09:15
FYI:

Currently SLEHA15 provides a `rear23a` package
that contains ReaR version 2.3
plus all later ReaR upstream GitHub commits up to
commit e0363b07e66df0d64a4d2c61e29917b366553688
but that has still issues with btrfs and GRUB
https://github.com/rear/rear/issues/1828

Currently I am working on a `rear23a` package update
that contains the current ReaR upstream GitHub master code
up to commit d9897b3cc5a2413057834722c06b21309b593519
which means it contains ReaR version 2.4
plus all later ReaR upstream GitHub commits up to
commit d9897b3cc5a2413057834722c06b21309b593519
but I keep the RPM package name `rear23a` so that
an installed `rear23a` RPM package can be updated.

Currently it is planned that this updated `rear23a` RPM package
should be provided for SLEHA15 and SLEHA12 and SLEHA11
but I am not the actual decision maker for such things.

**Comment by jsmeix** [comment] 2018-09-24 10:56
What "rear..." RPM packages are provided and are planned to be provided
for what SUSE Linux Enterprise version is now documented at

https://en.opensuse.org/SDB:Disaster_Recovery#rear_.2F_rear116_.2F_rear1172a_.2F_rear118a_.2F_rear23a

**Closed by jsmeix** 2018-09-24 10:56 UTC
Labels: enhancement, fixed/solved/done
