### ISSUE TITLE
ReaR 2.4 - Kernel Panic 

### ISSUE THREAD

**Issue by samurdhi** [rear/rear#1927] opened 2018-10-11 18:05 UTC
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Version 2.3 and 2.4

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
Red Hat Enterprise Linux Server release 7.0 (Maipo)

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
````
OUTPUT=ISO
OUTPUT_OPTIONS="nfsvers=3,nolock"
OUTPUT_URL=nfs://srv1/UNIXDRBACKUP
BACKUP=NETFS
BACKUP_OPTIONS="nfsvers=3,nolock"
BACKUP_URL=nfs://srv1/UNIXDRBACKUP
REQUIRED_PROGS=( "${REQUIRED_PROGS[@]}" lsblk vim )
BACKUP_PROG_EXCLUDE=( ${BACKUP_PROG_EXCLUDE[@]} '/spare/*' '/root/*'  )
````
* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):

iLO 4 ProLiant DL380 Gen9 | iLO 4 | ProLiant DL380 Gen9 |  
iLO 4
ProLiant DL380 Gen9

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):

* Storage (lokal disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
````
[root@srv2 rear]# multipath -ll
Oct 11 17:55:09 | multipath.conf +98, invalid keyword: getuid_callout
mpathb (360060e8012a1b4005040a1b400000137) dm-4 HITACHI ,OPEN-V          
size=200G features='1 queue_if_no_path' hwhandler='0' wp=rw
`-+- policy='round-robin 0' prio=1 status=active
  |- 0:0:0:1 sdd 8:48  active ready running
  |- 9:0:0:1 sdh 8:112 active ready running
  |- 0:0:1:1 sdg 8:96  active ready running
  `- 9:0:1:1 sdj 8:144 active ready running
mpatha (360060e8012a1b4005040a1b40000010e) dm-3 HITACHI ,OPEN-V          
size=300G features='1 queue_if_no_path' hwhandler='0' wp=rw
`-+- policy='round-robin 0' prio=1 status=active
  |- 0:0:1:0 sde 8:64  active ready running
  |- 0:0:0:0 sdc 8:32  active ready running
  |- 9:0:0:0 sdf 8:80  active ready running
  `- 9:0:1:0 sdi 8:128 active ready running
[root@srv2 rear]# 

````

* Description of the issue (ideally so that others can reproduce it):
I have installed rear version 2.4 on the server and generated rear backup of that server and trying to install it on another different server. But when I'm trying to boot the second server using rear ISO file, I  am unable to boot because it is getting kernel panic error while booting the ISO. Then I install rear 2.3 on the original server and did same but no success.
Grateful if you could help me to find the issue.

![image](https://user-images.githubusercontent.com/36687647/46823595-95e07280-cd5c-11e8-8e80-3efb4c18766b.png)

**Comment by gdha** [comment] 2018-10-12 06:14
@samurdhi according the screendump you are missing the `libz.so.1` library on the recovery image.
Check you rear log of the mkbackup to see if you can find libz.so library in there?

**Comment by gdha** [comment] 2018-10-12 13:44
@samurdhi The wrong **libz.so.1** was copied to the rescue image:
`'/opt/HP/BSM/Postgres/lib/libz.so.1' -> '/tmp/rear.LK1aj0oHdIoSOq3/rootfs//opt/HP/BSM/Postgres/lib/libz.so.1'`
The question is now why? You could run `rear -vD mkrescue` and perhaps we see something more in there?

**Comment by samurdhi** [comment] 2018-10-12 13:53
@gdha 

Please see below output of command "rear -vD mkrescue"

[root@srv1~]# rear -vD mkrescue
Relax-and-Recover 2.3 / 2017-12-20
Using log file: /var/log/rear/rear-srv1.log
Using backup archive '/tmp/rear.KywiRPxIHGiDnFa/outputfs/srv1/backup.tar.gz'
Creating disk layout
Using guessed bootloader 'GRUB'
Creating root filesystem layout
To log into the recovery system via ssh set up /root/.ssh/authorized_keys or specify SSH_ROOT_PASSWORD
Copying logfile /var/log/rear/rear-srv1.log into initramfs as '/tmp/rear-srv1-partial-2018-10-12T13:46:19+0000.log'
Copying files and directories
Copying binaries and libraries
Copying kernel modules
Copying all files in /lib*/firmware/
Creating recovery/rescue system initramfs/initrd initrd.cgz with gzip default compression
Created initrd.cgz with gzip default compression (101364400 bytes) in 15 seconds
Making ISO image
Wrote ISO image: /var/lib/rear/output/rear-srv1.iso (104M)
Copying resulting files to nfs location
Saving /var/log/rear/rear-srv1.log as rear-srv1.log to nfs location
You should also rm -Rf /tmp/rear.KywiRPxIHGiDnFa
[root@srv1~]#

**Comment by samurdhi** [comment] 2018-10-12 13:54
[rear-srv1.log](https://github.com/rear/rear/files/2473318/rear-srv1.log)

**Comment by gdha** [comment] 2018-10-12 15:54
@samurdhi Cannot figure out why `/opt/HP/BSM/Postgres/lib/libc.so.1` is added amongst many other libraries under /opt/HP/BSM ? However, I'm pretty sure you do need these under recovery mode, right? Therefore, I suggest to add the following line to your `/etc/rear/local.conf` file:
````
COPY_AS_IS_EXCLUDE=( "${COPY_AS_IS_EXCLUDE[@]"  '/opt/HP/BSM' )
````

**Comment by jsmeix** [comment] 2018-10-15 07:59
This issue is the same as https://github.com/rear/rear/issues/1494
but that should have been fixed since the ReaR 2.3 release via
https://github.com/rear/rear/pull/1502 and
https://github.com/rear/rear/pull/1514 and
https://github.com/rear/rear/pull/1521

Simply put:
With ReaR before the ReaR 2.3 release
as soon as some special libraries configuration is used,
the libraries in the recovery system had been likely inconsistent
and when a library is involved or missing where init is linked with,
the recovery system fails to boot with kernel panic because `init` fails.
But since the ReaR 2.3 release the libraries in the recovery system
should be consistent and each binary is tested that all its needed
libraries exist in the recovery system.

In https://github.com/rear/rear/files/2473328/rear-srv1.log
I see that usr/share/rear/build/default/980_verify_rootfs.sh
runs and tests successfully tons of binaries for missing libraries
(in particular `/bin/init` is successfully tested in the recovery system)
so that currently I do not understand why later a library
can be still missing for `init`.

FYI:
`/bin/init` in the recovery system could be `/sbin/init` on the original system
because in the recovery system `/sbin` is a symlink to `/bin`.

Perhaps the libraries setup might got broken on the original system
since it was last booted but there that is not yet noticed
because `init` is still running there since it was booted?

@samurdhi 
does it work to reboot your original system?
Caution!
When in your original system your libraries setup is broken,
it may fail to boot your original system in the same way
as now it fails to boot the ReaR recovery system.

What actual program is `init` on your original system?

E.g. on my SLES11 system `/sbin/init` is an executable
that belons to the sysvinit RPM
but on my SLES12 system `/sbin/init` is a symlink
that points to /usr/lib/systemd/systemd

How you could inspect your ReaR recovery system content
in $TMPDIR/rear.XXXXXXXXXXXXXXX/rootfs/ directly:

Set in etc/rear/local.conf
<pre>
KEEP_BUILD_DIR="yes"
</pre>

This way you can 'chroot' into the ReaR recovery system directly
on the original system where you made it with "rear mkrescue"
without the need to boot the ReaR recovery system
on another (virtual) machine only to do some tests
in the ReaR recovery system which is impossible
when the ReaR recovery system fails to come up
like here when the kernel panics because init fails, cf.
https://github.com/rear/rear/issues/1494#issuecomment-330192635

**Comment by jsmeix** [comment] 2018-10-15 09:18
@gdha 
provided my code (in particular the RequiredSharedOjects function)
works as it should libraries like `/opt/HP/BSM/Postgres/lib/libc.so.1`
get used in the recovery system because `ldd` reports them as needed.

`ldd` is called in the RequiredSharedOjects function for each binary
and for each library that is intended for the recovery system, see in
usr/share/rear/build/GNU/Linux/390_copy_binaries_libraries.sh
<pre>
local all_libs=( "${LIBS[@]}" $( RequiredSharedOjects "${all_binaries[@]}" "${LIBS[@]}" ) )
</pre>

In particular for sbin/init
https://github.com/rear/rear/files/2473328/rear-srv1.log
shows (excerpts):
<pre>
+++ RequiredSharedOjects ... /sbin/init ...
...
+++ ldd ... /sbin/init ...
...
++ Log 'Libraries being copied: ... /opt/HP/BSM/Postgres/lib/libz.so.1 ...
</pre>
so that according to the `ldd` output /opt/HP/BSM/Postgres/lib/libz.so.1
is the only 'libz.so.1' that is needed on the original system where 'ldd'
is run e.g. for '/sbin/init' (390_copy_binaries_libraries.sh and
the RequiredSharedOjects function run on the original system).

This is the reason behind why I think the libraries setup might
be already broken on the original system.

**Comment by samurdhi** [comment] 2018-10-15 19:39
@gdha 

I have added following line to config file. But it doesn't do anything.
COPY_AS_IS_EXCLUDE=( "${COPY_AS_IS_EXCLUDE[@]"  '/opt/HP/BSM' )

---------------------------------------------------------------------
OUTPUT=ISO
OUTPUT_OPTIONS="nfsvers=3,nolock"
OUTPUT_URL=nfs://srv1/UNIXDRBACKUP
BACKUP=NETFS
BACKUP_OPTIONS="nfsvers=3,nolock"
BACKUP_URL=nfs://srv1/UNIXDRBACKUP
REQUIRED_PROGS=( "${REQUIRED_PROGS[@]}" lsblk vim )
BACKUP_PROG_EXCLUDE=( ${BACKUP_PROG_EXCLUDE[@]} '/spare/*' '/root/*' '/HP_Image/*' )
COPY_AS_IS_EXCLUDE=( "${COPY_AS_IS_EXCLUDE[@]"  '/opt/HP/BSM' )
--------------------------------------------------------------------------------------

Please see attached rear log file.

[rear-srv.log](https://github.com/rear/rear/files/2480273/rear-srv.log)

Thanks,
Samurdhi

**Comment by jsmeix** [comment] 2018-10-16 07:17
@samurdhi 
what are the contents of your `/etc/ld.so.conf.d/*.conf` files?
What is your output of
<pre>
# for f in /etc/ld.so.conf.d/*.conf ; do file $f ; cat $f ; done
</pre>

Hopefully you warned them that rebooting of that production server may fail
(perhaps in the same ways as booting of your ReaR recovery system fails).

With what libraries is your `/sbin/init` linked with?
What is your output of
<pre>
# file /sbin/init ; ldd /sbin/init
</pre>

E.g. on my SLES11 system:
<pre>
 # file /sbin/init ; ldd /sbin/init
/sbin/init: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), for GNU/Linux 2.6.4, dynamically linked (uses shared libs), stripped
        linux-gate.so.1 =>  (0xffffe000)
        libselinux.so.1 => /lib/libselinux.so.1 (0xb7781000)
        libsepol.so.1 => /lib/libsepol.so.1 (0xb7744000)
        libc.so.6 => /lib/libc.so.6 (0xb75d1000)
        libdl.so.2 => /lib/libdl.so.2 (0xb75cc000)
        /lib/ld-linux.so.2 (0xb77d8000)
</pre>
versus on my SLES12 like openSUSE Leap 15.o system:
<pre>
 # file /sbin/init ; ldd /sbin/init
/sbin/init: symbolic link to ../usr/lib/systemd/systemd
        linux-vdso.so.1 (0x00007ffc717bf000)
        libsystemd-shared-234.so => /usr/lib/systemd/libsystemd-shared-234.so (0x00007fa8a3171000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fa8a2f48000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fa8a2d40000)
        libseccomp.so.2 => /usr/lib64/libseccomp.so.2 (0x00007fa8a2aff000)
        libpam.so.0 => /lib64/libpam.so.0 (0x00007fa8a28f0000)
        libkmod.so.2 => /usr/lib64/libkmod.so.2 (0x00007fa8a26bb000)
        libapparmor.so.1 => /usr/lib64/libapparmor.so.1 (0x00007fa8a24aa000)
        libmount.so.1 => /usr/lib64/libmount.so.1 (0x00007fa8a2252000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fa8a2034000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fa8a1c7a000)
        libcap.so.2 => /usr/lib64/libcap.so.2 (0x00007fa8a1a75000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fa8a185e000)
        liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007fa8a1623000)
        liblz4.so.1 => /usr/lib64/liblz4.so.1 (0x00007fa8a140e000)
        libgcrypt.so.20 => /usr/lib64/libgcrypt.so.20 (0x00007fa8a10f2000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fa8a0eee000)
        libgpg-error.so.0 => /usr/lib64/libgpg-error.so.0 (0x00007fa8a0cce000)
        libacl.so.1 => /lib64/libacl.so.1 (0x00007fa8a0ac5000)
        libblkid.so.1 => /usr/lib64/libblkid.so.1 (0x00007fa8a0877000)
        libcryptsetup.so.12 => /usr/lib64/libcryptsetup.so.12 (0x00007fa8a062b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fa8a38be000)
        libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007fa8a039e000)
        libaudit.so.1 => /usr/lib64/libaudit.so.1 (0x00007fa8a0178000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fa89ff61000)
        libattr.so.1 => /lib64/libattr.so.1 (0x00007fa89fd5c000)
        libuuid.so.1 => /usr/lib64/libuuid.so.1 (0x00007fa89fb54000)
        libdevmapper.so.1.03 => /usr/lib64/libdevmapper.so.1.03 (0x00007fa89f8fd000)
        libargon2.so.1 => /usr/lib64/libargon2.so.1 (0x00007fa89f6f5000)
        libjson-c.so.3 => /usr/lib64/libjson-c.so.3 (0x00007fa89f4e5000)
        libudev.so.1 => /usr/lib64/libudev.so.1 (0x00007fa89f2c3000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fa89ef78000)
</pre>

**Comment by samurdhi** [comment] 2018-10-16 13:13
@jsmeix 

Please see below command outputs of the server

[root@srv1 ~]# for f in /etc/ld.so.conf.d/*.conf ; do file $f ; cat $f ; done
/etc/ld.so.conf.d/dyninst-x86_64.conf: ASCII text
/usr/lib64/dyninst
/etc/ld.so.conf.d/kernel-3.10.0-123.20.1.el7.x86_64.conf: ASCII text
# Placeholder file, no vDSO hwcap entries used in this kernel.
/etc/ld.so.conf.d/kernel-3.10.0-123.el7.x86_64.conf: ASCII text
# Placeholder file, no vDSO hwcap entries used in this kernel.
/etc/ld.so.conf.d/kernel-3.10.0-229.20.1.el7.x86_64.conf: ASCII text
# Placeholder file, no vDSO hwcap entries used in this kernel.
/etc/ld.so.conf.d/mariadb-x86_64.conf: ASCII text
/usr/lib64/mysql
[root@srv1 ~]# 
[root@srv1 ~]# file /sbin/init ; ldd /sbin/init
/sbin/init: symbolic link to `../lib/systemd/systemd'
        linux-vdso.so.1 =>  (0x00007ffdc047c000)
        libselinux.so.1 => /usr/lib64/libselinux.so.1 (0x00007f2de428d000)
        libcap.so.2 => /usr/lib64/libcap.so.2 (0x00007f2de4087000)
        libpam.so.0 => /usr/lib64/libpam.so.0 (0x00007f2de3e78000)
        libaudit.so.1 => /usr/lib64/libaudit.so.1 (0x00007f2de3c52000)
        libkmod.so.2 => /usr/lib64/libkmod.so.2 (0x00007f2de3a3b000)
        libmount.so.1 => /usr/lib64/libmount.so.1 (0x00007f2de37fd000)
        librt.so.1 => /usr/lib64/librt.so.1 (0x00007f2de35f5000)
        libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007f2de33de000)
        libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007f2de31c2000)
        libc.so.6 => /usr/lib64/libc.so.6 (0x00007f2de2e01000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2de4618000)
        libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007f2de2b9f000)
        liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007f2de297a000)
        libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f2de2776000)
        libattr.so.1 => /usr/lib64/libattr.so.1 (0x00007f2de2570000)
        libz.so.1 => /opt/HP/BSM/Postgres/lib/libz.so.1 (0x00007f2de2355000)
        libblkid.so.1 => /usr/lib64/libblkid.so.1 (0x00007f2de2119000)
        libuuid.so.1 => /usr/lib64/libuuid.so.1 (0x00007f2de1f13000)
[root@srv1~]#

**Comment by samurdhi** [comment] 2018-10-16 13:13
@jsmeix 

Please see below command outputs of the server

[root@srv1 ~]# for f in /etc/ld.so.conf.d/*.conf ; do file $f ; cat $f ; done
/etc/ld.so.conf.d/dyninst-x86_64.conf: ASCII text
/usr/lib64/dyninst
/etc/ld.so.conf.d/kernel-3.10.0-123.20.1.el7.x86_64.conf: ASCII text
# Placeholder file, no vDSO hwcap entries used in this kernel.
/etc/ld.so.conf.d/kernel-3.10.0-123.el7.x86_64.conf: ASCII text
# Placeholder file, no vDSO hwcap entries used in this kernel.
/etc/ld.so.conf.d/kernel-3.10.0-229.20.1.el7.x86_64.conf: ASCII text
# Placeholder file, no vDSO hwcap entries used in this kernel.
/etc/ld.so.conf.d/mariadb-x86_64.conf: ASCII text
/usr/lib64/mysql
[root@srv1 ~]# 
[root@srv1 ~]# file /sbin/init ; ldd /sbin/init
/sbin/init: symbolic link to `../lib/systemd/systemd'
        linux-vdso.so.1 =>  (0x00007ffdc047c000)
        libselinux.so.1 => /usr/lib64/libselinux.so.1 (0x00007f2de428d000)
        libcap.so.2 => /usr/lib64/libcap.so.2 (0x00007f2de4087000)
        libpam.so.0 => /usr/lib64/libpam.so.0 (0x00007f2de3e78000)
        libaudit.so.1 => /usr/lib64/libaudit.so.1 (0x00007f2de3c52000)
        libkmod.so.2 => /usr/lib64/libkmod.so.2 (0x00007f2de3a3b000)
        libmount.so.1 => /usr/lib64/libmount.so.1 (0x00007f2de37fd000)
        librt.so.1 => /usr/lib64/librt.so.1 (0x00007f2de35f5000)
        libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007f2de33de000)
        libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007f2de31c2000)
        libc.so.6 => /usr/lib64/libc.so.6 (0x00007f2de2e01000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2de4618000)
        libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007f2de2b9f000)
        liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007f2de297a000)
        libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f2de2776000)
        libattr.so.1 => /usr/lib64/libattr.so.1 (0x00007f2de2570000)
        libz.so.1 => /opt/HP/BSM/Postgres/lib/libz.so.1 (0x00007f2de2355000)
        libblkid.so.1 => /usr/lib64/libblkid.so.1 (0x00007f2de2119000)
        libuuid.so.1 => /usr/lib64/libuuid.so.1 (0x00007f2de1f13000)
[root@srv1~]#

**Comment by jsmeix** [comment] 2018-10-16 14:15
@samurdhi 
compared to what I have on my SLES systems cf.
https://github.com/rear/rear/issues/1927#issuecomment-430127980
things do not look o.k. on your RHEL system
but I do not use RHEL so that I cannot tell if things are really broken
on your RHEL system, but at least your `ldd /sbin/init` output line
<pre>
libz.so.1 => /opt/HP/BSM/Postgres/lib/libz.so.1
</pre>
looks broken.

@gdha 
I do not have a RHEL system installed so that
I would like to ask you if you could have a look if
the dynamic linker config files of @samurdhi in
https://github.com/rear/rear/issues/1927#issuecomment-429999909
and
https://github.com/rear/rear/issues/1927#issuecomment-430232244
seems to be o.k. on a RHEL system.

FYI:
The dynamic linker config files on my SLES systems:
On SLES11:
<pre>
# cat /etc/ld.so.conf
/usr/X11R6/lib/Xaw3d
/usr/X11R6/lib
/usr/lib/Xaw3d
/usr/i386-suse-linux/lib
/usr/local/lib
/opt/kde3/lib
include /etc/ld.so.conf.d/*.conf
</pre>
<pre>
# for f in /etc/ld.so.conf.d/*.conf ; do file $f ; cat $f ; done
/etc/ld.so.conf.d/ghostscript-omni.conf: ASCII text
/usr/lib/ghostscript/Omni
/etc/ld.so.conf.d/graphviz.conf: ASCII text
/usr/lib/graphviz
/usr/lib/graphviz/sharp
/usr/lib/graphviz/java
/usr/lib/graphviz/perl
/usr/lib/graphviz/php
/usr/lib/graphviz/ocaml
/usr/lib/graphviz/python
/usr/lib/graphviz/lua
/usr/lib/graphviz/tcl
/usr/lib/graphviz/guile
/usr/lib/graphviz/ruby
/etc/ld.so.conf.d/novell-NLDAPsdk-dyn.conf: ASCII text
/opt/novell/ldapsdk-dyn/lib
/etc/ld.so.conf.d/samba4.conf: ASCII text
/usr/lib/samba4/lib
</pre>
On my SLES12 like openSUSE Leap 15.0 system:
<pre>
# cat /etc/ld.so.conf
/usr/local/lib64
/usr/local/lib
include /etc/ld.so.conf.d/*.conf
# /lib64, /lib, /usr/lib64 and /usr/lib gets added
# automatically by ldconfig after parsing this file.
# So, they do not need to be listed.
</pre>
<pre>
# for f in /etc/ld.so.conf.d/*.conf ; do file $f ; cat $f ; done
/etc/ld.so.conf.d/graphviz.conf: ASCII text
/usr/lib64/graphviz
/usr/lib64/graphviz/sharp
/usr/lib64/graphviz/java
/usr/lib64/graphviz/perl
/usr/lib64/graphviz/php
/usr/lib64/graphviz/ocaml
/usr/lib64/graphviz/python
/usr/lib64/graphviz/lua
/usr/lib64/graphviz/tcl
/usr/lib64/graphviz/guile
/usr/lib64/graphviz/ruby
</pre>

**Comment by jsmeix** [comment] 2018-10-24 14:44
@samurdhi 
any news?

**Comment by jsmeix** [comment] 2018-10-26 14:54
Because "no news is good news" I close it hereby.

@samurdhi 
regardless that it is closed you can still add comments
(I would be interested to learn how it turns out).

**Closed by jsmeix** 2018-10-26 14:54 UTC
Labels: fixed/solved/done, support/question

**Comment by jsmeix** [comment] 2018-10-30 09:11
https://github.com/rear/rear/issues/1907#issuecomment-434024416
actually belongs here so that also
https://github.com/rear/rear/issues/1907#issuecomment-434215448
and
https://github.com/rear/rear/issues/1907#issuecomment-434218293
belong here.

In the end Hewlett Packard's setenv.sh script did
`export LD_LIBRARY_PATH=somewhere` for some users
that messes up the system libraries configuration
for the users where such a LD_LIBRARY_PATH is set
so that the root cause is a broken dynamic libraries setup
on the original system which makes this issue "not ReaR / invalid".

**Comment by samurdhi** [comment] 2018-11-06 20:22
@gdha @jsmeix

I was able to take ReaR Iso and it was not given me a kernel panic issue. what I did was, I cleared the LD_LIBRARY_PATH variable and ran **rear -dv mkbackup.** It solved the kernel panic issue.

**export LD_LIBRARY_PATH=""**

[root@srv ~]# ldd /sbin/init
linux-vdso.so.1 => (0x00007ffe9a718000)
libselinux.so.1 => /usr/lib64/libselinux.so.1 (0x00007f6bf3700000)
libcap.so.2 => /usr/lib64/libcap.so.2 (0x00007f6bf34fa000)
libpam.so.0 => /usr/lib64/libpam.so.0 (0x00007f6bf32eb000)
libaudit.so.1 => /usr/lib64/libaudit.so.1 (0x00007f6bf30c5000)
libkmod.so.2 => /usr/lib64/libkmod.so.2 (0x00007f6bf2eae000)
libmount.so.1 => /usr/lib64/libmount.so.1 (0x00007f6bf2c70000)
librt.so.1 => /usr/lib64/librt.so.1 (0x00007f6bf2a68000)
libgcc_s.so.1 => /usr/lib64/libgcc_s.so.1 (0x00007f6bf2851000)
libpthread.so.0 => /usr/lib64/libpthread.so.0 (0x00007f6bf2635000)
libc.so.6 => /usr/lib64/libc.so.6 (0x00007f6bf2274000)
/lib64/ld-linux-x86-64.so.2 (0x00007f6bf3a8b000)
libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007f6bf2012000)
liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007f6bf1ded000)
libdl.so.2 => /usr/lib64/libdl.so.2 (0x00007f6bf1be9000)
libattr.so.1 => /usr/lib64/libattr.so.1 (0x00007f6bf19e3000)
**libz.so.1 => /opt/HP/BSM/Postgres/lib/libz.so.1 (0x00007f6bf17c8000)**
libblkid.so.1 => /usr/lib64/libblkid.so.1 (0x00007f6bf158c000)
libuuid.so.1 => /usr/lib64/libuuid.so.1 (0x00007f6bf1386000)
[root@srv ~]#
[root@srv ~]# export LD_LIBRARY_PATH=""
[root@srv ~]#
[root@srv ~]# ldd /sbin/init
linux-vdso.so.1 => (0x00007fff5f3f4000)
libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f00ac8b1000)
libcap.so.2 => /lib64/libcap.so.2 (0x00007f00ac6ac000)
libpam.so.0 => /lib64/libpam.so.0 (0x00007f00ac49c000)
libaudit.so.1 => /lib64/libaudit.so.1 (0x00007f00ac276000)
libkmod.so.2 => /lib64/libkmod.so.2 (0x00007f00ac060000)
libmount.so.1 => /lib64/libmount.so.1 (0x00007f00abe21000)
librt.so.1 => /lib64/librt.so.1 (0x00007f00abc19000)
libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f00aba03000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f00ab7e6000)
libc.so.6 => /lib64/libc.so.6 (0x00007f00ab425000)
/lib64/ld-linux-x86-64.so.2 (0x00007f00acc4a000)
libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f00ab1c4000)
liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f00aaf9e000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007f00aad9a000)
libattr.so.1 => /lib64/libattr.so.1 (0x00007f00aab95000)
**libz.so.1 => /lib64/libz.so.1 (0x00007f00aa97e000)**
libblkid.so.1 => /lib64/libblkid.so.1 (0x00007f00aa742000)
libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f00aa53d000)
[root@srv ~]#
