### ISSUE TITLE
Unable to Restore Backup

### ISSUE THREAD

**Issue by akshaysarraf2016** [rear/rear#832] opened 2016-05-12 07:00 UTC
# Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue:

* rear version (/usr/sbin/rear -V):  Relax-and-Recover 1.17.2 / Git
* OS version (cat /etc/rear/os.conf or lsb_release  -a): RHEL 6.7
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf): 
OUTPUT=ISO
GRUB_RESCUE=1
* Brief description of the issue

**Issue** - I was trying to clone a system via Rear. I used some other system's rescue image. When I reach to rescue shell it asks me to restore all the data to /mnt/local. How do I do that ? 
I want to use TSM for restore. I cannot do unless there is a TSM Client installed on it. 
How can I do this? Any Idea?
I cant install anything now, as it is in rescue mode. 

Is there any other way to do it ? 
Is there a Procedure to make Rear work with TSM ?

Thank You
Akshay Saraf

**Comment by gdha** [comment] 2016-05-12 07:38
On the source system you should also add `BACKUP=TSM` to the `local.conf` file and make sure you have a full backup made by TSM. Use the newly created rear rescue image to boot on the target system and you are ready to go.

**Comment by jsmeix** [comment] 2016-05-12 07:55
And see usr/share/rear/conf/default.conf
in particular see therein the "BACKUP=TSM stuff".

FYI
why you got that
<pre>
Please start the restore process on your backup host.
Make sure that you restore the data into /mnt/local
instead of '/' because the hard disks of the recovered
system are mounted there.
</pre>
text see also usr/share/rear/conf/default.conf that contains
<pre>
# default backup and output targets
BACKUP=REQUESTRESTORE
...
# BACKUP=REQUESTRESTORE stuff
##
# This mode stops the restore after formatting and mounting the filesystems and expects
# the backup data to appear by miracle (e.g. you doing something).
...
# The text to display in order to prompt the user to restore the data
REQUESTRESTORE_TEXT="Please start the restore process on your backup host.

Make sure that you restore the data into $TARGET_FS_ROOT (by default '/mnt/local')
instead of '/' because the hard disks of the recovered system are mounted there.
"
</pre>

**Comment by akshaysarraf2016** [comment] 2016-05-13 05:46
Thank s lot for your prompt response. 
How will I restore from TSM when the System is in Rescue Mode ? 
Can TSM Push Backup ? 
Won't it need TSM Client installed that time ?



Thank You
Akshay Saraf

**Comment by gdha** [comment] 2016-05-13 05:59
When booted from the rescue image just type 'rear -v recover' and the
restore will be invoked via TSM - pure magic, no?

**Comment by Joeri-MS** [comment] 2016-05-13 06:00
Sorry, you have to install the TSM Client on the rescue system.
Here are my /etc/rear/local.conf part for TSM-Restore for an Redhat 6.x System:

```
BACKUP=TSM
PROGS_TSM=(dsmc)
TSM_RESULT_FILE_PATH=/opt/tivoli/tsm/rear
TSM_RESULT_SAVE=n
```
Now create a new rescue image and an working TSM Cllint wil be there.

**Comment by akshaysarraf2016** [comment] 2016-05-24 03:38
Thanks a Lot Joeri-MS. Yout configuration worked Perfectly. Could you please tell me what does TSM_RESULT_FILE_PATH Mean ?

Also when I run "rear -v mkbackup" after this configuration. It creates a rear ISO file in /var/lib/rear/output directory and also in /opt/tivoli/tsm/rear directory. What is the difference between these 2 files ?

**Comment by gdha** [comment] 2016-05-24 07:37
@Joeri-MS `conf/default.conf:PROGS_TSM=(dsmc)` so there is no need to add it to the `local.conf` file.
@akshaysarraf2016 
````
onf/default.conf:# where to copy the resulting files to and save them with TSM
conf/default.conf:TSM_RESULT_FILE_PATH=/opt/tivoli/tsm/rear
````
And, you are right currently you will find the exact ISO images on your system (see issue #734 which is not implemented yet).

**Comment by jsmeix** [comment] 2016-09-28 13:22
No further comments since more than 4 month
indicate that the issue is sufficiently answered.
I am closing it now.
If needed it can be reopened.

**Closed by jsmeix** 2016-09-28 13:22 UTC
Labels: fixed, support
