### ISSUE TITLE
RHEL on Power different mpath Backup and Recovery.

### ISSUE THREAD

**Issue by skywallger** [rear/rear#2217] opened 2019-08-19 04:03 UTC
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):  
  - Relax-and-Recover 2.00 / Git

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
  - OS_VENDOR=RedHatEnterpriseServer
  - OS_VERSION=7
* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
   -OUTPUT=ISO
   - BACKUP=NETFS
   - BACKUP_URL=nfs://10.209.1.97/ftpbulk
    -BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/source' '/mnt/cdrom' '/media' '/var/tmp' '/var/crash')
    -AUTOEXCLUDE_MULTIPATH=n

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
   - LPAR on PowerVC 

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
   - PPC64
* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
    - bootloader  GRUB
* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
   - multipath DM
* Description of the issue (ideally so that others can reproduce it):
  - Backup successfully. and  can note recovery because mpathb  file not found
    Disk configuration is identical, proceeding with restore.
    No code has been generated to restore device fs:/srv/node/partition1 (fs).
    Please add code to /var/lib/rear/layout/diskrestore.sh to manually install                                                                                                                                                    
    it or choose abort.
   1) Continue
   2) Abort
 #? 1
   Start system layout restoration.
     Creating partitions for disk /dev/mapper/mpathb (msdos)
     An error occurred during layout recreation.
  rear> multipath -l
_mpatha (36005076380818336840000000000015d)_ dm-0 IBM     ,2145
size=100G features='1 queue_if_no_path' hwhandler='0' wp=rw
|-+- policy='service-time 0' prio=0 status=active
| |- 1:0:0:0 sda 8:0   active undef unknown
| |- 2:0:0:0 sdc 8:32  active undef unknown
| |- 3:0:0:0 sde 8:64  active undef unknown
| `- 4:0:1:0 sdh 8:112 active undef unknown
`-+- policy='service-time 0' prio=0 status=enabled
  |- 1:0:1:0 sdb 8:16  active undef unknown
  |- 2:0:1:0 sdd 8:48  active undef unknown
  |- 3:0:1:0 sdf 8:80  active undef unknown
  `- 4:0:0:0 sdg 8:96  active undef unknown

Verify on OS mpath is math id but different name .
_mpathb (36005076380818336840000000000015d)_ dm-0 IBM     ,2145
size=100G features='1 queue_if_no_path' hwhandler='0' wp=rw
|-+- policy='service-time 0' prio=0 status=active
| |- 1:0:0:0 sda 8:0   active undef unknown
| |- 2:0:0:0 sdc 8:32  active undef unknown
| |- 3:0:0:0 sde 8:64  active undef unknown
| `- 4:0:1:0 sdh 8:112 active undef unknown
`-+- policy='service-time 0' prio=0 status=enabled
  |- 1:0:1:0 sdb 8:16  active undef unknown
  |- 2:0:1:0 sdd 8:48  active undef unknown
  |- 3:0:1:0 sdf 8:80  active undef unknown
  `- 4:0:0:0 sdg 8:96  active undef unknown

* Workaround, if any:
   - - -  how to ? why different name mpath.
* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):
RESCUE hostshare
[rear-hpeshare2.log](https://github.com/rear/rear/files/3514130/rear-hpeshare2.log)
[rear-hpeshare2.log](https://github.com/rear/rear/files/3514135/rear-hpeshare2.log)

:~ # rear -Dv recover
Relax-and-Recover 2.00 / Git
Using log file: /var/log/rear/rear-hpeshare2.log
Running workflow recover within the ReaR rescue/recovery system
Starting required daemons for NFS: RPC portmapper (portmap or rpcbind) and rpc.s                                                                                                             tatd if available.
Started RPC portmapper 'rpcbind'.
RPC portmapper 'rpcbind' available.
Started rpc.statd.
RPC status rpc.statd available.
Started rpc.idmapd.
Using backup archive 'backup.tar.gz'
Calculating backup archive size
Backup archive size is 2.2G     /tmp/rear.ocTZPkGvOhS8ePt/outputfs/hpeshare2/bac                                                                                                             kup.tar.gz (compressed)
Comparing disks.
Disk configuration is identical, proceeding with restore.
No code has been generated to restore device fs:/srv/node/partition1 (fs).
    Please add code to /var/lib/rear/layout/diskrestore.sh to manually install i                                                                                                             t or choose abort.
++ select choice in '"Continue"' '"Abort"'
1) Continue
2) Abort
#? 1
++ '[' Continue = Continue ']'
++ break
Start system layout restoration.
Creating partitions for disk /dev/mapper/mpathb (msdos)
An error occurred during layout recreation.

++ select choice in '"${choices[@]}"'
1) View Relax-and-Recover log
2) View original disk space usage
3) Go to Relax-and-Recover shell
4) Edit restore script (diskrestore.sh)
5) Continue restore script
6) Abort Relax-and-Recover
#?

**Comment by pcahyna** [comment] 2019-08-30 08:32
@rmetrich do you please have any idea how this should work?

**Comment by rmetrich** [comment] 2019-08-30 09:44
@skywallger 
There is no guarantee about the name generated. To have something persistent, /etc/multipath* must be copied into the ISO.
Probably in the OS, you had another disk mapped to mpatha at some time.

**Comment by rmetrich** [comment] 2019-09-09 08:38
Hi @skywallger 
Checking the "rear mkrescue" log, I can see that you are using rear-2.00 and that your disk is named **mpathb** (there is no **mpatha**).
With rear-2.00, `/etc/multipath/*` content was not included in the ReaR ISO, explaining the issue:
because there is no explicit mapping, then ReaR ISO assigns **mpatha** to the system disk.

This was fixed with https://github.com/rear/rear/commit/3cf070c1757c6eadbbb5ed05df57e5ba75647d98

**Closed by rmetrich** 2019-09-09 08:38 UTC
Labels: support / question

**Comment by skywallger** [comment] 2019-09-16 03:30
@rmetrich   
Should I change the version or not, is there a recommended version?

**Comment by rmetrich** [comment] 2019-09-16 07:04
@skywallger Try with rear-2.4, it should work, we now include /etc/multipath/* files in the ISO.

**Comment by jsmeix** [comment] 2019-09-17 11:18
@rmetrich 
thank you for your analysis what the root cause was!

**Comment by skywallger** [comment] 2019-09-20 02:23
@rmetrich @jsmeix   Thank very much for advice . I can recovery compleete  on rear 2.0 from fixed with 3cf070c.
