### ISSUE TITLE
What to improve in ReaR project as lesson learned from XZ Attack?

### ISSUE THREAD

**Issue by jsmeix** [rear/rear#3202] opened 2024-04-08 12:39 UTC
For background information about the XZ Attack see
https://en.wikipedia.org/wiki/XZ_Utils_backdoor
and follow the links therein, in particular see
https://tukaani.org/xz-backdoor/
and
https://gist.github.com/thesamesam/223949d5a074ebc3dce9ee78baad9e27

**Comment by jsmeix** [comment] 2024-04-08 13:08
In addition to enforce that code must be easy to understand
I think we should also enforce to review all code changes.

This means that all code changes
(also code changes by us, the upstream maintainers)
must be approved by at least one other upstream maintainer
even if that makes merging code changes into 'master' slower.

But I think that a certain kind of slowness is helpful
when it comes from "verify" in "Trust, but verify"
https://en.wikipedia.org/wiki/Trust,_but_verify

In practice enforced code change reviews means
that all code changes must happen via a pull request.

I mean only actual code changes (at least for now).
I.e. all what changes what ReaR does on the user's system.

E.g. typo fixes in comments can still be directly merged
regardless that even a "typo fix" in a comment may
(unintentionally or by evil intent) be a false change
of the meaning of a comment so others get a false
understanding what (some weird looking) code
actually does which could be a first step to do
later a malicious change in the actual code.

**Comment by gdha** [comment] 2024-04-09 06:34
As mentioned already mentioned before all Pull Requests must be reviewed by another person then the author, and I would like to add an additional third person - the co-called "approver" of the PR. This way there always 3 persons involved before a PR is getting merged.

**Comment by schlomo** [comment] 2024-04-09 06:50
We can enable [branch protection](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches) to help us "remember" the PR rule, although maintainers of course can override that.

I'm against a 6-eyes approval, at least now, because I think that going from "just do it" to "everything via PR" is already a big and probably sometimes inconvenient step for us. As we don't have any actual problem, I'd like to take this slowly, step by step. And inspect and adapt after every change.

**Comment by jsmeix** [comment] 2024-04-09 08:26
I also think that 6-eyes approval is too much for us for now.
Often I don't get a single approval for my pull requests and
when I get one I think it is often not after a thorough review.
I totally understand this because in most cases I don't do
a thorough review but only have a look if I spot something
and if not I just trust you.

I always prefer to change things slowly, step by step.

In think for now it is enough to have some kind of "enforced"
approval by at least one other upstream maintainer
for pull requests from an upstream maintainer.

Perhaps we should "enforce" approval by at least
two upstream maintainers for pull requests
from external contributors?

With "enforce" I mean that we set up something in GitHub
which we can of course override but that would at least
remind us each time to not "just merge" something without
approval by at least one other upstream maintainer.

FWIW:
I remember well how @pcahyna asked me
again and again questions during
https://github.com/rear/rear/pull/2961
because he did not understand my description in default.conf.
I even felt somewhat annoyed by his insisting questions
("why the heck doesn't he understand my nice description?")
until finally I saw it that what I described
did not match what I had implemented, cf.
https://github.com/rear/rear/pull/2961#discussion_r1363679930
I was blind regarding my own faulty description
(from 09. Oct. 2023 until 18. Oct. 2023).
I still cannot understand why I was so blind.
So @pcahyna helped me to finally see my fault and
he helped our users to not get my faulty description.

**Comment by gdha** [comment] 2024-04-09 08:32
Perhaps, the biggest danger is not in the source code itself, but in the produced ISO images stored on a NAS location where everybody (within a company) can replace it with a malicious code (or whatever evil).

**Comment by schlomo** [comment] 2024-04-09 08:39
Yes, that is however by design and we shouldn't worry about it.

Maybe Secure Boot with custom keys can be used to create end-end secured DR boot media

**Comment by jsmeix** [comment] 2024-04-09 09:42
With this issue here I meant only our source code,
in particular how to better ensure that our users
actually get what we intended to provide them.

Regarding secure ReaR recovery system images:
I don't remember there had been a user request in the past
for an secured ReaR boot medium so at least currently
this seems to be not an issue for our users.
I assume our users know how to keep e.g. ReaR ISOs secure.
I assume they handle ReaR boot media same as their backups.
One does not want to restore a maliciously modified backup
(e.g. where /usr/sbin/sshd got "additional functionality").

**Comment by jsmeix** [comment] 2024-04-12 13:43
FYI:
an openSUSE report about the XZ Backdoor issue:

https://news.opensuse.org/2024/04/12/learn-from-the-xz-backdoor/

**Closed** 2024-06-19 02:19 UTC
Labels: discuss / RFC, ReaR Project, no-issue-activity
