### ISSUE TITLE
tar --test-label is not supported on Centos 5 who have tar version 1.15.

### ISSUE THREAD

**Issue by philippebolduc** [rear/rear#1014] opened 2016-09-28 14:19 UTC
# Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue:

* rear version (/usr/sbin/rear -V):
* OS version (cat /etc/rear/os.conf or lsb_release  -a):
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
* Brief description of the issue
* Work-around, if any

**Comment by philippebolduc** [comment] 2016-09-28 14:21
Relax-and-Recover 1.18 / Git
cat /etc/rear/os.conf
OS_VENDOR=RedHatEnterpriseServer
OS_VERSION=5
cat /etc/rear/local.conf
# sample local configuration

# Create Rear rescue media as ISO image
OUTPUT=ISO
USE_DHCLIENT=yes 
# optionally define (non-default) backup software, e.g. TSM, NBU, DP, BACULA
# BACKUP=TSM
BACKUP_TYPE=incremental
FULLBACKUPDAY="Sun"
BACKUP=NETFS
BACKUP_URL=nfs://10.2.1.40/backup
# the following is required on older VMware VMs
MODULES_LOAD=( vmxnet )

# to see boot messages on the serial console (uncomment next line)
# KERNEL_CMDLINE="console=tty0 console=ttyS1

Restore do not work

Change line 53
From
BASE=$BASEDIR/$(tar --test-label -f "$restorearchive")
To
BASE=$BASEDIR/$(cat $BASEDIR/basebackup.txt)

**Comment by jsmeix** [comment] 2016-09-28 14:46
@gdha 
because this issue is related to your
https://github.com/rear/rear/commit/847323fbedefda7376530bd2e3e13cae87fa9b38
I assign it also to you.

I will prepare a pull request and then you can decide
if you accept it.

**Comment by jsmeix** [comment] 2016-09-28 15:04
This is the right pull request:
https://github.com/rear/rear/pull/1016

**Comment by philippebolduc** [comment] 2016-09-28 15:17
Ok what should I do now ?


Thanks.

Philippe Bolduc
Administrateur système Linux / Programmeur analyste
Linux System Administrator / Programmer Analyst

<http://www.florenceinc.com/>
3382, boul. Industriel
Laval (Québec)
H7L 4R9
T :: 514-875-7525 #235
F :: 514-875-7536
C :: philippe@florenceinc.com
W :: florenceinc.com

**Comment by jsmeix** [comment] 2016-09-28 15:25
@philippebolduc 
do nothing - just wait (like me) what @gdha will tell us.

**Comment by philippebolduc** [comment] 2016-09-28 15:26
Ok thanks.


Philippe Bolduc
Administrateur système Linux / Programmeur analyste
Linux System Administrator / Programmer Analyst

<http://www.florenceinc.com/>
3382, boul. Industriel
Laval (Québec)
H7L 4R9
T :: 514-875-7525 #235
F :: 514-875-7536
C :: philippe@florenceinc.com
W :: florenceinc.com

**Comment by gdha** [comment] 2016-09-29 11:33
@jsmeix IMHO we should work with `tar_version=$(get_version tar --version)` and make a decision based on a version of `tar` from when the option `--test-label` was introduced. I found evidence on the Internet it was introduced in version **1.15.90** (see http://cvs.savannah.gnu.org/viewvc/*checkout*/tar/NEWS?view=auto&root=tar&revision=1.125) (released on 2006-02-19).
@philippebolduc My suggestion to you is to upgrade `tar` to at least version 1.15.92 and your problem is over.

I have the feeling it is not worth the effort to modify the code in _rear_ as the option `--test-label` is already 10 years present within `tar`.

**Comment by philippebolduc** [comment] 2016-09-29 11:55
Do tar 1.15.92 avalaible easily via rpm on Centos 5 ?

Thanks.

Philippe Bolduc
Administrateur système Linux / Programmeur analyste
Linux System Administrator / Programmer Analyst

<http://www.florenceinc.com/>
3382, boul. Industriel
Laval (Québec)
H7L 4R9
T :: 514-875-7525 #235
F :: 514-875-7536
C :: philippe@florenceinc.com
W :: florenceinc.com

**Comment by jsmeix** [comment] 2016-09-29 13:27
@gdha 
I agree that rear does not need to support very old versions
of tools that are called by the rear scripts - in particular
because basically nobody tests that.

On the other hand doc/rear-release-notes.txt currently reads
<pre>
Rear-1.18 is supported on the following Linux based operating systems:
...
CentOS 5, 6 and 7
</pre>

But on one more other hand (again a "tertium datur" ;-)
the rear scripts are meant to be adapted by the admin
as needed in his particular case so that it can be considered
to be o.k. when @philippebolduc must adapt rear to make it work
for his CentOS 5 (or upgrade tar on his CentOS 5).

I think we should not do the effort to keep
the current rear working also for tar < 1.15.92

As a consequence for the upcoming rear-1.19
we may drop officially support for CentOS 5.

Some forensics on that issue:

The string '--test-label' is only in
restore/NETFS/default/40_restore_backup.sh
and
"git log -p -w restore/NETFS/default/40_restore_backup.sh"
shows when the '--test-label' was introduced:
<pre>
commit 354486da3191dbfe5c6a4b896e34977be10697d5
Author: test <kreitz@Dev-Server.mhknet.de>
Date:   Mon Sep 2 11:39:52 2013 +0200
...
+                       BASE=$(dirname "$restorearchive")/$(tar --test-label -f "$restorearchive")
</pre>
but "git log" does not show any useful message for that commit:
<pre>
commit 354486da3191dbfe5c6a4b896e34977be10697d5
Author: test <kreitz@Dev-Server.mhknet.de>
Date:   Mon Sep 2 11:39:52 2013 +0200

    Incrementap Patches
</pre>

I.e. it was this commit
https://github.com/rear/rear/commit/354486da3191dbfe5c6a4b896e34977be10697d5

According to
https://en.wikipedia.org/wiki/CentOS
CentOS 5 was releasted in April 2007
and that commit happened in 2013
so that I assume before rear had worked for CentOS 5
but since that commit it does no longer work for CentOS 5.

**Comment by gdha** [comment] 2016-09-29 13:34
@jsmeix For CentOS 5: the`tar --test-label` is only used when `BACKUP_TYPE=incremental` has been selected, therefore, it is only problematic in some cases. I can comment it in the FAQ section of our web pages?

@philippebolduc If you do not find a suitable rpm for _tar v1.15.9x_ you could try to build it from the sources?

**Comment by jsmeix** [comment] 2016-09-29 13:51
Ah!
Now I understand (at least I think so).

The commit
https://github.com/rear/rear/commit/354486da3191dbfe5c6a4b896e34977be10697d5
did not break existing functionality for CentOS 5
but only implemented the new functionality
"BACKUP_TYPE=incremental" is a way that
does not work with tar < 1.15.92.

If I am right it means there is no real bug here
(i.e. I remove "bug" from that issue and keep
only "enhancement").

Because we will not do the work to make the new
"BACKUP_TYPE=incremental" functionality
working with old tar < 1.15.92 I close this
enhancement request as "won't fix".

**Closed by jsmeix** 2016-09-29 13:51 UTC
Labels: enhancement, won't fix

**Comment by jsmeix** [comment] 2016-09-29 13:56
@philippebolduc 
regardless that we will not fix the issue
many thanks for your valuable contribution
to Relax-and-Recover because now we learned under
what special circumstances tar < 1.15.92 fails and you
even provided a "quick and dirty" workaround that could
also be used by other users who have that issue.

**Comment by jsmeix** [comment] 2016-09-29 14:01
@philippebolduc 
in general regarding "BACKUP_TYPE=incremental" note its limits
that are describen only in the current documentation
cf. https://github.com/rear/rear/issues/974 and
https://github.com/rear/rear/commit/35fc7c93242221e58f148f2aa318a52b07dcc9fb
in short:
<pre>
The current implementation supports only to restore
one full backup plus one single incremental backup
so that currently BACKUP_TYPE=incremental
actually implements a differential backup
</pre>

**Comment by jsmeix** [comment] 2016-09-29 14:13
@philippebolduc 
that "we will not fix the issue" does of course not mean
that another contributor (e.g. you) could not enhance
the current "BACKUP_TYPE=incremental" functionality
so that it also works with old tar < 1.15.92 provided
the enhancement is made in a way that it cannot
cause regressions for users with newer tar.

Of course we appreciate GitHub pull requests
that enhance Relax-and-Recover functionality.

You may have a look at
https://github.com/rear/rear/wiki/Coding-Style

**Comment by gdha** [comment] 2016-10-04 11:36
Added a note in the release notes of 1.19
