### ISSUE TITLE
'Unknown bootloader ()' when running rear -v mkrescue

### ISSUE THREAD

**Issue by shibhikkiran** [rear/rear#1929] opened 2018-10-15 08:24 UTC
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.00 / Git

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
CentOS Linux release 7.5.1804 (Core)

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
<pre>
# cat /etc/rear/local.conf|grep -v ^#
OUTPUT=ISO
BACKUP=NETFS
BACKUP_PROG=tar
BACKUP_TYPE=full
BACKUP_PROG_COMPRESS_OPTIONS="--gzip"
BACKUP_PROG_COMPRESS_SUFFIX=".gz"
BACKUP_PROG_EXCLUDE=(  '/tmp/*' '/dev/shm/*' )
BACKUP_OPTIONS="nfsvers=3,nolock"
USE_CFG2HTML=y
BACKUP_URL="nfs://XX.XX.XX.XX/export/images"
AUTOEXCLUDE_MULTIPATH=n
#
</pre>

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
Physical Machine HP Proliant

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86_64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
UEFI and GRUB

* Storage (lokal disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
local SSD 

* Description of the issue (ideally so that others can reproduce it):
Installed "rear" package on brand new CentOS 7 installtion.
<pre>
# rear -v mkrescue
Relax-and-Recover 2.00 / Git
Using log file: /var/log/rear/rear-XXXXXXXX.log
Using backup archive 'backup.tar.gz'
Using UEFI Boot Loader for Linux (USING_UEFI_BOOTLOADER=1)
Creating disk layout
ERROR:
====================
BUG in /usr/share/rear/layout/save/default/450_check_bootloader_files.sh:
'Unknown bootloader () - ask for sponsoring to get this fixed'
--------------------
Please report this issue at https://github.com/rear/rear/issues
and include the relevant parts from /var/log/rear/rear-XXXXXXXXX.log
preferably with full debug information via 'rear -d -D mkrescue'
====================
Aborting due to an error, check /var/log/rear/rear-XXXXXXXXX.log for details
Terminated
</pre>

* Work-around, if any:
NA

**Comment by jsmeix** [comment] 2018-10-15 11:02
ReaR version 2.00 is a bit old, from January 2017, cf.
http://relax-and-recover.org/documentation/release-notes-2-4

Some time ago there was an issue with ReaR 2.0 where guessing
the bootloader did not work on RHEL 7.3 with UEFI, see 
https://github.com/rear/rear/issues/1242
that lead to "Improved BOOTLOADER support" in ReaR 2.1, see
http://relax-and-recover.org/documentation/release-notes-2-4
and for details see https://github.com/rear/rear/pull/1262

With UEFI you may additionally need to specify config variables
like ISO_MKISOFS_BIN USING_UEFI_BOOTLOADER
UEFI_BOOTLOADER, see what the currrent usr/share/rear/conf/default.conf
https://raw.githubusercontent.com/rear/rear/master/usr/share/rear/conf/default.conf
reads that is related to `UEFI`.

Try out if a more current version works better for you, cf.
http://relax-and-recover.org/download/

See
http://relax-and-recover.org/documentation/release-notes-2-4
what has changed from ReaR 2.0 to the current ReaR 2.4.
There are some possibly backward incompatible changes.

I would also recommend to try out our current
ReaR upstream GitHub master code as follows:

Basically "git clone" it into a separated directory and then
configure and run ReaR from within that directory like:
<pre>
# git clone https://github.com/rear/rear.git

# mv rear rear.github.master

# cd rear.github.master

# vi etc/rear/local.conf

# usr/sbin/rear -D mkbackup
</pre>
Note the relative paths "etc/rear/" and "usr/sbin/".

I recommend to try out our current ReaR upstream GitHub master code
because that is the only place where we fix bugs - i.e. bugs in older
ReaR versions are not fixed by us (i.e. by ReaR upstream).

I don't know if your issue is a bug in ReaR, a missing feature in ReaR,
or if it is caused by inappropriate configuration settings by you.

If your issue is a bug or a missing feature in ReaR:

Bugs in older ReaR versions are not fixed by us (i.e. by ReaR upstream).
Missing features in older ReaR versions are not backported by us.

Bugs in older ReaR versions that got fixed in current ReaR upstream
GitHub master code might be fixed (provided the fix can be backported
with reasonable effort) by the Linux distributor wherefrom you got your
older ReaR version.

Missing features in older ReaR versions are usually not backported
by the Linux distributor wherefrom you got your older ReaR version.

If the issue also happens with current ReaR upstream GitHub master code
please provide us a complete ReaR debug log file of "rear -D mkrescue"
plus your initial/original disklayout.conf file from your original system
so that we can have a look how it behaves in your particular environment
cf. "Debugging issues with Relax-and-Recover" at
https://en.opensuse.org/SDB:Disaster_Recovery

If it works with current ReaR upstream GitHub master code
we would really appreciate an explicit positive feedback.

**Comment by jsmeix** [comment] 2018-10-18 08:18
Because "no news is good news", cf.
https://en.wikipedia.org/wiki/Talk%3AUnix_philosophy#No_news_is_good_news
I assume things work sufficiently with latest ReaR release 2.4
or with our current ReaR upstream GitHub master code.

**Closed by jsmeix** 2018-10-18 08:18 UTC
Labels: fixed/solved/done, support/question
