### ISSUE TITLE
rear package on ubuntu 14.04 depends on isolinux package (which does not exist)

### ISSUE THREAD

**Issue by gdha** [rear/rear#1403] opened 2017-07-06 09:19 UTC
* rear version (/usr/sbin/rear -V): 2.1
* OS version (cat /etc/rear/os.conf or lsb_release -a): ubuntu 14.04
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf): OUTPUT=ISO
* Are you using legacy BIOS or UEFI boot? BIOS
* Brief description of the issue:
````
# apt install rear
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 rear : Depends: isolinux but it is not installable
E: Unable to correct problems, you have held broken packages.
````
* Work-around, if any:
````
control:Depends: syslinux[!ppc64el], syslinux-common[!ppc64el], ethtool, ${shlibs:Depends}, lsb-release, xorriso, iproute, iputils-ping, isolinux, dosfstools, binutils, parted, openssl, gawk, attr, bc, ${misc:Depends}
````
should we remove **isolinux** from the **_control_** file as long as we support ubuntu14.04?

**Comment by gdha** [comment] 2017-07-06 09:33
Work-around to get it installed:
````
# apt-get download rear
# dpkg -i rear_2.1-0_amd64.deb 
Selecting previously unselected package rear.
(Reading database ... 39264 files and directories currently installed.)
Preparing to unpack rear_2.1-0_amd64.deb ...
Unpacking rear (2.1-0) ...
dpkg: dependency problems prevent configuration of rear:
 rear depends on ethtool; however:
  Package ethtool is not installed.
 rear depends on xorriso; however:
  Package xorriso is not installed.
 rear depends on iproute; however:
  Package iproute is not installed.
 rear depends on isolinux; however:
  Package isolinux is not installed.
 rear depends on gawk; however:
  Package gawk is not installed.

dpkg: error processing package rear (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Errors were encountered while processing:
 rear

# apt-get -f install

# dpkg  --ignore-depends isolinux -i rear_2.1-0_amd64.deb 
(Reading database ... 40706 files and directories currently installed.)
Preparing to unpack rear_2.1-0_amd64.deb ...
Unpacking rear (2.1-0) over (2.1-0) ...
Setting up rear (2.1-0) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
````

**Comment by schlomo** [comment] 2017-07-06 09:43
Maybe removing isolinux is an option, although on all other distros our agreement was IIRC that we want to include the dependencies to make the default config work.

Root cause is that Debian split the syslinux package without proving `Provides` for the old stuff.

I guess as long as we don't use different control files for different Debian versions we won't solve this problem. AFAIK there are no macros in control files that we could use to achieve a similar result to our spec file macros.

**Comment by gdha** [comment] 2017-07-06 15:16
If we add it to the FAQ page then we are fine I guess

**Comment by schlomo** [comment] 2017-07-06 15:38
Yes, and also to the description of the DEB package. We could also add both the new and the old name as `Recommends`. People doing `apt-get install` will actually see that.

**Comment by gdha** [comment] 2017-07-19 15:10
post-pone to release 2.3

**Comment by gdha** [comment] 2017-07-19 16:15
Added to the FAQ section in the release notes of v2.2

**Comment by gdha** [comment] 2017-11-17 15:28
@schlomo So your suggestion is that we remove `isolinux` and `xorriso` from the **Depends** line and move these two to the **Recommends** line?
And, furthermore, add some comments about it in the **Description** part of the _control_ file, right?

**Comment by schlomo** [comment] 2017-11-18 16:39
I think we can't provide a solution to this problem as long as we only build a single DEB for all Debian versions (or build from the same control file). So the "good" solution would be to expand our build tooling to have different control files - or parts of it - for different Debian version: New and old.

In the mean time we can add all the potential packages to **Recommends** to show the user that we would recommend to install those as well. Unresolvable Recommends shouldn't harm anybody.

And yes, removing the isolinux and xorriso packages from **Depends** will allow all Debian distros to install our ReaR package again.

As there is now a Debian maintainer who explicitly does not use our control file for his builds I think that this is the best we can do right now. In any case it only is relevant for those users building themselves or installing from OBS.

**Comment by jsmeix** [comment] 2017-11-28 12:27
I assume this issue is fixed via
https://github.com/rear/rear/pull/1599

**Closed by jsmeix** 2017-11-28 12:27 UTC
Labels: documentation, fixed/solved/done
