### ISSUE TITLE
ERROR: Partition mpath230 is numbered '\''230'\''. More than 128 partitions is not supported.

### ISSUE THREAD

**Issue by badarmontassar** [rear/rear#1766] opened 2018-04-03 17:08 UTC
Hello, 

I'm unable to backup my rhel 5 server with rear ..

here is the error message : 
<pre>
Trace 0: /usr/sbin/rear:504 main
Trace 1: /usr/share/rear/lib/mkrescue-workflow.sh:14 WORKFLOW_mkrescue
Trace 2: /usr/share/rear/lib/framework-functions.sh:85 SourceStage
Trace 3: /usr/share/rear/lib/framework-functions.sh:45 Source
Trace 4: /usr/share/rear/layout/save/GNU/Linux/280_multipath_layout.sh:24 source
Trace 5: /usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh:59 extract_partitions
Trace 6: /usr/share/rear/lib/layout-functions.sh:332 get_partition_number
Trace 7: /usr/share/rear/lib/_input-output-functions.sh:132 StopIfError
+++ echo 'Message: Partition mpath230 is numbered '\''230'\''. More than 128 partitions is not supported.'
Message: Partition mpath230 is numbered '230'. More than 128 partitions is not supported
</pre>

Here is the log with debug mode : 
<pre>
277063 ++ partition_name=/dev/mapper/mpath230
277064 ++ partition_name=mapper/mpath230
277065 ++ partition_name=mpath230
277066 +++ get_partition_number mpath230
277067 +++ local partition=mpath230
277068 ++++ echo mpath230
277069 ++++ grep -o -E '[0-9]+$'
277070 +++ local number=230
277071 +++ '[' 230 -gt 0 ']'
277072 +++ StopIfError 'Partition number '\''230'\'' of partition mpath230 is not a valid number.'
277073 +++ ((  0 != 0  ))
277074 +++ ((  230 <= 128  ))
277075 +++ StopIfError 'Partition mpath230 is numbered '\''230'\''. More than 128 partitions is not supported.'
277076 +++ ((  1 != 0  ))
277077 +++ Error 'Partition mpath230 is numbered '\''230'\''. More than 128 partitions is not supported.'
277078 +++ VERBOSE=1
277079 +++ LogPrint 'ERROR: Partition mpath230 is numbered '\''230'\''. More than 128 partitions is not supported.'
277080 +++ Log 'ERROR: Partition mpath230 is numbered '\''230'\''. More than 128 partitions is not supported.'
</pre>

The disk /dev/mapper/mpath230 don't have any partition !!! 
Any help please  ??

Rear version : Relax-and-Recover 2.00 / Git
Rhel version : 2.6.18-410.el5

Thanks in advance !

**Comment by jsmeix** [comment] 2018-04-04 08:16
Usually the "More than 128 partitions is not supported" errror message
and the place where that errors out has a root cause that is at some
earlier place with a differnt reason so that you need to inspect your
whole debug log to find out where things start to go wrong that finally
leads to that "More than 128 partitions is not supported" errror exit.

Relax-and-Recover 2.00 is relatively old.

Try out if a more current version works better for you, cf.
http://relax-and-recover.org/download/

I would also recommend to try out our current
ReaR upstream GitHub master code as follows:

Basically "git clone" it into a separated directory and then
configure and run ReaR from within that directory like:
<pre>
# git clone https://github.com/rear/rear.git

# mv rear rear.github.master

# cd rear.github.master

# vi etc/rear/local.conf

# usr/sbin/rear -D mkbackup
</pre>
Note the relative paths "etc/rear/" and "usr/sbin/".

I recommend to try out our current ReaR upstream GitHub master code
because that is the only place where we fix bugs - i.e. bugs in older
ReaR versions are not fixed by us (i.e. by ReaR upstream).
Bugs in older ReaR versions that got fixed in current ReaR upstream
GitHub master code might be fixed (if the fix can be backported)
by the Linux distributor wherefrom you got your older ReaR version.

**Comment by badarmontassar** [comment] 2018-04-04 13:07
I found the root cause, 
Rear is considering the device /dev/mapper/mpath230 as a partition of /dev/mapper/mpath23 device !!

I fix it with the following workaround :

In the function /usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh, I change the line : 

for path in ${device}p[0-9]* ${device}[0-9] ${device}-part* ${device}_part*; do
by
for path in ${device}p[0-9]* ${device}-part* ${device}_part*; do

**Comment by jsmeix** [comment] 2018-04-04 13:25
@badarmontassar 
FYI:
It seems the multipath related device naming is a horrible mess
where each Linux distribution and each distribution version
does it different so that what works here it breaks there, cf.
https://github.com/rear/rear/pull/1765

**Comment by jsmeix** [comment] 2018-04-04 13:37
@schabrolles 
on a first glance it seems only a trailing '*' in `${device}[0-9]` is missing
(i.e. as in the other bash globbing patterns)
to make it also match things like /dev/mapper/mpath230
because without a trailing '*' in `${device}[0-9]` I get
<pre>
 ( shopt -s nullglob extglob ; device="/tmp/foo" ; touch ${device}p1234 ; touch ${device}1234 ; touch ${device}-part1234 ; touch ${device}_part1234 ; for path in ${device}p[0-9]* ${device}[0-9] ${device}-part* ${device}_part*; do echo $path ; done )
/tmp/foop1234
/tmp/foo-part1234
/tmp/foo_part1234
</pre>
i.e. `/tmp/foo1234` is missing
versus with a trailing '*' in `${device}[0-9]*` I get
<pre>
( shopt -s nullglob extglob ; device="/tmp/foo" ; touch ${device}p1234 ; touch ${device}1234 ; touch ${device}-part1234 ; touch ${device}_part1234 ; for path in ${device}p[0-9]* ${device}[0-9]* ${device}-part* ${device}_part*; do echo $path ; done )
/tmp/foop1234
/tmp/foo1234
/tmp/foo-part1234
/tmp/foo_part1234
</pre>

**Comment by badarmontassar** [comment] 2018-04-04 14:33
@jsmeix : yes i have a device /dev/mapper/mpath230

# ls -lrt /dev/mapper/mpath230
 brw-rw---- 1 root disk 253, 147 Nov 11 13:40 /dev/mapper/mpath230

**Comment by jsmeix** [comment] 2018-04-05 13:28
@badarmontassar 
I am not at all a multipath user so that my above
https://github.com/rear/rear/issues/1766#issuecomment-378602550
is only a blind guess - nevertheless if you like you may try out
and report here if it also works for you when you have in
usr/share/rear/layout/save/GNU/Linux/200_partition_layout.sh
that line as follows:
<pre>
for path in ${device}p[0-9]* ${device}[0-9]* ${device}-part* ${device}_part*; do
</pre>
i.e. using `${device}[0-9]*` with a trailing `*` as in the other
bash globbing patterns in that line.

**Comment by badarmontassar** [comment] 2018-04-05 14:01
@jsmeix, 
It will not work,  I get the problem when rear is looking for mpath23 device partitions with the for loop,
If i add ${device}p[0-9]* , the device mpath230 will be in the list of mpath23 device partitions.

# device="/tmp/mpath23"; touch ${device}p230 ; touch ${device}0; touch ${device}-part230
#  for path in ${device}p[0-9]* ${device}[0-9]* ${device}-part* ; do echo $path ; done
/tmp/mpath23p230
/tmp/mpath230
/tmp/mpath23-part230

**Comment by jsmeix** [comment] 2018-04-05 14:09
O.k. I will leave this issue to @schabrolles 
because he knows at least 100-times more about multipath than I do.

**Comment by schabrolles** [comment] 2018-04-07 18:13
@jsmeix 
I think I find a better way to get the multipath partition device name... (at least on rhel7). I need more time and testing to check if it works for other distro and version.

@badarmontassar,
I don't have a rhel5 , so it is a bit difficult for me to validate if it will work for you.

Could you please send me the output of the following commands:
```
[root@rear-rhel-142 /]# ls -l /dev/mapper/
total 0
lrwxrwxrwx 1 root root       7 Apr  7 19:58 3600507680c82004cf8000000000000d8 -> ../dm-0
lrwxrwxrwx 1 root root       7 Apr  7 18:47 3600507680c82004cf8000000000000d8p1 -> ../dm-1
lrwxrwxrwx 1 root root       7 Apr  7 18:47 3600507680c82004cf8000000000000d8p2 -> ../dm-2
lrwxrwxrwx 1 root root       7 Apr  7 18:47 3600507680c82004cf8000000000000d8p3 -> ../dm-3
crw------- 1 root root 10, 236 Apr  7 18:37 control
lrwxrwxrwx 1 root root       7 Apr  7 18:47 rhel_rhel73-root -> ../dm-4
lrwxrwxrwx 1 root root       7 Apr  7 18:47 rhel_rhel73-swap -> ../dm-5
```
On my system,  `/dev/dm-0` is a real disk with partitions
```
[root@rear-rhel-142 /]# ls -l /sys/block/dm-0/holders
total 0
lrwxrwxrwx 1 root root 0 Apr  7 18:47 dm-1 -> ../../dm-1
lrwxrwxrwx 1 root root 0 Apr  7 18:47 dm-2 -> ../../dm-2
lrwxrwxrwx 1 root root 0 Apr  7 18:47 dm-3 -> ../../dm-3
```
`ls -l /sys/block/dm-0/holders` lists the devices that are partition of the current device `dm-0`.

I would need you to do the ame on your rhel5 with a multipath device that have partitions (if you have some.)

**Comment by badarmontassar** [comment] 2018-04-12 06:58
[
[multipath.txt](https://github.com/rear/rear/files/1901664/multipath.txt)
](url)
@schabrolles 
You find attached the output of needed command.
Sorry I don't have a multipath device with partitions.

**Comment by schabrolles** [comment] 2018-04-12 08:45
@badarmontassar 

If you have `sosreport`command, could you please run it and send me the tar file. It will gather some information from your system. I will then being able to have a look at it to see if there is diffenrence between your rhel5 and the rhel6 or 7 I use.

- I typically need to understand how rhel5 is managing multi path device (it seems that it does not use dm device but create directly /dev/mapper/mpathXXX as block device.) 
 - I need to have a full view of your /sys filesystem .... I could be able to check how the information about block device are stored by your rhel5.

**Comment by badarmontassar** [comment] 2018-04-18 10:37
@schabrolles : sorry for the delay 
sorry, I can't send you an sosreport. Below the output of needed commands : 

[dm.txt](https://github.com/rear/rear/files/1923570/dm.txt)
# ls -ltr /sys/block/mpath*
ls: /sys/block/mpath*: No such file or directory

Regards,

**Comment by badarmontassar** [comment] 2018-04-25 14:28
@schabrolles : with the new version i got another issue with a logical volume 
Relax-and-Recover 2.00 / Git
...
Using backup archive 'backup.tar.gz'
Creating disk layout
ERROR: Partition number '00' of partition treflArchVG-treflArchLV00 is not a valid number.
... 
# ls -ltr /dev/mapper/
brw-rw---- 1 root disk 253,  11 Nov 11 13:40 mpath20
brw-rw---- 1 root disk 253,  12 Nov 11 13:40 mpath22
brw-rw---- 1 root disk 253,  13 Nov 11 13:40 mpath21
brw-rw---- 1 root disk 253,  14 Nov 11 13:40 mpath23
brw-rw---- 1 root disk 253,  16 Nov 11 13:40 mpath25
brw-rw---- 1 root disk 253,  15 Nov 11 13:40 mpath24
brw-rw---- 1 root disk 253,  17 Nov 11 13:40 mpath26
brw-rw---- 1 root disk 253,  18 Nov 11 13:40 mpath27
brw-rw---- 1 root disk 253,  19 Nov 11 13:40 mpath28
brw-rw---- 1 root disk 253,  20 Nov 11 13:40 mpath29
brw-rw---- 1 root disk 253,  21 Nov 11 13:40 mpath0
brw-rw---- 1 root disk 253,  22 Nov 11 13:40 mpath2
brw-rw---- 1 root disk 253,  23 Nov 11 13:40 mpath1
brw-rw---- 1 root disk 253,  24 Nov 11 13:40 mpath3
brw-rw---- 1 root disk 253,  25 Nov 11 13:40 mpath4
brw-rw---- 1 root disk 253,  26 Nov 11 13:40 mpath177
brw-rw---- 1 root disk 253,  27 Nov 11 13:40 mpath5
brw-rw---- 1 root disk 253,  28 Nov 11 13:40 mpath6
brw-rw---- 1 root disk 253,  29 Nov 11 13:40 mpath7
brw-rw---- 1 root disk 253,  30 Nov 11 13:40 mpath8
brw-rw---- 1 root disk 253,  31 Nov 11 13:40 mpath9
brw-rw---- 1 root disk 253,  32 Nov 11 13:40 mpath10
brw-rw---- 1 root disk 253,  33 Nov 11 13:40 mpath11
brw-rw---- 1 root disk 253,  34 Nov 11 13:40 mpath14
brw-rw---- 1 root disk 253,  35 Nov 11 13:40 mpath16
brw-rw---- 1 root disk 253,  36 Nov 11 13:40 mpath17
brw-rw---- 1 root disk 253,  37 Nov 11 13:40 mpath18
brw-rw---- 1 root disk 253,  38 Nov 11 13:40 mpath31
brw-rw---- 1 root disk 253,  39 Nov 11 13:40 mpath32
brw-rw---- 1 root disk 253,  40 Nov 11 13:40 mpath178
brw-rw---- 1 root disk 253,  41 Nov 11 13:40 mpath33
brw-rw---- 1 root disk 253,  42 Nov 11 13:40 mpath34
brw-rw---- 1 root disk 253,  43 Nov 11 13:40 mpath35
brw-rw---- 1 root disk 253,  44 Nov 11 13:40 mpath36
brw-rw---- 1 root disk 253,  45 Nov 11 13:40 mpath37
brw-rw---- 1 root disk 253,  46 Nov 11 13:40 mpath38
brw-rw---- 1 root disk 253,  47 Nov 11 13:40 mpath39
brw-rw---- 1 root disk 253,  48 Nov 11 13:40 mpath40
brw-rw---- 1 root disk 253,  49 Nov 11 13:40 mpath41
brw-rw---- 1 root disk 253,  50 Nov 11 13:40 mpath42
brw-rw---- 1 root disk 253,  51 Nov 11 13:40 mpath43
brw-rw---- 1 root disk 253,  52 Nov 11 13:40 mpath44
brw-rw---- 1 root disk 253,  53 Nov 11 13:40 mpath45
brw-rw---- 1 root disk 253,  54 Nov 11 13:40 mpath179
brw-rw---- 1 root disk 253,  55 Nov 11 13:40 mpath46
brw-rw---- 1 root disk 253,  56 Nov 11 13:40 mpath47
brw-rw---- 1 root disk 253,  57 Nov 11 13:40 mpath48
brw-rw---- 1 root disk 253,  58 Nov 11 13:40 mpath49
brw-rw---- 1 root disk 253,  59 Nov 11 13:40 mpath50
brw-rw---- 1 root disk 253,  60 Nov 11 13:40 mpath51
brw-rw---- 1 root disk 253,  61 Nov 11 13:40 mpath52
brw-rw---- 1 root disk 253,  62 Nov 11 13:40 mpath53
brw-rw---- 1 root disk 253,  63 Nov 11 13:40 mpath54
brw-rw---- 1 root disk 253,  64 Nov 11 13:40 mpath143
brw-rw---- 1 root disk 253,  65 Nov 11 13:40 mpath144
brw-rw---- 1 root disk 253,  66 Nov 11 13:40 mpath145
brw-rw---- 1 root disk 253,  67 Nov 11 13:40 mpath146
brw-rw---- 1 root disk 253,  68 Nov 11 13:40 mpath180
brw-rw---- 1 root disk 253,  69 Nov 11 13:40 mpath147
brw-rw---- 1 root disk 253,  70 Nov 11 13:40 mpath148
brw-rw---- 1 root disk 253,  71 Nov 11 13:40 mpath149
brw-rw---- 1 root disk 253,  72 Nov 11 13:40 mpath150
brw-rw---- 1 root disk 253,  73 Nov 11 13:40 mpath151
brw-rw---- 1 root disk 253,  74 Nov 11 13:40 mpath152
brw-rw---- 1 root disk 253,  75 Nov 11 13:40 mpath153
brw-rw---- 1 root disk 253,  76 Nov 11 13:40 mpath154
brw-rw---- 1 root disk 253,  77 Nov 11 13:40 mpath155
brw-rw---- 1 root disk 253,  78 Nov 11 13:40 mpath156
brw-rw---- 1 root disk 253,  79 Nov 11 13:40 mpath157
brw-rw---- 1 root disk 253,  81 Nov 11 13:40 mpath159
brw-rw---- 1 root disk 253,  80 Nov 11 13:40 mpath158
brw-rw---- 1 root disk 253,  82 Nov 11 13:40 mpath181
brw-rw---- 1 root disk 253,  83 Nov 11 13:40 mpath160
brw-rw---- 1 root disk 253,  84 Nov 11 13:40 mpath161
brw-rw---- 1 root disk 253,  85 Nov 11 13:40 mpath162
brw-rw---- 1 root disk 253,  86 Nov 11 13:40 mpath163
brw-rw---- 1 root disk 253,  87 Nov 11 13:40 mpath164
brw-rw---- 1 root disk 253,  88 Nov 11 13:40 mpath165
brw-rw---- 1 root disk 253,  89 Nov 11 13:40 mpath166
brw-rw---- 1 root disk 253,  90 Nov 11 13:40 mpath167
brw-rw---- 1 root disk 253,  91 Nov 11 13:40 mpath168
brw-rw---- 1 root disk 253,  92 Nov 11 13:40 mpath169
brw-rw---- 1 root disk 253,  93 Nov 11 13:40 mpath170
brw-rw---- 1 root disk 253,  94 Nov 11 13:40 mpath171
brw-rw---- 1 root disk 253,  95 Nov 11 13:40 mpath172
brw-rw---- 1 root disk 253,  96 Nov 11 13:40 mpath182
brw-rw---- 1 root disk 253,  97 Nov 11 13:40 mpath176
brw-rw---- 1 root disk 253,  98 Nov 11 13:40 mpath173
brw-rw---- 1 root disk 253,  99 Nov 11 13:40 mpath174
brw-rw---- 1 root disk 253, 100 Nov 11 13:40 mpath175
brw-rw---- 1 root disk 253, 101 Nov 11 13:40 mpath187
brw-rw---- 1 root disk 253, 102 Nov 11 13:40 mpath188
brw-rw---- 1 root disk 253, 103 Nov 11 13:40 mpath189
brw-rw---- 1 root disk 253, 104 Nov 11 13:40 mpath190
brw-rw---- 1 root disk 253, 105 Nov 11 13:40 mpath191
brw-rw---- 1 root disk 253, 106 Nov 11 13:40 mpath192
brw-rw---- 1 root disk 253, 107 Nov 11 13:40 mpath193
brw-rw---- 1 root disk 253, 108 Nov 11 13:40 mpath194
brw-rw---- 1 root disk 253, 109 Nov 11 13:40 mpath195
brw-rw---- 1 root disk 253, 110 Nov 11 13:40 mpath183
brw-rw---- 1 root disk 253, 111 Nov 11 13:40 mpath196
brw-rw---- 1 root disk 253, 112 Nov 11 13:40 mpath197
brw-rw---- 1 root disk 253, 113 Nov 11 13:40 mpath198
brw-rw---- 1 root disk 253, 114 Nov 11 13:40 mpath199
brw-rw---- 1 root disk 253, 115 Nov 11 13:40 mpath200
brw-rw---- 1 root disk 253, 116 Nov 11 13:40 mpath201
brw-rw---- 1 root disk 253, 117 Nov 11 13:40 mpath202
brw-rw---- 1 root disk 253, 118 Nov 11 13:40 mpath203
brw-rw---- 1 root disk 253, 119 Nov 11 13:40 mpath204
brw-rw---- 1 root disk 253, 120 Nov 11 13:40 mpath205
brw-rw---- 1 root disk 253, 121 Nov 11 13:40 mpath206
brw-rw---- 1 root disk 253, 122 Nov 11 13:40 mpath207
brw-rw---- 1 root disk 253, 123 Nov 11 13:40 mpath208
brw-rw---- 1 root disk 253, 124 Nov 11 13:40 mpath184
brw-rw---- 1 root disk 253, 125 Nov 11 13:40 mpath209
brw-rw---- 1 root disk 253, 126 Nov 11 13:40 mpath210
brw-rw---- 1 root disk 253, 127 Nov 11 13:40 mpath211
brw-rw---- 1 root disk 253, 128 Nov 11 13:40 mpath212
brw-rw---- 1 root disk 253, 129 Nov 11 13:40 mpath213
brw-rw---- 1 root disk 253, 130 Nov 11 13:40 mpath214
brw-rw---- 1 root disk 253, 131 Nov 11 13:40 mpath215
brw-rw---- 1 root disk 253, 132 Nov 11 13:40 mpath216
brw-rw---- 1 root disk 253, 133 Nov 11 13:40 mpath217
brw-rw---- 1 root disk 253, 134 Nov 11 13:40 mpath218
brw-rw---- 1 root disk 253, 135 Nov 11 13:40 mpath219
brw-rw---- 1 root disk 253, 136 Nov 11 13:40 mpath220
brw-rw---- 1 root disk 253, 137 Nov 11 13:40 mpath185
brw-rw---- 1 root disk 253, 138 Nov 11 13:40 mpath221
brw-rw---- 1 root disk 253, 139 Nov 11 13:40 mpath222
brw-rw---- 1 root disk 253, 140 Nov 11 13:40 mpath223
brw-rw---- 1 root disk 253, 141 Nov 11 13:40 mpath224
brw-rw---- 1 root disk 253, 142 Nov 11 13:40 mpath225
brw-rw---- 1 root disk 253, 143 Nov 11 13:40 mpath226
brw-rw---- 1 root disk 253, 144 Nov 11 13:40 mpath227
brw-rw---- 1 root disk 253, 145 Nov 11 13:40 mpath228
brw-rw---- 1 root disk 253, 146 Nov 11 13:40 mpath229
brw-rw---- 1 root disk 253, 147 Nov 11 13:40 mpath230
brw-rw---- 1 root disk 253, 148 Nov 11 13:40 mpath231
brw-rw---- 1 root disk 253, 149 Nov 11 13:40 mpath232
brw-rw---- 1 root disk 253, 150 Nov 11 13:40 mpath233
brw-rw---- 1 root disk 253, 151 Nov 11 13:40 mpath243
brw-rw---- 1 root disk 253, 152 Nov 11 13:40 mpath186
brw-rw---- 1 root disk 253, 153 Nov 11 13:40 mpath234
brw-rw---- 1 root disk 253, 154 Nov 11 13:40 mpath244
brw-rw---- 1 root disk 253, 155 Nov 11 13:40 mpath235
brw-rw---- 1 root disk 253, 156 Nov 11 13:40 mpath236
brw-rw---- 1 root disk 253, 157 Nov 11 13:40 mpath237
brw-rw---- 1 root disk 253, 158 Nov 11 13:40 mpath238
brw-rw---- 1 root disk 253, 159 Nov 11 13:40 mpath239
brw-rw---- 1 root disk 253, 160 Nov 11 13:40 mpath240
brw-rw---- 1 root disk 253, 161 Nov 11 13:40 mpath241
brw-rw---- 1 root disk 253, 162 Nov 11 13:40 mpath242
brw-rw---- 1 root disk 253, 163 Nov 11 13:40 mpath12
brw-rw---- 1 root disk 253, 165 Nov 11 13:40 mpath15
brw-rw---- 1 root disk 253, 166 Nov 11 13:40 mpath19
....
....
brw-rw---- 1 root disk 253, 171 Nov 11 13:40 treflArchVG-treflArchLV00
.....
crw------- 1 root root  10,  60 Nov 11 14:40 control
brw-rw---- 1 root disk 253, 164 Mar 16 12:55 mpath13

**Comment by schabrolles** [comment] 2018-04-25 15:28
What is your architecture ? x86_64 ?

**Comment by badarmontassar** [comment] 2018-04-25 15:46
# uname -a
Linux 2.6.18-410.el5 #1 SMP Fri Apr 8 05:48:52 EDT 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by schabrolles** [comment] 2018-04-25 15:54
Here it is  
[rear-2.3-1.git.2941.c635fd9d.issue1766.fc27.x86_64.zip](https://github.com/rear/rear/files/1947819/rear-2.3-1.git.2941.c635fd9d.issue1766.fc27.x86_64.zip)

**Comment by badarmontassar** [comment] 2018-05-03 13:38
I couldn't install the rpm due a dependency with the package genisoimage which is not available on rhel5. 
In rear 2.0 for rhel 5 has a dependency with mkisofs not genisoimage.
Could you please send me an rpm for rhel5 ?

**Comment by jsmeix** [comment] 2018-05-03 14:06
@badarmontassar 
what is your problem with using our current ReaR upstream
GitHub master code directly as I described in
https://github.com/rear/rear/issues/1766#issuecomment-378519043

I mean let us make specific RPMs for your specific system somewhat exceeds
what we usually do as free (often voluntary) support by ReaR upstream.
This support here by ReaR upstream is not any kind of official support
for your particular Linux distribution or any kind of enterprise suport for
business customers that you would get only directly from your particular
vendor of you particular enterprise Linux distribution.
This support here by ReaR upstream is basically meant as a cooperation
between ReaR users and the ReaR upstream authors where the primary
intent is to further develop ReaR but not to provide professional support.
Regarding professional support you may also have a look at
http://relax-and-recover.org/support/

**Comment by schabrolles** [comment] 2018-05-03 15:06
@badarmontassar,
Unfortunately, I don't have any rhel5 to build your rpm. 
As @jsmeix  suggest, you can use the git master branch to get the code.
if you prefer using rpm, here is the procedure to build the rpm from the source code.

```
it clone https://github.com/schabrolles/rear -b issue_1766
cd rear
make rpm
```
the rpms created should be in `dists` directory.

**Comment by schabrolles** [comment] 2018-05-03 15:42
@badarmontassar,

The patch I propose is only located in my private github repo https://github.com/schabrolles/rear because I cannot verify if it works on rhel5. If you can test it and confirm it works I will push it in the official rear repo.

**Comment by schabrolles** [comment] 2018-05-09 14:47
@badarmontassar 
Just a quick question. Did you use **Storix Software** on this server before switching to rear?

**Comment by badarmontassar** [comment] 2018-05-09 14:51
@schabrolles 
No, i didn't use  Storix Software.

**Comment by gdha** [comment] 2018-05-30 08:14
@badarmontassar @schabrolles How far are we with testing this PR of Sebastien? Do you still want this in ReaR 2.4 or can it wait for 2.5?

**Comment by schabrolles** [comment] 2018-05-30 08:47
@gdha it is more an issue here than a PR. All the PR related to this issue are already merged into master brnach because they solved other issues.
The main problem here is how a RHEL5  is managing and create multipath devices. : create a real /dev/mpath#devicenumber#part_number.
Because of that it is difficult to know if /dev/mpath231 is a device or the first partition of device /dev/mpath23 ... 

As I don't have a rhel5, it will be hard to quickly find a solution for that issue. (postpone to 2.5)

**Comment by gdha** [comment] 2019-03-27 17:34
@schabrolles what shall we do with this issue? Close it for now?

**Comment by gdha** [comment] 2019-04-17 10:11
@schabrolles Are we OK to post-pone this issue to rear-2.6?

**Comment by schabrolles** [comment] 2019-04-17 12:10
@gdha, 
I'm Ok as I don't have time to look at it... it is also a problem related to rhel5 (there is no problem with rhel6 and above).

**Comment by gdha** [comment] 2019-04-17 13:19
moved the milestone from 2.5 to 2.6

**Comment by jsmeix** [comment] 2019-04-23 12:57
@schabrolles 
only FYI an offhanded idea that there might be a general problem with the
extract_partitions() function in layout/save/GNU/Linux/200_partition_layout.sh

We had a similar kind of issue
https://github.com/rear/rear/issues/2087
where the extract_partitions() function failed to determine
partitions correctly, see in particular my conclusion in
https://github.com/rear/rear/issues/2087#issuecomment-477551079

My basic idea is to let `lsblk` determine what `TYPE` a block device is
instead of our current block device name pattern matching attempts, cf.
https://github.com/rear/rear/issues/2087#issuecomment-480173977

According to the initial description
https://github.com/rear/rear/issues/1766#issue-310921361
```
... +++ get_partition_number mpath230

The disk /dev/mapper/mpath230 don't have any partition
```
also in this case here the extract_partitions() function wrongly
recognized the `disk` type block device /dev/mapper/mpath230
as if it was a `part` type block device.

@badarmontassar 
to see whether or not the `lsblk` output could also be used in your case
I would like that you provide us with the full output of a command like
```
lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,SIZE,MOUNTPOINT
```

Because you have RHEL 5 which is rather old, its 'lsblk' command
may not support all those columns that I specified above so that
you may have to use a bit different `lsblk` command, e.g. call
`lsblk --help` to see the available options and columns.

I do not run RHEL but on my SLES11 system that is also rather old
`lsblk --help` shows neither `PKNAME  internal parent kernel device name`
nor `TYPE  device type` so that on SLES11 the `lsblk` output is useless
to determine what `TYPE` a block device is.

Perhaps on RHEL 5 the `lsblk` output can be used
to determine what `TYPE` a block device is?

**Comment by schabrolles** [comment] 2019-04-23 15:29
@jsmeix 
I really like `lsblk` ... It can realy be useful to use it for rear... My only problem is that it is not included in 
the older distro like rhel5. 

Here is an extract from redhat website:  https://access.redhat.com/solutions/2063833
```
The lsblk command is provided by the util-linux package which is not available on RHEL 5 through the Red Hat repositories. 
```

**Comment by jsmeix** [comment] 2019-04-24 10:18
So using `lsblk` to determine what `TYPE` a block device is
is for ReaR 3.0 via https://github.com/rear/rear/issues/1390
where we can drop support for too old Linux distributions.

For this specific issue here the user's system-specific workaround
https://github.com/rear/rear/issues/1766#issuecomment-378593308
is probably the most reasonable way in current ReaR because
ReaR is meant to be adapted or extended by the admin
to make things work for specific cases.

By the way:
This is the ultimate reason why ReaR is written entirely in the
native language for system administration: as bash scripts, cf.
"Disaster recovery with Relax-and-Recover (ReaR)" in
https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by jsmeix** [comment] 2019-04-26 09:52
Only as a side note FYI how `lsblk` could be useful in another case see
https://github.com/rear/rear/issues/2036#issuecomment-463170130
where `lsblk` reports that `TYPE` is `crypt` for encrypted block devices
(at least for block devices that are encrypted with eCryptfs).

**Comment by gdha** [comment] 2020-05-27 07:59
@schabrolles is RHEL 5 still supported by RedHat?

**Comment by schabrolles** [comment] 2020-05-27 11:58
@gdha I would say no ... but https://access.redhat.com/support/policy/updates/errata says it will be definitely END of extended support by the end of the year.


Version | General Availability | End of Full Support | End of Maintenance Support 1 | End of Maintenance Support or Maintenance Support 2 (Product retirement) | End of Extended Life-cycle Support | End of Extended Life Phase | LastMinorRelease
-- | -- | -- | -- | -- | -- | -- | --
4 | February 14, 2005 | March 31, 2009 | February 16, 2011 | February 29, 2012 | March 31, 2017 | Ongoing | 4.9
5 | March 15, 2007 | January 8, 2013 | January 31, 2014 | March 31, 2017 | November 30, 2020 | Ongoing | 5.11
6 | November 10, 2010 | May 10, 2016 | May 10, 2017 | November 30, 2020 | June 30, 2024 | Ongoing | 6.10
7 | June 10, 2014 | August 6, 2019 | August 6, 2020 | June 30, 2024 | TBD | Ongoing | 7.9
7 (ARM) | November 13, 2017 | November 30, 2020 | N/A | N/A | N/A | Ongoing | 7.6
7 (POWER9) | November 13, 2017 | May 31, 2021 | N/A | N/A | N/A | Ongoing | 7.6
7 (System z (Structure A)) | April 10, 2018 | May 31, 2021 | N/A | N/A | N/A | Ongoing | 7.6

**Comment by gdha** [comment] 2020-05-27 12:07
@schabrolles  Thank you for the quick response. 
@jsmeix Wouldn't it be better to remove RHEL 5 from ReaR support matrix for version 2.6?

**Comment by jsmeix** [comment] 2020-05-27 13:36
Yes, better remove old and no longer well tested distributions
from our list of official supported Linux based operating systems.

Via
https://github.com/rear/rear.github.com/commit/f191b3feb2134557bdfa0d746fbdf82b5c494c74
I adapted the "Supported and Unsupported Operating Systems"
and "Supported and Unsupported Architectures" for ReaR 2.6
in the "Release Notes for Relax-and-Recover version 2.6".

By the way:
I think RHEL 8 must be added there?

**Comment by gdha** [comment] 2020-05-27 13:40
@jsmeix indeed RHEL 8 and CentOS 8 should be added. Thanks for the remark - good catch

**Comment by jsmeix** [comment] 2020-05-27 13:47
Via
https://github.com/rear/rear.github.com/commit/2749468fb6c12e94d1bf83e68e8fbef58a228989
I  added RHEL 8 and CentOS 8 as supported operating systems.

What about newest Fedora 30 31 32 ... according to
https://en.wikipedia.org/wiki/Fedora_(operating_system)#History

And what about other newest distributions like ScientificLinux,
Debian, Ubuntu, whatnot...?

**Comment by gdha** [comment] 2020-05-27 13:55
@jsmeix perhaps we should not use this issue for further discussions on what is supported or not, but better use issue #2368 instead.

**Comment by gdha** [comment] 2020-05-28 14:19
Removing the milestone from the issue report.

**Closed** 2020-08-04 01:34 UTC
Labels: bug, no-issue-activity
