### ISSUE TITLE
When OUTPUT_URL is set OUTPUT_OPTIONS does not inherit BACKUP_OPTIONS

### ISSUE THREAD

**Issue by exfarmer** [rear/rear#2753] opened 2022-02-03 23:53 UTC
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
Relax-and-Recover 2.6 / 2020-06-17

* OS version ("cat /etc/os-release" or "lsb_release -a" or "cat /etc/rear/os.conf"):
Red Hat Enterprise Linux Server release 6.10 (Santiago)

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
```
OUTPUT=ISO
OUTPUT_URL=nfs://ussydd6300/data/col1/sylmar_linux_bu_image
BACKUP=NETFS
BACKUP_OPTIONS="nfsvers=3,nolock"
BACKUP_URL=nfs://ussydd6300/data/col1/sylmar_linux_bu_image
ONLY_INCLUDE_VG=( 'VolGroup00' 'vg01' )
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media' '/var/tmp' '/var/crash' '/srv')
NETFS_KEEP_OLD_BACKUP_COPY=y
```

* Hardware vendor/product (PC or PowerNV BareMetal or ARM) or VM (KVM guest or PowerVM LPAR):
VMWare

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
x86_64

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot): 

* Storage (local disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
SAN

* Storage layout ("lsblk -ipo NAME,KNAME,PKNAME,TRAN,TYPE,FSTYPE,LABEL,SIZE,MOUNTPOINT"): 

* Description of the issue (ideally so that others can reproduce it):
BACKUP_OPTIONS defined in local.conf are not being used

* Workaround, if any:
Hardcode values in /usr/share/rear/conf/default.conf

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files): 

[rear-ussy-messtgora20.log](https://github.com/rear/rear/files/7999022/rear-ussy-messtgora20.log)

**Comment by jsmeix** [comment] 2022-02-04 09:48
https://github.com/rear/rear/files/7999022/rear-ussy-messtgora20.log
contains (excerpts):
```
2022-02-03 13:23:03.263559160 Including prep/NETFS/default/060_mount_NETFS_path.sh
mkdir: created directory `/tmp/rear.XOaHbxxa0dHb2MK/outputfs'
2022-02-03 13:23:03.288418377 Added 'rmdir -v /tmp/rear.XOaHbxxa0dHb2MK/outputfs >&2' as an exit task
2022-02-03 13:23:03.324917225 Mounting with 'mount -v -t nfs -o nfsvers=3,nolock ussydd6300:/data/col1/sylmar_linux_bu_image /tmp/rear.XOaHbxxa0dHb2MK/outputfs'
mount.nfs: trying 10.94.101.36 prog 100003 vers 3 prot TCP port 2049
mount.nfs: trying 10.94.101.36 prog 100005 vers 3 prot UDP port 2052
mount.nfs: timeout set for Thu Feb  3 13:25:03 2022
mount.nfs: trying text-based options 'nfsvers=3,nolock,addr=10.94.101.36'
mount.nfs: prog 100003, trying vers=3, prot=6
mount.nfs: prog 100005, trying vers=3, prot=17
ussydd6300:/data/col1/sylmar_linux_bu_image on /tmp/rear.XOaHbxxa0dHb2MK/outputfs type nfs (rw,nfsvers=3,nolock)
```

**Comment by jsmeix** [comment] 2022-02-04 10:04
In current GitHub master code we have in
usr/share/rear/prep/NETFS/default/060_mount_NETFS_path.sh
which is a symlink to
../../../backup/NETFS/default/100_mount_NETFS_path.sh
```
mount_url $BACKUP_URL $BUILD_DIR/outputfs $BACKUP_OPTIONS
```
while in
usr/share/rear/output/default/100_mount_output_path.sh
we have
```
mount_url $OUTPUT_URL $BUILD_DIR/outputfs $OUTPUT_OPTIONS
```
i.e. BACKUP_OPTIONS vs. OUTPUT_OPTIONS.

I think I vaguely remember from another issue that
when OUTPUT_URL is set then the right OUTPUT_OPTIONS must be set
but when only BACKUP_URL is set then OUTPUT_URL and OUTPUT_OPTIONS
inherit their values from BACKUP_URL and BACKUP_OPTIONS,
via the code in usr/share/rear/prep/default/020_translate_url.sh

@exfarmer 
accordingly either specify
```
OUTPUT_URL=nfs://ussydd6300/data/col1/sylmar_linux_bu_image
OUTPUT_OPTIONS="nfsvers=3,nolock"
...
BACKUP_URL=nfs://ussydd6300/data/col1/sylmar_linux_bu_image
BACKUP_OPTIONS="nfsvers=3,nolock"
```
or - because both are same - only specify
```
BACKUP_URL=nfs://ussydd6300/data/col1/sylmar_linux_bu_image
BACKUP_OPTIONS="nfsvers=3,nolock"
```

**Comment by jsmeix** [comment] 2022-02-04 10:24
The issue is missing documentation which should now be fixed via
https://github.com/rear/rear/commit/87d36f304ca4301bc1cfce55084b83260839695a

**Closed by jsmeix** 2022-02-04 10:24 UTC
Labels: documentation, support / question, fixed / solved / done

**Comment by exfarmer** [comment] 2022-02-04 14:03
Hi,

I must of missed this in the documentation, I have removed the OUTPUT_URL from the local configuration file and now only specify BACKUP_URL and BACKUP_OPTIONS.
This worked.

You can close the case.
Thank you

Abbott
[image001]
Gary Hess
Administrator, Sr - Unix
Abbott

253 Financial Blvd.
Liberty, SC 29657  USA

O:
+1 864-843-8352
M:
+1 864-546-8921
E:
***@***.***
