### ISSUE TITLE
Problems with Toshiba USB flash driveUSB. Seems to format, but then won't boot or mount but is recognised by OS

### ISSUE THREAD

**Issue by ipcctv** [rear/rear#1260] opened 2017-03-22 17:40 UTC
Centos 7 minimal OS. ReaR format seems to work when looking at it's log and the console output. As does mkrecover. However, the drive is not bootable and also, its not mountable.

The ReaR log issues a warning about alignment and performance, but no errors. It does label the device as REAR-000. I see this when I insert the device into a different machine. It must have been writable. I don't see any data though?
It sets a maximal mount count to -1 ? and continues to finish after 306 seconds.

Attempting to mount the device as ext3 or 4 fails/
I've noted in the syslog output it refers to ext4 though the dialog says 
Type exactly 'Yes' to format /dev/sdb with ext3 filesystem:

/var/log/rear/rear-<machinename>.log attached.
[REAR_log.txt](https://github.com/rear/rear/files/862318/REAR_log.txt)

I see it says it's writing a master boot record of type msdos to /dev/sdb.

Any help greatly appreciated.

**Comment by gozora** [comment] 2017-03-22 17:52
Hi @ipcctv,

1. try to fill issue template, it helps when (at least) I try to reproduce issues ...
2. try to run `rear mkbackup` and test if booting works (I have a dim feeling that you need to run `rear mkbackup` at least once when launching ReaR for first time after `rear format`)

V.

**Comment by ipcctv** [comment] 2017-03-23 10:03
Hi Gozora.  I thought I had and attached them - sorry.   Er the more than excellent news is that I've done the mkbackup and then a recovery. All seems fine, so thank you very much for that and the quick response.  My remaining issue seems to be when I try to mount it on my HP system, it will not have it.  It says it's mounting as read/only, being write protected and says it has a file system type of null.

What I did was to make a subdirectory off /mnt called usbtest and then typed variout things like
mount -t ext3 /dev/sdb /mnt/usbtest  and same with -t ext4 and also no option to the -t.  All the above but as follows  mount -t /dev/sdb /mnt

What confuses me also is that putting the usb stick into a laptop seems fine.     Whatever the outcome, thanks and I'm further along!!

Tom/

**Comment by ipcctv** [comment] 2017-03-23 10:12
As per previous post, I also tried the -t ext4 and no option to the -t.
The error when trying to mount is
---
[root@btpevtlk01 sbin]# mount -t ext3 /dev/sdb /mnt
mount: wrong fs type, bad option, bad superblock on /dev/sdb,
       missing codepage or helper program, or other error
----
and the dmesg output is
----
[ 4216.011005] scsi 2:0:0:0: Direct-Access     TOSHIBA  USB FLASH DRIVE  PMAP PQ                : 0 ANSI: 6
[ 4216.011359] sd 2:0:0:0: Attached scsi generic sg2 type 0
[ 4216.012157] sd 2:0:0:0: [sdb] 30240768 512-byte logical blocks: (15.4 GB/14.4                 GiB)
[ 4216.012994] sd 2:0:0:0: [sdb] Write Protect is off
[ 4216.013001] sd 2:0:0:0: [sdb] Mode Sense: 45 00 00 00
[ 4216.013647] sd 2:0:0:0: [sdb] Write cache: disabled, read cache: enabled, doe                sn't support DPO or FUA
[ 4216.142243]  sdb: sdb1
[ 4216.146097] sd 2:0:0:0: [sdb] Attached SCSI removable disk
[ 4428.466647] EXT4-fs (sdb): VFS: Can't find ext4 filesystem

**Comment by jsmeix** [comment] 2017-03-23 11:48
@ipcctv 
I cannot help with specific issues how to mount something.
Because you wrote "minimal OS" and you got
a "missing ... helper program" error message
I guess your "minimal OS" is too minimal. See also
https://github.com/rear/rear/issues/755

In general regarding how to use a USB medium, see
http://relax-and-recover.org/documentation/getting-started

In particular regarding what "rear format" results,
see the various USB_DEVICE... variables
in usr/share/rear/conf/default.conf

I think the issue is sufficiently answered
so that I close it.

**Closed by jsmeix** 2017-03-23 11:48 UTC
Labels: fixed/solved/done, support/question

**Comment by jsmeix** [comment] 2017-03-23 11:54
@ipcctv 
I noticed that you wrote
<pre>
mount -t ext3 /dev/sdb /mnt
</pre>
Usually this cannot work because there is no
filesystem on /dev/sdb (that is the whole disk)
but a filesystem is e.g. on /dev/sdb1 (first partition)
or /dev/sdb2 (second partition) ...

**Comment by ipcctv** [comment] 2017-03-23 20:22
jsmeix,  thanks. Now I feel stupid :-)  I should and do know better - normally.   That's what you get when you try to do too many jobs at once.  But thanks to everybody too for sharing your time/skills.  Tom.

**Comment by jsmeix** [comment] 2017-03-24 08:17
@ipcctv 
don't worry.
The same kind of things happen also to me.
My preferred way is to think "long and careful" about something,
then I finally ask a "well founded" question on a public forum and
a short time after I had made my "current state of mind" public,
I see who (not what) the root cause is ;-)

Many thanks for your feedback that now things work for you.
