### ISSUE TITLE
Confusing name of configuration directives

### ISSUE THREAD

**Issue by tcerna** [rear/rear#933] opened 2016-07-20 14:15 UTC
* rear version (/usr/sbin/rear -V):
rear-1.17.2

* OS version (cat /etc/rear/os.conf or lsb_release -a):
RHEL-7.2 Server

* Brief description of the issue
 Rear contains two basic possibilities during create backup:
  * Create data backup: user should specify configuration directives BACKUP and BACKUP_URL
  * Create rescue image: user should specify OUTPUT and OUTPUT_URL

We had rear testday and most of participants told that names of configuration directives OUTPUT and OUTPUT_URL are really confusing. They are not able to navigate skillfully if it covers data backup or rescue image. Yes, there is manual page and documentation, they use it, but this problem was still appearing. They proposed renaming this variables to for example RESCUE and RESCUE_URL. Also it is possible to preserve old directives as visible or hide options.

**Comment by scr4bble** [comment] 2016-07-20 15:48
Hi Terka, sorry - I forgot to tell you about filling this issue here. I have opened it 6 days ago.
#920 "confused by names - OUTPUT vs BACKUP variables"

**Comment by jsmeix** [comment] 2016-07-21 07:45
I close this one because it is a duplicate of https://github.com/rear/rear/issues/920

**Closed by jsmeix** 2016-07-21 07:45 UTC
Labels: documentation, enhancement
