### ISSUE TITLE
Teaming interface support is very limited

### ISSUE THREAD

**Issue by rmetrich** [rear/rear#1561] opened 2017-11-03 14:17 UTC
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): Relax-and-Recover 2.00 / Git
* OS version (cat /etc/rear/os.conf or lsb_release -a): RHEL 7, but doesn't matter here
* Brief description of the issue:

The Teaming interface code (360_teaming.sh) doesn't support VLans, Bridges, Bonds, etc, because the code has been split from 310_network_devices.sh.
This is a heavy limitation of the feature.

**Comment by jsmeix** [comment] 2017-11-06 12:58
@rmetrich 
according to what
<pre>
git log -p --follow usr/share/rear/rescue/GNU/Linux/360_teaming.sh
</pre>
shows me the 360_teaming.sh script was
not split from 310_network_devices.sh
but the 360_teaming.sh script was created
separated from scratch via
https://github.com/rear/rear/commit/2cac34fd4f2277cd1095d5ff3f0dd4272f2bb4eb

I assume your intent is to merge the code in 360_teaming.sh
into the 310_network_devices.sh script so that afterwards
the Teaming interface code also supports all what 
310_network_devices.sh already supports?

**Comment by rmetrich** [comment] 2017-11-06 13:06
@jsmeix Exactly, I'd like teaming to just work in all contexts.
If merging in 310_network_devices.sh is acceptable, I'll go ahead and propose a patch.

**Comment by jsmeix** [comment] 2017-11-06 13:28
@rmetrich 
I look forward to your pull request!

At least I accept basically anything that improves ReaR
(even up to dirty hacks that intend to make things work)
provided the code is well explained, cf.
https://github.com/rear/rear/wiki/Coding-Style

**Comment by rmetrich** [comment] 2017-11-10 16:32
@jsmeix FIY, new code currently being tested:
https://github.com/rmetrich/rear/tree/Team
Adds support for crazy setups!

**Comment by jsmeix** [comment] 2017-11-13 11:26
@rmetrich 
I had a quick look at your new code and I am very impressed mainly
because of your good explanation what your code should do.
For me on a first glance it looks very good to do such a
general overhaul and re-implementation and I appreciate
your efforts very much.

But my networking knowledge is only about some basic stuff
so that I cannot really review if the new code is actually o.k.

Therefore other ReaR maintainers with better networking knowledge
would have to actually review if your new code is o.k.

Because your new code is basically a re-write of
rescue/GNU/Linux/310_network_devices.sh
I think we may have to postpone that big change
after the current upcoming ReaR 2.3 was released
(i.e. for the next ReaR 2.4 release) to avoid
possible (unexpected) regressions in ReaR 2.3.

**Comment by jsmeix** [comment] 2018-01-17 08:10
With https://github.com/rear/rear/pull/1574 merged
this issue should be fixed.

**Closed** 2018-01-17 08:10 UTC
Labels: cleanup, enhancement, fixed/solved/done

**Comment by jsmeix** [comment] 2018-01-17 08:18
@rmetrich 
many thanks for cleaning up scatteded pieces of code
that actually belongs to one same functionality
into one piece of code in one single script.
