### ISSUE TITLE
Trying to clone from rear backup of SLES12 SP3 SAP fails on Power lpar

### ISSUE THREAD

**Issue by dewagner1** [rear/rear#2000] opened 2018-12-06 18:46 UTC
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"):
esashxigo171:/dev # /usr/sbin/rear -V
Relax-and-Recover 2.4 / Git

* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"):
esashxigo171:/dev # cat /etc/rear/os.conf
OS_VENDOR=SUSE_LINUX
OS_VERSION=12

* ReaR configuration files ("cat /etc/rear/site.conf" and/or "cat /etc/rear/local.conf"):
esashxigo171:/dev # cat /etc/rear/local.conf
AUTOEXCLUDE_MULTIPATH=n
BOOT_OVER_SAN=y
REAR_INITRD_COMPRESSION=lzma
OUTPUT=ISO
ISO_MAX_SIZE=4000
BACKUP=NETFS
BACKUP_URL=iso:///iso_fs/REAR_BACKUP
ISO_DIR=/iso_fs/REAR_ISO
TMPDIR=/iso_fs/REAR_TEMP
OUTPUT_URL=null
BOOT_FROM_SAN=y
EXCLUDE_MOUNTPOINTS=( /iso_fs )
EXCLUDE_COMPONENTS=( /dev/mapper/36005076400810051380000000000006d /dev/mapper/36005076400810051380000000000007b /dev/mapper/36005076400810051380000000000007c /dev/mapper/36005076400810051380000000000007d /dev/mapper/36005076400810051380000000000007e /dev/mapper/36005076400810051380000000000007f /dev/mapper/360050764008100513800000000000080 /dev/mapper/360050764008100513800000000000088 )

* Hardware (PC or PowerNV BareMetal or ARM) or virtual machine (KVM guest or PoverVM LPAR):
Power Lpar

* System architecture (x86 compatible or PPC64/PPC64LE or what exact ARM device):
PPC64LE

* Firmware (BIOS or UEFI or Open Firmware) and bootloader (GRUB or ELILO or Petitboot):
GRUB

* Storage (lokal disk or SSD) and/or SAN (FC or iSCSI or FCoE) and/or multipath (DM or NVMe):
SAN FC multipath

* Description of the issue (ideally so that others can reproduce it):
Built a new SLES 12 SP3 SAP system and created a rear backup.  Trying to clone to another lpar fails.

* Workaround, if any:
None

* Attachments, as applicable ("rear -D mkrescue/mkbackup/recover" debug log files):
[eniesdbs101_RearRecoverDebug.txt](https://github.com/rear/rear/files/2654383/eniesdbs101_RearRecoverDebug.txt)

**Comment by jsmeix** [comment] 2018-12-07 08:12
@dewagner1 
your
https://github.com/rear/rear/files/2654383/eniesdbs101_RearRecoverDebug.txt
contains (excerpts):
<pre>
+ source /usr/share/rear/verify/NETFS/default/060_mount_NETFS_path.sh
...
++ mount_url iso:///iso_fs/REAR_BACKUP /tmp/rear.zPDBCQZF4G6Z2X7/outputfs
++ local url=iso:///iso_fs/REAR_BACKUP
++ local mountpoint=/tmp/rear.zPDBCQZF4G6Z2X7/outputfs
++ local defaultoptions=rw,noatime
++ local options=rw,noatime
++ local mount_cmd
++ case $(url_scheme $url) in
+++ url_scheme iso:///iso_fs/REAR_BACKUP
+++ local url=iso:///iso_fs/REAR_BACKUP
+++ local scheme=iso
+++ echo iso
+++ grep -q :
+++ echo iso
++ [[ recover = \r\e\c\o\v\e\r ]]
++ mount_cmd='mount /dev/disk/by-label/RELAXRECOVER /tmp/rear.zPDBCQZF4G6Z2X7/outputfs'
++ Log 'Mounting with '\''mount /dev/disk/by-label/RELAXRECOVER /tmp/rear.zPDBCQZF4G6Z2X7/outputfs'\'''
+++ date '+%Y-%m-%d %H:%M:%S.%N '
++ local 'timestamp=2018-12-06 18:07:30.404691098 '
++ test 1 -gt 0
++ echo '2018-12-06 18:07:30.404691098 Mounting with '\''mount /dev/disk/by-label/RELAXRECOVER /tmp/rear.zPDBCQZF4G6Z2X7/outputfs'\'''
2018-12-06 18:07:30.404691098 Mounting with 'mount /dev/disk/by-label/RELAXRECOVER /tmp/rear.zPDBCQZF4G6Z2X7/outputfs'
++ eval mount /dev/disk/by-label/RELAXRECOVER /tmp/rear.zPDBCQZF4G6Z2X7/outputfs
+++ mount /dev/disk/by-label/RELAXRECOVER /tmp/rear.zPDBCQZF4G6Z2X7/outputfs
mount: you must specify the filesystem type
++ StopIfError 'Mount command '\''mount /dev/disk/by-label/RELAXRECOVER /tmp/rear.zPDBCQZF4G6Z2X7/outputfs'\'' failed.'
++ ((  1 != 0  ))
++ Error 'Mount command '\''mount /dev/disk/by-label/RELAXRECOVER /tmp/rear.zPDBCQZF4G6Z2X7/outputfs'\'' failed.'
...
++ echo -e 'Some latest log messages since the last called script 060_mount_NETFS_path.sh:'
++ echo -e '  2018-12-06 18:07:30.396131630 Including verify/NETFS/default/060_mount_NETFS_path.sh
  2018-12-06 18:07:30.397077974 Entering debugscripts mode via '\''set -x'\''.
  mkdir: created directory '\''/tmp/rear.zPDBCQZF4G6Z2X7/outputfs'\''
  2018-12-06 18:07:30.401750143 Added '\''rmdir -v /tmp/rear.zPDBCQZF4G6Z2X7/outputfs >&2'\'' as an exit task
  2018-12-06 18:07:30.404691098 Mounting with '\''mount /dev/disk/by-label/RELAXRECOVER /tmp/rear.zPDBCQZF4G6Z2X7/outputfs'\''
  mount: you must specify the filesystem type'
</pre>
which matches
https://github.com/rear/rear/issues/1891#issuecomment-410749428
so that this issue is a duplicate of your
https://github.com/rear/rear/issues/1891
which should have been fixed via
https://github.com/rear/rear/issues/1893
and
https://github.com/rear/rear/pull/1894
which are included in the SUSE rear23a RPM package,
cf. the section about
"rear / rear116 / rear1172a / rear118a / rear23a" in
https://en.opensuse.org/SDB:Disaster_Recovery

Your eniesdbs101_RearRecoverDebug.txt excerpts above show
that you use the old mount_url before https://github.com/rear/rear/pull/1894
so that you need to update your ReaR to one where that issue is fixed.

If it is not fixed with a current ReaR you should of course reopen this issue.

**Closed by jsmeix** 2018-12-07 08:12 UTC
Labels: fixed / solved / done, support / question
