### ISSUE TITLE
Rear install fails on Debian 7 i386 missing dependency "isolinux"

### ISSUE THREAD

**Issue by imakiro** [rear/rear#1064] opened 2016-11-10 15:54 UTC
- rear version : 2.19 & 2.18 from http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/Debian_7.0/i386/
and latest git release available in .deb format

- Output of lsb_release -a
```
Distributor ID: Debian
Description:    Debian GNU/Linux 7.11 (wheezy)
Release:        7.11
Codename:       wheezy
```

The installation fails because rear depends on ISOLINUX package that cannot be found of main contrib and non-free repos on debian 7 Wheezy and doesn't exist at all for wheezy.

```
root@debian732:/home/nuabee# dpkg -i rear_1.19_i386.deb
Sélection du paquet rear précédemment désélectionné.
(Lecture de la base de données... 23206 fichiers et répertoires déjà installés.)
Dépaquetage de rear (à partir de rear_1.19_i386.deb) ...
dpkg: des problèmes de dépendances empêchent la configuration de rear :
 rear dépend de isolinux ; cependant :
  Le paquet isolinux n'est pas installé.
 rear dépend de dosfstools ; cependant :
  Le paquet dosfstools n'est pas installé.
 rear dépend de binutils ; cependant :
  Le paquet binutils n'est pas installé.
 rear dépend de parted ; cependant :
  Le paquet parted n'est pas installé.
 rear dépend de openssl ; cependant :
  Le paquet openssl n'est pas installé.
 rear dépend de gawk ; cependant :
  Le paquet gawk n'est pas installé.
 rear dépend de attr ; cependant :
  Le paquet attr n'est pas installé.

dpkg: erreur de traitement de rear (--install) :
 problèmes de dépendances - laissé non configuré
Traitement des actions différées (« triggers ») pour « man-db »...
Des erreurs ont été rencontrées pendant l'exécution :
 rear
```

```
root@debian732:/home/user# apt-get install isolinux dosfstools binutils parted openssl gawk attr
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances
Lecture des informations d'état... Fait
Aucune version du paquet isolinux n'est disponible, mais il existe dans la base
de données. Cela signifie en général que le paquet est manquant, qu'il est devenu obsolète
ou qu'il n'est disponible que sur une autre source

E: Le paquet « isolinux » n'a pas de version susceptible d'être installée

```
C.F. https://packages.debian.org/search?suite=wheezy-backports&searchon=names&keywords=isolinux

I don't know any workaround thus I'm opening this issue. Building from source doesn't help either.

Edit : I git cloned the repo, it seems it's an unnecessary- dependency to create ISO backups, why is this still required then?

**Comment by jsmeix** [comment] 2016-11-11 08:53
I am not a Debian user so that I cannot reproduce
anything here myself but it looks as if
https://github.com/rear/rear/issues/940
could be related or even the reason because
https://github.com/rear/rear/issues/940#issue-167294084
reads:
<pre>
heinlein-support commented on 25 Jul

At Debian 8 they removed some stuff from
the syslinux package and createt "isolinux"
and "extlinux". At Open SuSE Build service
you should add those packages as dependency
for ReaR under Debian .
</pre>

**Comment by imakiro** [comment] 2016-11-14 07:41
Haem,
it seems that by adding compatibility for debian 8, this "fix" wiped the compatibility of Debian 7... How about havin a separate build for debian 7 or 8?

**Comment by gdha** [comment] 2016-11-18 09:32
In the `control` file I find:
`control:Depends: syslinux[!ppc64el], ethtool, ${shlibs:Depends}, lsb-release, xorriso, iproute, iputils-ping, isolinux, dosfstools, binutils, parted, openssl, gawk, attr, ${misc:Depends}`

Is there something wrong with it? I'm not a Debian packaging expert I'm afraid. I'm hoping for years to find an expert in these matters, but nobody seems to stand up,

**Comment by jsmeix** [comment] 2016-11-18 11:10
Neither can I help with Debian packaging but in
https://github.com/rear/rear/issues/940
it looks as if @heinlein-support volunteered
to help with Debian packaging?

**Comment by frediz** [comment] 2017-01-18 11:16
@imakiro , I pushed rear package in Debian Unstable.
But I confirm that isolinux dependency won't be available in Debian Wheezy if you do some pinning and want to drag rear 2.20 from Unstable into your Wheezy installation.
isolinux is only available since Debian Jessie.

**Comment by imakiro** [comment] 2017-01-18 11:21
@frediz is there no workaround for this instead of creating an empty meta package...at each install on every machine? if not is there a way to include a script doing it in an automated way to avoid apt complaining?

**Comment by frediz** [comment] 2017-01-18 11:26
@imakiro sorry, I don't get what you mean exactly.
I fear that officially having rear in Wheezy is not going to happen since it's an old stable version and it won't change unless for security reasons.
Could you explain more please ?

**Comment by imakiro** [comment] 2017-01-18 11:43
@frediz well, the .deb package can still be done, but to be able to install that package on wheezy, it needs a way to fill the dependency issue that is isolinux, to do so implies to either have a specific debian wheezy make deb target or use a script that create an empty package filling in for isolinux in the apt db so that the dependency check doesn't fail...

**Comment by frediz** [comment] 2017-01-18 13:10
@imakiro ok I get it.
Well, I worked on providing an official package in Debian, not on the packaging/debian 
directory in github/rear. So I'm talking of the official Debian way of doing and the .deb
provided by the opensuse build system is not official.
So if you read #1163, you'll see I won't update the packaging here and would advise you
to *try* to migrate to the officially supported .deb in Debian (which sadly means no support
in Wheezy...)
Still, if you want some trick to cheat the package manager to be able to force the
installation of the package, you may try ```dpkg -i --force-depends``` or another
variant (man dpkg).

**Comment by imakiro** [comment] 2017-01-18 16:13
@frediz well, we use ReaR on many systems, and none of the packets given by the rear website and yours as you just said work for wheezy, and unfortunately a few of our machines are out of our upgrade control. So this issue here is more like can we have a proper wheezy package or will the devs of rear drop support for this specific distro, which it is supposedly supporting with a link to http://download.opensuse.org/repositories/Archiving:/Backup:/Rear/Debian_7.0/
on the official website.

**Comment by jsmeix** [comment] 2018-07-18 10:33
Because there are no further comments
I assume this isssue was meanwhile sufficiently answered and handled
so that I can close it hereby.

**Closed by jsmeix** 2018-07-18 10:33 UTC
Labels: fixed/solved/done, support/question
