### ISSUE TITLE
"rear mkrescue" fails with "BUG! Unknown bootloader" - nvme sys block device not included

### ISSUE THREAD

**Issue by miked314** [rear/rear#1326] opened 2017-04-23 15:32 UTC
* rear version (/usr/sbin/rear -V):
`
Relax-and-Recover 2.00 / Git
`

* OS version (cat /etc/rear/os.conf or lsb_release -a):
`
LSB modules are available. 
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty
`
* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
`OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL="nfs://xxx.xxx.xxx.xxx/mnt/BigBerta/backup/"
`
* Are you using legacy BIOS or UEFI boot?
UEFI
* Brief description of the issue:
"rear mkrescue" fails with "BUG! Unknown bootloader"
file /usr/share/rear/prep/default/500_guess_bootloader.sh looks for block devices in /sys/block
that start with: hd sd cciss vd xvd however im using nvme disk and block device appear as nvme0n1 on my DELL XPS 13 

michal@xps:~$ ll /sys/block/
total 0
drwxr-xr-x  2 root root 0 Apr 23 10:21 ./
dr-xr-xr-x 13 root root 0 Apr 23 08:40 ../
lrwxrwxrwx  1 root root 0 Apr 22 21:31 loop0 -> ../devices/virtual/block/loop0/
lrwxrwxrwx  1 root root 0 Apr 22 21:31 loop1 -> ../devices/virtual/block/loop1/
lrwxrwxrwx  1 root root 0 Apr 22 21:31 loop2 -> ../devices/virtual/block/loop2/
lrwxrwxrwx  1 root root 0 Apr 22 21:31 loop3 -> ../devices/virtual/block/loop3/
lrwxrwxrwx  1 root root 0 Apr 22 21:31 loop4 -> ../devices/virtual/block/loop4/
lrwxrwxrwx  1 root root 0 Apr 22 21:31 loop5 -> ../devices/virtual/block/loop5/
lrwxrwxrwx  1 root root 0 Apr 22 21:31 loop6 -> ../devices/virtual/block/loop6/
lrwxrwxrwx  1 root root 0 Apr 22 21:31 loop7 -> ../devices/virtual/block/loop7/
lrwxrwxrwx  1 root root 0 Apr 22 15:50 nvme0n1 -> ../devices/pci0000:00/0000:00:1d.0/0000:3c:00.0/nvme/nvme0/nvme0n1/
* Work-around, if any:
change line 15 in /usr/share/rear/prep/default/500_guess_bootloader.sh
from 
    if [[ $blockd = hd* || $blockd = sd* || $blockd = cciss* || $blockd = vd* || $blockd = xvd*  ]] ; then
to:
    if [[ $blockd = hd* || $blockd = sd* || $blockd = cciss* || $blockd = vd* || $blockd = xvd* || $blockd = nvme* ]] ; then

**Comment by gozora** [comment] 2017-04-23 16:14
@miked314  I guess you are a bit late ;-).
Until I'm not wrong, something similar was fixed in https://github.com/rear/rear/pull/1191 

V.

**Comment by miked314** [comment] 2017-04-23 21:53
Yes. You are right. I didn't​ check recent bug fixes.

**Comment by jsmeix** [comment] 2017-04-24 10:12
I think the issue is solved via https://github.com/rear/rear/pull/1191

@miked314 FYI:

How to test the currently newest ReaR GitHub master code
(even independent of an already installed ReaR software):

Basically "git clone" it into a directory and then
configure and run it from within that directory like:
<pre>
# git clone https://github.com/rear/rear.git

# cd rear

# vi etc/rear/local.conf

# usr/sbin/rear -d -D mkbackup
</pre>
(note the relative paths "etc/rear/" and "usr/sbin/").

**Closed by jsmeix** 2017-04-24 10:12 UTC
Labels: enhancement, fixed/solved/done, support/question
