### ISSUE TITLE
Need to fix "200_run_layout_code.sh"

### ISSUE THREAD

**Issue by kodiss** [rear/rear#1835] opened 2018-06-19 07:07 UTC
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* ReaR version ("/usr/sbin/rear -V"): 2.3.1
* OS version ("cat /etc/rear/os.conf" or "lsb_release -a" or "cat /etc/os-release"): Redhatenterprise7
* System architecture (x86 compatible or POWER and/or what kind of virtual machine): x86
* Are you using BIOS or UEFI or another way to boot? UEFI
* Brief description of the issue: 
   When i  rear recover, i got the error message like below
![1](https://user-images.githubusercontent.com/19543458/41581751-7f7234ba-73da-11e8-8445-25be0f2f5df0.png)

* Work-around, if any:
i modify the command 
from  ' part /dev/sda XXX XXX EFI0x20System0x20Partition boot /devsda1' 
to ' part /dev/sda XXX XXX "EFI0x20System0x20Partition" boot /devsda1' 
please modify the script for blank.

![2](https://user-images.githubusercontent.com/19543458/41581752-814ea37c-73da-11e8-9211-a5d5b5b55d71.png)

**Comment by jsmeix** [comment] 2018-06-19 07:30
@kodiss 
see
https://github.com/rear/rear/issues/1824#issuecomment-395080565

Summary:

This issue is a duplicate of
https://github.com/rear/rear/issues/1563
which was fixed after the ReaR 2.3 release.

To use a ReaR version where this issue should be already fixed:

I recommend to use our current ReaR upstream GitHub master code
because that is the only place where we fix bugs - i.e. bugs in released
ReaR versions are not fixed by us (i.e. by ReaR upstream).
Bugs in released ReaR versions that got fixed in current ReaR upstream
GitHub master code might be fixed (if the fix can be backported with reasonable effort)
by the Linux distributor wherefrom you got your ReaR version.

To use our current ReaR upstream GitHub master code do the following:

Basically "git clone" it into a separated directory and then
configure and run ReaR from within that directory like:
<pre>
# git clone https://github.com/rear/rear.git

# mv rear rear.github.master

# cd rear.github.master

# vi etc/rear/local.conf

# usr/sbin/rear -D mkbackup
</pre>
Note the relative paths "etc/rear/" and "usr/sbin/".

**Closed by jsmeix** 2018-06-19 07:30 UTC
Labels: fixed/solved/done, support/question
