### ISSUE TITLE
udev failed to start on Debian 8.8, rear 2.1

### ISSUE THREAD

**Issue by bmarshmn** [rear/rear#1416] opened 2017-07-15 03:46 UTC
#### Relax-and-Recover (ReaR) Issue Template

Fill in the following items before submitting a new issue
(quick response is not guaranteed with free support):

* rear version (/usr/sbin/rear -V): 2.1
* OS version (cat /etc/rear/os.conf or lsb_release -a):
Distributor ID:	Wazo
Description:	Wazo GNU/Linux 8.8 (jessie)
Release:	8.8
Codename:	jessie

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
OUTPUT=USB

### create a backup using the internal NETFS method, using 'tar'
BACKUP=NETFS

### write both rescue image and backup to the device labeled REAR-000
BACKUP_URL=usb:///dev/disk/by-label/REAR-000

* Are you using legacy BIOS or UEFI boot?
pretty sure legacy
* Brief description of the issue:
when booting from the USB stick, systemd-udevd.service failed to start
w/out udev the LVM names were not updated in /dev and the LVM create was unable to proceed

* Work-around, if any:
I found this, https://github.com/rear/rear/pull/601
and when I created the symlinks per the script, udev was able to start

**Comment by jsmeix** [comment] 2017-07-18 16:05
@bmarshmn 
your described workaround indicates that the script
usr/share/rear/build/Debian/610_jessie_link_systemd_lib.sh
is not run in your case when you run
"rear mkbackup" or "rear mkrescue".

To check that run
<pre>
rear -s mkrescue | grep ' build/'
</pre>
which shows what 'build' stage scripts are run in your case.

**Comment by gdha** [comment] 2017-11-17 15:18
On **Ubuntu** I get:
````
# rear -s mkrescue | grep jes
Source build/Debian/610_jessie_link_systemd_lib.sh
````
The script does run. Or, it is an USB issue or something is wrong with the script? Ubuntu tests performed by me are ISO and PXE not USB, so I cannot tell
@bmarshmn Any further input from your side?

**Comment by gdha** [comment] 2018-05-15 06:56
As we cannot reproduce this problem reported we label it "won't fix"

**Closed by gdha** 2018-05-15 06:56 UTC
Labels: support/question, won't fix / can't fix
