### ISSUE TITLE
usage of get_template is wrong in 95_copy_result_files.sh

### ISSUE THREAD

**Issue by gdha** [rear/rear#1050] opened 2016-10-25 11:15 UTC
- rear version (/usr/sbin/rear -V): 1.19 (and earlier version as well)
- OS version (cat /etc/rear/os.conf or lsb_release  -a): n/a
- rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf): n/a
- Brief description of the issue:

```
./default/95_copy_result_files.sh:get_template "RESULT_usage_$OUTPUT.txt" > "$TMP_DIR/README" 
```

The `get_template` function returns the file name and not the content of that file, therefore we still need a copy command for it as for example in:

```
95_dsmc_save_result_files.sh: cp $v $(get_template "RESULT_usage_$OUTPUT.txt") "$TSM_RESULT_FILE_PATH/README"
```

**Comment by jsmeix** [comment] 2016-11-24 17:54
The issue is marked as "fixed"
so that I asssume it can be closed.

**Closed by jsmeix** 2016-11-24 17:54 UTC
Labels: bug, fixed
