### ISSUE TITLE
Duplicate ISO images - /backup/fedora.iso and /var/lib/rear/output/fedora.iso

### ISSUE THREAD

**Issue by phracek** [rear/rear#802] opened 2016-03-23 13:05 UTC
# Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue:
- rear version (/usr/sbin/rear -V): 1.18
- OS version (cat /etc/rear/os.conf or lsb_release  -a):  Fedora 23
- rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):

```
OUTPUT=ISO
BACKUP=NETFS
BACKUP_URL=iso://backup
#OUTPUT_URL="nfs:///192.168.122.1/"
OUTPUT_URL=file:///backup
EXCLUDE_MOUNTPOINTS=(/home/* /usr/lib/* /run/* /var/* /sys/* /opt/*)
BACKUP_PROG_EXCLUDE=("${BACKUP_PROG_EXCLUDE[@]}" '/media/' '/var/rmp' '/var/crash')
```
- Brief description of the issue: ISO image is created in ''/backup/fedora.iso'' but ''/var/lib/rear/output/fedora.iso'' exists too.
- Work-around, if any

**Comment by gdha** [comment] 2016-03-23 16:33
See also #734 - it did not get in 1.18 on time.

**Comment by gdha** [comment] 2016-09-13 14:36
Move milestone once again due to lack of funding

**Comment by jmazanek** [comment] 2016-10-11 14:45
Feature is already implemented in Rear v1.17 . The following configuration works exactly as requested:

#/etc/rear/local.conf
OUTPUT=ISO
BACKUP=NETFS
OUTPUT_URL=null
BACKUP_URL="iso:///backup"
ISO_DIR="/home/test_rear"  #Here should be the custom location for iso.

But it is not very intuitive, unless you look into code and you know what variable $ISO_DIR is used for and you figure out that directives in default.conf can be redefined in local.conf.

Is it intended behaviour? Is variable $ISO_DIR  meant to be used as a standalone configuration directive? If yes, it should be documented.

**Comment by jmazanek** [comment] 2016-10-27 13:30
@gdha  Perhaps my last post regarding duplicate iso images was overlooked among the other comments. I think it can prevent lot of unnecessary work in the future. This solution is already being used on enterprise production system with positive feedback

**Comment by gdha** [comment] 2016-12-31 09:59
Need to think about it, but it won't be for ReaR v2.0 I'm afraid.

**Comment by gdha** [comment] 2017-04-25 18:43
@gdha Add it to the documentation as a FAQ?

**Comment by gdha** [comment] 2017-06-01 07:10
As default.conf file entry ISO_DIR has now a better explanation we can close this issue.

**Closed by gdha** 2017-06-01 07:10 UTC
Labels: documentation, enhancement, needs sponsorship
