### ISSUE TITLE
The savefs command could not retrieve the "save sets" from this client

### ISSUE THREAD

**Issue by viper1986** [rear/rear#829] opened 2016-05-11 06:46 UTC
[rear-itehana01.zip](https://github.com/rear/rear/files/258693/rear-itehana01.zip)

# Relax-and-Recover (rear) Issue Template

Please fill in the following items before submitting a new issue:

* rear version (/usr/sbin/rear -V): Relax-and-Recover 1.17.1 / Git
* OS version (cat /etc/rear/os.conf or lsb_release  -a):
LSB Version:    core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-ppc64:core-3.2-ppc64:core-4.0-ppc64:desktop-4.0-noarch:desktop-4.0-ppc32:desktop-4.0-ppc64:graphics-2.0-noarch:graphics-2.0-ppc32:graphics-2.0-ppc64:graphics-3.2-noarch:graphics-3.2-ppc32:graphics-3.2-ppc64:graphics-4.0-noarch:graphics-4.0-ppc32:graphics-4.0-ppc64
Distributor ID: SUSE LINUX
Description:    SUSE Linux Enterprise Server 11 (ppc64)
Release:        11
Codename:       n/a

* rear configuration files (cat /etc/rear/site.conf or cat /etc/rear/local.conf):
/etc/rear/site.conf
BACKUP=NSR
OUTPUT=ISO
OUTPUT_URL=nfs://t301-dd10.itebck.local/data/col1/rear
NSRSERVER=c301bcksrv
POOLNAME=ddos
RETENTION_TIME=Weeks
USE_CFG2HTML=y

* Brief description of the issue
I try use REAR on SLES 11 on Power platform. Configure client from the Networker site, but REAR can't find the save set for backup. When I start the command in bash everythink works fine and the output is correctly.
I configure some time ago similar server and I don't have any problem.
Also for x64 platform everythink works correctly.

cat 47_safe_filesystems.sh
savefs -D2 -p -s $NSRSERVER 2>&1 |grep -ie 'path\(: \|=\)\/' |awk -F '(: |=|;|,)' '{print $2}' > $VAR_DIR/recovery/nsr_paths

**Comment by viper1986** [comment] 2016-05-11 07:20
I just find the solution.
Missing package glibc-locale 32bit version.

Close the ticket please.

**Comment by jsmeix** [comment] 2016-05-11 08:21
In general I am interested in any issues with
Relax-and-Recover on SUSE systems.

In this case I like to understand why the
package glibc-locale-32bit was missing.
Shouldn't it be normally always installed?

I am not a glibc expert but I wonder why
glibc-locale stuff is needed at all by rear
because /usr/sbin/rear contains
<pre>
# Make sure that we use only English:
export LC_CTYPE=C LC_ALL=C LANG=C
</pre>
so that I assume rear should work independent
of any localization stuff?
I did a quick test on a SLE11 x86_64 system what hapens
without glibc-locale packages:
<pre>
# rpm -qa | grep glibc-locale
glibc-locale-32bit-2.11.3-17.84.1
glibc-locale-2.11.3-17.84.1

# rpm -e --test glibc-locale-32bit

# rpm -e --test glibc-locale      
error: Failed dependencies:
glibc-locale is needed by (installed) yast2-ncurses-2.17.23-1.14.x86_64
glibc-locale is needed by (installed) yast2-ncurses-pkg-2.17.20-0.5.1.x86_64

# rpm -e glibc-locale-32bit
# rpm -e --nodeps glibc-locale

# export LC_CTYPE=de_DE LC_ALL=de_DE LANG=de_DE
# locale -a
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
C
POSIX

# export LC_CTYPE=C LC_ALL=C LANG=C
# locale -a
C
POSIX
</pre>
It seems with "export LC_CTYPE=C LC_ALL=C LANG=C"
things "just work" even without localization packages.

@viper1986 
I do not fuly understand your description of the issue.
Note that I do not have any of the third party backup tools
that are supported by rear here on my worstation
so that I cannot reproduce any issues with third party backup
tools on my own which means I need an explanatory description
in case of issues with third party backup tools so that I have
a chance to understand what goes on.

What do you mean with 
"Configure client from the Networker site"?
What is "the client"?
I guess it is the system where rear runs.

What do you mean with
"REAR can't find the save set for backup"?
What exactly is meant with "REAR"?
I.e. which exact "rear ..." command did you run
where the issue happens?
E.g. did it happen while "rear mkbackup" runs
or while "rear recover" runs?

What do you mean with
"When I start the command in bash"?
Which exact command did you run manuanlly
and in which environment did you run it?
In the normal running system (i.e. where you
also run "rear mkbackup") or in the rear recovery system
(i.e. where you run "rear recover")?

**Comment by viper1986** [comment] 2016-05-11 08:46
I think that 32bits library is not normally instaled on ppc64 SUSE.
I don't install this system, so I don't know that this package is required.

You tested this on x86_64, but I have PPC64. I don't have this error for x86_64.

"Configure client from the Networker site"?
I must configure host which I want to backup via Networker on Networker serwer.
Add IP address and hostname ( witch FQDN ).
Client is the definition of host that you want to backup on Networker.

"REAR can't find the save set for backup"?
What exactly is meant with "REAR"?
REAR - Relax-and-Recover
It happen when I run rear mkbackup.
And I got error:
The savefs command could not retrieve the "save sets" from this client.

"When I start the command in bash"?
In command line.
savefs -D2 -p -s c301bcksrv 2>&1 |grep -ie 'path(: |=)\/' |awk -F '(: |=|;|,)' '{print $2}'

itehana01:/home # savefs -D2 -p -s c301bcksrv 2>&1 |grep -ie 'path\(: \|=\)\/' |awk -F '(: |=|;|,)' '{print $2}'
/
/tmp
/var
/hana/data
/hana/log
/hana/shared
/usr/sap
/install

This is the same system where I run "rear mkbackup".

I don't exactly why, but when I install glibc-locale-32bit all action performed correctly.

**Comment by jsmeix** [comment] 2016-05-11 09:48
Many thanks for your prompt reply!

I will try if I can somehow reproduce it...

**Comment by jsmeix** [comment] 2016-09-28 13:27
I am afraid - I won't find the time to try to reproduce it.
According to
https://github.com/rear/rear/issues/829#issuecomment-218381546
I close it now.

**Closed by jsmeix** 2016-09-28 13:27 UTC
Labels: support
