### ISSUE TITLE
New solution for GitHub push emails

### ISSUE THREAD

**Issue by schlomo** [rear/rear#1956] opened 2018-11-07 20:07 UTC
Currently the [Relax-and-Recover Development](http://lists.relax-and-recover.org/mailman/listinfo/rear-devel) mailing list receives an email for every change in our GitHub ReaR repo.

As GitHub is deprecGitHub is discontinuing their [email notification service](https://help.github.com/articles/about-email-service-notifications-for-pushes-to-your-repository/). We need to

- [ ] decide amongst @rear/contributors if we want to continue the GitHub commit emails
- [ ] find a new solution for delivering commit emails

**Comment by schlomo** [comment] 2018-11-07 20:34
FWIW, it seems like the only postings on the rear-devel list are those GitHub push notifications. Maybe it will be simpler for everybody involved if those who want to have them solve this on their own.

**Comment by jsmeix** [comment] 2018-11-08 09:07
I wish to also include @rmetrich here because I assume
he and @schabrolles and perhaps also @gozora
are in the same situation as I am:

As far as I understand
https://developer.github.com/v3/guides/replacing-github-services/
<pre>
We have deprecated GitHub Services in favor of integrating with webhooks.
</pre>
and
https://developer.github.com/webhooks/#events
<pre>
Webhooks allow you to build or set up GitHub Apps which subscribe
to certain events on GitHub.com. When one of those events is triggered,
we'll send a HTTP POST payload to the webhook's configured URL. 
</pre>
plus
https://en.wikipedia.org/wiki/POST_(HTTP)
<pre>
By design, the POST request method requests that a web server accepts
the data enclosed in the body of the request message,
</pre>
using GitHub webhooks requires each one to run a HTTP server
that accepts data from "out there of the Internet" which means one has to run
a public accessible HTTP server with all the security related consequences.

Because I am inside an internal corporate network behind a big-and-fat
full-featurted corporate firewall I cannot run a public accessible HTTP server
and I am certainly not allowed to do that (even if I could) on any of my own
systems ("own" means where I am 'root') inside our internal company network.

I will ask internally at SUSE what the official way inside SUSE is
how SUSE employees should use GitHub webhooks.

I would be interested what the official way inside IBM, Red Hat, and HP is
how IBM, Red Hat, and HP employees should use GitHub webhooks.

**Comment by rmetrich** [comment] 2018-11-08 10:00
@jsmeix Sorry I have no idea, because I'm no real developer ;-)

**Comment by schabrolles** [comment] 2018-11-08 10:33
We (in IBM) have also the same issue related to security and Firewall.
 
Webhook from github is a bit painfull as http connection from outside is blocked by our firewall.
 
Solution 1: Requesting an exception to have a server in a specific DMZ where outside connection is allowed.
BUT => Security enforcement is really high which really slow down productivity (isolated network, crazy password policy, no root access, tons of justification to porvide..)
 
Solution 2: Mirror the external repo to our internal github-Entreprise repo and run webhook from here.
 
Solution 3: (my personal choice to work with my team) move to gitlab which provide a lot of features for free (private registries, CI/CD, docker regitry...).
The CICD worker node are not working in a push way (gitlab-> server for build) but in a pull way thanks to a gitlabci-agent installed on the server (server pull -> gitlab.com). This allows CI/CD working behind a Firewall.
 
Cordialement / Best Regards
 
                                                 
Sébastien ChabrollesPower Systems Linux CenterIBM Client Center, Montpellier1 rue vieille poste 34000 Montpellier FRANCETel +33 4 99 58 00 81Email : s.chabrolles@fr.ibm.com
 
European Power Systems Linux Center community :https://ibm.biz/PSLC_MOP
         
 
 
----- Original message -----From: "Renaud Métrich" <notifications@github.com>To: rear/rear <rear@noreply.github.com>Cc: "Sébastien Chabrolles" <s.chabrolles@fr.ibm.com>, Mention <mention@noreply.github.com>Subject: Re: [rear/rear] New solution for GitHub push emails (#1956)Date: Thu, Nov 8, 2018 11:00 AM 
@jsmeix Sorry I have no idea, because I'm no real developer ;-)

**Comment by gozora** [comment] 2018-11-08 15:20
My contributions to ReaR are pure hobby, as such I'm luckily not be limited by paranoid corporate network rules ;-).
I'm running my own web server out there in the Internet, so using any kind of webhooks is just a matter of configuration for me. Either way, I'm not paying much of an attention to repo changes mails, so I'll most probably not miss this feature ...

V.

**Comment by jsmeix** [comment] 2018-11-16 14:47
FYI:
On Mon. 12 Nov. I had asked internally at SUSE
how SUSE employees should use GitHub webhooks
but up to now I got no really useful reply
(except some individual band-aid workarounds)...

**Comment by gdha** [comment] 2018-12-25 10:48
I have no real opinion on this matter

**Comment by gdha** [comment] 2020-01-23 15:38
@schlomo Guess we can close this?

**Comment by jsmeix** [comment] 2020-01-27 13:14
FYI:
For me the current GitHub email behaviour still works "good enough".

**Closed** 2020-07-08 01:36 UTC
Labels: ReaR Project, no-issue-activity
